// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/pet/notify_remove_beacon.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifyRemoveBeacon 请求服务器移除宠物技能信标。
//
// NotifyRemoveBeacon asks the server to remove a pet skill beacon.
type NotifyRemoveBeacon struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Basic                  *Basic                  `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	NotifyRemoveBeaconData *NotifyRemoveBeaconData `protobuf:"bytes,2,opt,name=NotifyRemoveBeaconData,proto3" json:"NotifyRemoveBeaconData,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NotifyRemoveBeacon) Reset() {
	*x = NotifyRemoveBeacon{}
	mi := &file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRemoveBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRemoveBeacon) ProtoMessage() {}

func (x *NotifyRemoveBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRemoveBeacon.ProtoReflect.Descriptor instead.
func (*NotifyRemoveBeacon) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRemoveBeacon) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *NotifyRemoveBeacon) GetNotifyRemoveBeaconData() *NotifyRemoveBeaconData {
	if x != nil {
		return x.NotifyRemoveBeaconData
	}
	return nil
}

// NotifyRemoveBeaconData 保存宠物信标字段。
//
// NotifyRemoveBeaconData stores pet beacon fields.
type NotifyRemoveBeaconData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	PetID string                 `protobuf:"bytes,1,opt,name=PetID,proto3" json:"PetID,omitempty"`
	// Go type: []float64
	Position []float64 `protobuf:"fixed64,2,rep,packed,name=Position,proto3" json:"Position,omitempty"`
	// Go type: []float64
	MixColor      []float64 `protobuf:"fixed64,3,rep,packed,name=MixColor,proto3" json:"MixColor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRemoveBeaconData) Reset() {
	*x = NotifyRemoveBeaconData{}
	mi := &file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRemoveBeaconData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRemoveBeaconData) ProtoMessage() {}

func (x *NotifyRemoveBeaconData) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRemoveBeaconData.ProtoReflect.Descriptor instead.
func (*NotifyRemoveBeaconData) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyRemoveBeaconData) GetPetID() string {
	if x != nil {
		return x.PetID
	}
	return ""
}

func (x *NotifyRemoveBeaconData) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NotifyRemoveBeaconData) GetMixColor() []float64 {
	if x != nil {
		return x.MixColor
	}
	return nil
}

var File_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDesc = "" +
	"\n" +
	"9py_rpc/mod_event/minecraft/pet/notify_remove_beacon.proto\x12Rmousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon\x1a*py_rpc/mod_event/minecraft/pet/basic.proto\"\x9b\x02\n" +
	"\x12NotifyRemoveBeacon\x12`\n" +
	"\x05Basic\x18\x01 \x01(\v2J.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.BasicR\x05Basic\x12\xa2\x01\n" +
	"\x16NotifyRemoveBeaconData\x18\x02 \x01(\v2j.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeaconDataR\x16NotifyRemoveBeaconData\"f\n" +
	"\x16NotifyRemoveBeaconData\x12\x14\n" +
	"\x05PetID\x18\x01 \x01(\tR\x05PetID\x12\x1a\n" +
	"\bPosition\x18\x02 \x03(\x01R\bPosition\x12\x1a\n" +
	"\bMixColor\x18\x03 \x03(\x01R\bMixColorBeZcgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/pet;petb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_goTypes = []any{
	(*NotifyRemoveBeacon)(nil),     // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeacon
	(*NotifyRemoveBeaconData)(nil), // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeaconData
	(*Basic)(nil),                  // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
}
var file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeacon.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeacon.NotifyRemoveBeaconData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.notify_remove_beacon.NotifyRemoveBeaconData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_init() }
func file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_init() {
	if File_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_pet_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto = out.File
	file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_pet_notify_remove_beacon_proto_depIdxs = nil
}
