// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/pet/pet_skill_remove_beacon.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PetSkillRemoveBeacon 表示宠物临时技能信标消失。
//
// PetSkillRemoveBeacon indicates that a temporary pet skill beacon disappeared.
type PetSkillRemoveBeacon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	// int64 是宠物运行时 ID。
	//
	// int64 is the pet runtime ID.
	PetID         string `protobuf:"bytes,2,opt,name=PetID,proto3" json:"PetID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSkillRemoveBeacon) Reset() {
	*x = PetSkillRemoveBeacon{}
	mi := &file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkillRemoveBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkillRemoveBeacon) ProtoMessage() {}

func (x *PetSkillRemoveBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkillRemoveBeacon.ProtoReflect.Descriptor instead.
func (*PetSkillRemoveBeacon) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *PetSkillRemoveBeacon) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *PetSkillRemoveBeacon) GetPetID() string {
	if x != nil {
		return x.PetID
	}
	return ""
}

var File_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDesc = "" +
	"\n" +
	"<py_rpc/mod_event/minecraft/pet/pet_skill_remove_beacon.proto\x12Umousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.pet_skill_remove_beacon\x1a*py_rpc/mod_event/minecraft/pet/basic.proto\"\x8e\x01\n" +
	"\x14PetSkillRemoveBeacon\x12`\n" +
	"\x05Basic\x18\x01 \x01(\v2J.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.BasicR\x05Basic\x12\x14\n" +
	"\x05PetID\x18\x02 \x01(\tR\x05PetIDBeZcgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/pet;petb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_goTypes = []any{
	(*PetSkillRemoveBeacon)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.pet_skill_remove_beacon.PetSkillRemoveBeacon
	(*Basic)(nil),                // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
}
var file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.pet_skill_remove_beacon.PetSkillRemoveBeacon.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_init() }
func file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_init() {
	if File_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_pet_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto = out.File
	file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_pet_pet_skill_remove_beacon_proto_depIdxs = nil
}
