// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/pet/sc_pet_play_animation.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SCPetPlayAnimation 广播宠物播放动画。
//
// SCPetPlayAnimation broadcasts pet animation playback.
type SCPetPlayAnimation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Basic            *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	PetAnimationData *PetAnimationData      `protobuf:"bytes,2,opt,name=PetAnimationData,proto3" json:"PetAnimationData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SCPetPlayAnimation) Reset() {
	*x = SCPetPlayAnimation{}
	mi := &file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCPetPlayAnimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCPetPlayAnimation) ProtoMessage() {}

func (x *SCPetPlayAnimation) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCPetPlayAnimation.ProtoReflect.Descriptor instead.
func (*SCPetPlayAnimation) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescGZIP(), []int{0}
}

func (x *SCPetPlayAnimation) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *SCPetPlayAnimation) GetPetAnimationData() *PetAnimationData {
	if x != nil {
		return x.PetAnimationData
	}
	return nil
}

// PetAnimationData 保存宠物动画同步字段。
//
// PetAnimationData stores pet animation sync fields.
type PetAnimationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetID         string                 `protobuf:"bytes,1,opt,name=PetID,proto3" json:"PetID,omitempty"`
	PlayerID      string                 `protobuf:"bytes,2,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Anim          string                 `protobuf:"bytes,3,opt,name=Anim,proto3" json:"Anim,omitempty"`
	Looped        bool                   `protobuf:"varint,4,opt,name=Looped,proto3" json:"Looped,omitempty"`
	ActionID      int64                  `protobuf:"varint,5,opt,name=ActionID,proto3" json:"ActionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAnimationData) Reset() {
	*x = PetAnimationData{}
	mi := &file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAnimationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAnimationData) ProtoMessage() {}

func (x *PetAnimationData) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAnimationData.ProtoReflect.Descriptor instead.
func (*PetAnimationData) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescGZIP(), []int{1}
}

func (x *PetAnimationData) GetPetID() string {
	if x != nil {
		return x.PetID
	}
	return ""
}

func (x *PetAnimationData) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PetAnimationData) GetAnim() string {
	if x != nil {
		return x.Anim
	}
	return ""
}

func (x *PetAnimationData) GetLooped() bool {
	if x != nil {
		return x.Looped
	}
	return false
}

func (x *PetAnimationData) GetActionID() int64 {
	if x != nil {
		return x.ActionID
	}
	return 0
}

var File_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDesc = "" +
	"\n" +
	":py_rpc/mod_event/minecraft/pet/sc_pet_play_animation.proto\x12Smousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation\x1a*py_rpc/mod_event/minecraft/pet/basic.proto\"\x8a\x02\n" +
	"\x12SCPetPlayAnimation\x12`\n" +
	"\x05Basic\x18\x01 \x01(\v2J.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.BasicR\x05Basic\x12\x91\x01\n" +
	"\x10PetAnimationData\x18\x02 \x01(\v2e.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.PetAnimationDataR\x10PetAnimationData\"\x8c\x01\n" +
	"\x10PetAnimationData\x12\x14\n" +
	"\x05PetID\x18\x01 \x01(\tR\x05PetID\x12\x1a\n" +
	"\bPlayerID\x18\x02 \x01(\tR\bPlayerID\x12\x12\n" +
	"\x04Anim\x18\x03 \x01(\tR\x04Anim\x12\x16\n" +
	"\x06Looped\x18\x04 \x01(\bR\x06Looped\x12\x1a\n" +
	"\bActionID\x18\x05 \x01(\x03R\bActionIDB_Z]github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/pet;petb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_goTypes = []any{
	(*SCPetPlayAnimation)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.SCPetPlayAnimation
	(*PetAnimationData)(nil),   // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.PetAnimationData
	(*Basic)(nil),              // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
}
var file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.SCPetPlayAnimation.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.SCPetPlayAnimation.PetAnimationData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.sc_pet_play_animation.PetAnimationData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_init() }
func file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_init() {
	if File_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_pet_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto = out.File
	file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_pet_sc_pet_play_animation_proto_depIdxs = nil
}
