// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/pet/swap_pet_bag_item.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SwapPetBagItem 同步宠物背包物品交换。
//
// SwapPetBagItem syncs pet-bag item swaps.
type SwapPetBagItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Basic              *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	SwapPetBagItemData *SwapPetBagItemData    `protobuf:"bytes,2,opt,name=SwapPetBagItemData,proto3" json:"SwapPetBagItemData,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SwapPetBagItem) Reset() {
	*x = SwapPetBagItem{}
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapPetBagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPetBagItem) ProtoMessage() {}

func (x *SwapPetBagItem) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPetBagItem.ProtoReflect.Descriptor instead.
func (*SwapPetBagItem) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP(), []int{0}
}

func (x *SwapPetBagItem) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *SwapPetBagItem) GetSwapPetBagItemData() *SwapPetBagItemData {
	if x != nil {
		return x.SwapPetBagItemData
	}
	return nil
}

// SwapPetBagItemData 保存宠物背包交换字段。
//
// SwapPetBagItemData stores pet-bag item swap fields.
type SwapPetBagItemData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerID string                 `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	FromSlot int64                  `protobuf:"varint,2,opt,name=FromSlot,proto3" json:"FromSlot,omitempty"`
	ToSlot   int64                  `protobuf:"varint,3,opt,name=ToSlot,proto3" json:"ToSlot,omitempty"`
	// Go type: *SwapPetBagItemItem
	FromItem *SwapPetBagItemItem `protobuf:"bytes,4,opt,name=FromItem,proto3" json:"FromItem,omitempty"`
	// Go type: *SwapPetBagItemItem
	ToItem *SwapPetBagItemItem `protobuf:"bytes,5,opt,name=ToItem,proto3" json:"ToItem,omitempty"`
	// Go type: float64
	TakePercent   float64 `protobuf:"fixed64,6,opt,name=TakePercent,proto3" json:"TakePercent,omitempty"`
	IsNewRequest  bool    `protobuf:"varint,7,opt,name=IsNewRequest,proto3" json:"IsNewRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapPetBagItemData) Reset() {
	*x = SwapPetBagItemData{}
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapPetBagItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPetBagItemData) ProtoMessage() {}

func (x *SwapPetBagItemData) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPetBagItemData.ProtoReflect.Descriptor instead.
func (*SwapPetBagItemData) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP(), []int{1}
}

func (x *SwapPetBagItemData) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *SwapPetBagItemData) GetFromSlot() int64 {
	if x != nil {
		return x.FromSlot
	}
	return 0
}

func (x *SwapPetBagItemData) GetToSlot() int64 {
	if x != nil {
		return x.ToSlot
	}
	return 0
}

func (x *SwapPetBagItemData) GetFromItem() *SwapPetBagItemItem {
	if x != nil {
		return x.FromItem
	}
	return nil
}

func (x *SwapPetBagItemData) GetToItem() *SwapPetBagItemItem {
	if x != nil {
		return x.ToItem
	}
	return nil
}

func (x *SwapPetBagItemData) GetTakePercent() float64 {
	if x != nil {
		return x.TakePercent
	}
	return 0
}

func (x *SwapPetBagItemData) GetIsNewRequest() bool {
	if x != nil {
		return x.IsNewRequest
	}
	return false
}

// SwapPetBagItemItem 保存背包交换事件中的物品数据。
//
// SwapPetBagItemItem stores item data in a pet-bag swap event.
type SwapPetBagItemItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ItemName    string                 `protobuf:"bytes,1,opt,name=ItemName,proto3" json:"ItemName,omitempty"`
	NewItemName string                 `protobuf:"bytes,2,opt,name=NewItemName,proto3" json:"NewItemName,omitempty"`
	AuxValue    int64                  `protobuf:"varint,3,opt,name=AuxValue,proto3" json:"AuxValue,omitempty"`
	Count       int64                  `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	// Go type: map[string]SwapPetBagItemUser
	UserData    map[string]*SwapPetBagItemUser `protobuf:"bytes,5,rep,name=UserData,proto3" json:"UserData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Durability  int64                          `protobuf:"varint,6,opt,name=Durability,proto3" json:"Durability,omitempty"`
	EnchantData bool                           `protobuf:"varint,7,opt,name=EnchantData,proto3" json:"EnchantData,omitempty"`
	// Go type: []SwapPetBagItemEnchant
	ModEnchantData []*SwapPetBagItemEnchant `protobuf:"bytes,8,rep,name=ModEnchantData,proto3" json:"ModEnchantData,omitempty"`
	CustomTips     string                   `protobuf:"bytes,9,opt,name=CustomTips,proto3" json:"CustomTips,omitempty"`
	ExtraID        string                   `protobuf:"bytes,10,opt,name=ExtraID,proto3" json:"ExtraID,omitempty"`
	ItemShowName   string                   `protobuf:"bytes,11,opt,name=ItemShowName,proto3" json:"ItemShowName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwapPetBagItemItem) Reset() {
	*x = SwapPetBagItemItem{}
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapPetBagItemItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPetBagItemItem) ProtoMessage() {}

func (x *SwapPetBagItemItem) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPetBagItemItem.ProtoReflect.Descriptor instead.
func (*SwapPetBagItemItem) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP(), []int{2}
}

func (x *SwapPetBagItemItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SwapPetBagItemItem) GetNewItemName() string {
	if x != nil {
		return x.NewItemName
	}
	return ""
}

func (x *SwapPetBagItemItem) GetAuxValue() int64 {
	if x != nil {
		return x.AuxValue
	}
	return 0
}

func (x *SwapPetBagItemItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SwapPetBagItemItem) GetUserData() map[string]*SwapPetBagItemUser {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *SwapPetBagItemItem) GetDurability() int64 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *SwapPetBagItemItem) GetEnchantData() bool {
	if x != nil {
		return x.EnchantData
	}
	return false
}

func (x *SwapPetBagItemItem) GetModEnchantData() []*SwapPetBagItemEnchant {
	if x != nil {
		return x.ModEnchantData
	}
	return nil
}

func (x *SwapPetBagItemItem) GetCustomTips() string {
	if x != nil {
		return x.CustomTips
	}
	return ""
}

func (x *SwapPetBagItemItem) GetExtraID() string {
	if x != nil {
		return x.ExtraID
	}
	return ""
}

func (x *SwapPetBagItemItem) GetItemShowName() string {
	if x != nil {
		return x.ItemShowName
	}
	return ""
}

// SwapPetBagItemUser 保存背包交换物品 userData 的已知项。
//
// SwapPetBagItemUser stores known item userData entries in a pet-bag swap event.
type SwapPetBagItemUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=Mode,proto3" json:"Mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapPetBagItemUser) Reset() {
	*x = SwapPetBagItemUser{}
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapPetBagItemUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPetBagItemUser) ProtoMessage() {}

func (x *SwapPetBagItemUser) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPetBagItemUser.ProtoReflect.Descriptor instead.
func (*SwapPetBagItemUser) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP(), []int{3}
}

func (x *SwapPetBagItemUser) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// SwapPetBagItemEnchant 保存背包交换物品附魔项。
//
// SwapPetBagItemEnchant stores item enchantment entries in a pet-bag swap event.
type SwapPetBagItemEnchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Level         int64                  `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapPetBagItemEnchant) Reset() {
	*x = SwapPetBagItemEnchant{}
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapPetBagItemEnchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPetBagItemEnchant) ProtoMessage() {}

func (x *SwapPetBagItemEnchant) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPetBagItemEnchant.ProtoReflect.Descriptor instead.
func (*SwapPetBagItemEnchant) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP(), []int{4}
}

func (x *SwapPetBagItemEnchant) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SwapPetBagItemEnchant) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDesc = "" +
	"\n" +
	"6py_rpc/mod_event/minecraft/pet/swap_pet_bag_item.proto\x12Omousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item\x1a*py_rpc/mod_event/minecraft/pet/basic.proto\"\x88\x02\n" +
	"\x0eSwapPetBagItem\x12`\n" +
	"\x05Basic\x18\x01 \x01(\v2J.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.BasicR\x05Basic\x12\x93\x01\n" +
	"\x12SwapPetBagItemData\x18\x02 \x01(\v2c.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemDataR\x12SwapPetBagItemData\"\xa8\x03\n" +
	"\x12SwapPetBagItemData\x12\x1a\n" +
	"\bPlayerID\x18\x01 \x01(\tR\bPlayerID\x12\x1a\n" +
	"\bFromSlot\x18\x02 \x01(\x03R\bFromSlot\x12\x16\n" +
	"\x06ToSlot\x18\x03 \x01(\x03R\x06ToSlot\x12\x7f\n" +
	"\bFromItem\x18\x04 \x01(\v2c.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItemR\bFromItem\x12{\n" +
	"\x06ToItem\x18\x05 \x01(\v2c.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItemR\x06ToItem\x12 \n" +
	"\vTakePercent\x18\x06 \x01(\x01R\vTakePercent\x12\"\n" +
	"\fIsNewRequest\x18\a \x01(\bR\fIsNewRequest\"\xe8\x05\n" +
	"\x12SwapPetBagItemItem\x12\x1a\n" +
	"\bItemName\x18\x01 \x01(\tR\bItemName\x12 \n" +
	"\vNewItemName\x18\x02 \x01(\tR\vNewItemName\x12\x1a\n" +
	"\bAuxValue\x18\x03 \x01(\x03R\bAuxValue\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\x03R\x05Count\x12\x8d\x01\n" +
	"\bUserData\x18\x05 \x03(\v2q.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.UserDataEntryR\bUserData\x12\x1e\n" +
	"\n" +
	"Durability\x18\x06 \x01(\x03R\n" +
	"Durability\x12 \n" +
	"\vEnchantData\x18\a \x01(\bR\vEnchantData\x12\x8e\x01\n" +
	"\x0eModEnchantData\x18\b \x03(\v2f.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemEnchantR\x0eModEnchantData\x12\x1e\n" +
	"\n" +
	"CustomTips\x18\t \x01(\tR\n" +
	"CustomTips\x12\x18\n" +
	"\aExtraID\x18\n" +
	" \x01(\tR\aExtraID\x12\"\n" +
	"\fItemShowName\x18\v \x01(\tR\fItemShowName\x1a\xa0\x01\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12y\n" +
	"\x05value\x18\x02 \x01(\v2c.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemUserR\x05value:\x028\x01\"(\n" +
	"\x12SwapPetBagItemUser\x12\x12\n" +
	"\x04Mode\x18\x01 \x01(\tR\x04Mode\"=\n" +
	"\x15SwapPetBagItemEnchant\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Level\x18\x02 \x01(\x03R\x05LevelB_Z]github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/pet;petb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_goTypes = []any{
	(*SwapPetBagItem)(nil),        // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItem
	(*SwapPetBagItemData)(nil),    // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemData
	(*SwapPetBagItemItem)(nil),    // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem
	(*SwapPetBagItemUser)(nil),    // 3: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemUser
	(*SwapPetBagItemEnchant)(nil), // 4: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemEnchant
	nil,                           // 5: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.UserDataEntry
	(*Basic)(nil),                 // 6: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
}
var file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_depIdxs = []int32{
	6, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItem.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItem.SwapPetBagItemData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemData
	2, // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemData.FromItem:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem
	2, // 3: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemData.ToItem:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem
	5, // 4: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.UserData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.UserDataEntry
	4, // 5: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.ModEnchantData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemEnchant
	3, // 6: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemItem.UserDataEntry.value:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.swap_pet_bag_item.SwapPetBagItemUser
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_init() }
func file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_init() {
	if File_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_pet_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto = out.File
	file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_pet_swap_pet_bag_item_proto_depIdxs = nil
}
