// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/pet/teleport_pet.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TeleportPet 请求服务器传送宠物。
//
// TeleportPet asks the server to teleport a pet.
type TeleportPet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Basic           *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	TeleportPetData *TeleportPetData       `protobuf:"bytes,2,opt,name=TeleportPetData,proto3" json:"TeleportPetData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeleportPet) Reset() {
	*x = TeleportPet{}
	mi := &file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleportPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportPet) ProtoMessage() {}

func (x *TeleportPet) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportPet.ProtoReflect.Descriptor instead.
func (*TeleportPet) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescGZIP(), []int{0}
}

func (x *TeleportPet) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *TeleportPet) GetTeleportPetData() *TeleportPetData {
	if x != nil {
		return x.TeleportPetData
	}
	return nil
}

// TeleportPetData 保存宠物召唤请求和响应的公共字段。
//
// TeleportPetData stores common fields for pet summon requests and responses.
type TeleportPetData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PlayerID  string                 `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	SkinID    int64                  `protobuf:"varint,2,opt,name=SkinID,proto3" json:"SkinID,omitempty"`
	NameValue string                 `protobuf:"bytes,3,opt,name=NameValue,proto3" json:"NameValue,omitempty"`
	PetID     int64                  `protobuf:"varint,4,opt,name=PetID,proto3" json:"PetID,omitempty"`
	ModelName string                 `protobuf:"bytes,5,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	// Go type: *bool
	AllowStepOnBlock bool `protobuf:"varint,6,opt,name=AllowStepOnBlock,proto3" json:"AllowStepOnBlock,omitempty"`
	// Go type: *bool
	AvoidOwner bool   `protobuf:"varint,7,opt,name=AvoidOwner,proto3" json:"AvoidOwner,omitempty"`
	Silent     bool   `protobuf:"varint,8,opt,name=Silent,proto3" json:"Silent,omitempty"`
	Respawn    bool   `protobuf:"varint,9,opt,name=Respawn,proto3" json:"Respawn,omitempty"`
	EntityID   string `protobuf:"bytes,10,opt,name=EntityID,proto3" json:"EntityID,omitempty"`
	// Go type: *int64
	Code          int64 `protobuf:"varint,11,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeleportPetData) Reset() {
	*x = TeleportPetData{}
	mi := &file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleportPetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportPetData) ProtoMessage() {}

func (x *TeleportPetData) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportPetData.ProtoReflect.Descriptor instead.
func (*TeleportPetData) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescGZIP(), []int{1}
}

func (x *TeleportPetData) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *TeleportPetData) GetSkinID() int64 {
	if x != nil {
		return x.SkinID
	}
	return 0
}

func (x *TeleportPetData) GetNameValue() string {
	if x != nil {
		return x.NameValue
	}
	return ""
}

func (x *TeleportPetData) GetPetID() int64 {
	if x != nil {
		return x.PetID
	}
	return 0
}

func (x *TeleportPetData) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TeleportPetData) GetAllowStepOnBlock() bool {
	if x != nil {
		return x.AllowStepOnBlock
	}
	return false
}

func (x *TeleportPetData) GetAvoidOwner() bool {
	if x != nil {
		return x.AvoidOwner
	}
	return false
}

func (x *TeleportPetData) GetSilent() bool {
	if x != nil {
		return x.Silent
	}
	return false
}

func (x *TeleportPetData) GetRespawn() bool {
	if x != nil {
		return x.Respawn
	}
	return false
}

func (x *TeleportPetData) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *TeleportPetData) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_py_rpc_mod_event_minecraft_pet_teleport_pet_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDesc = "" +
	"\n" +
	"1py_rpc/mod_event/minecraft/pet/teleport_pet.proto\x12Jmousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet\x1a*py_rpc/mod_event/minecraft/pet/basic.proto\"\xf7\x01\n" +
	"\vTeleportPet\x12`\n" +
	"\x05Basic\x18\x01 \x01(\v2J.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.BasicR\x05Basic\x12\x85\x01\n" +
	"\x0fTeleportPetData\x18\x02 \x01(\v2[.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPetDataR\x0fTeleportPetData\"\xc5\x02\n" +
	"\x0fTeleportPetData\x12\x1a\n" +
	"\bPlayerID\x18\x01 \x01(\tR\bPlayerID\x12\x16\n" +
	"\x06SkinID\x18\x02 \x01(\x03R\x06SkinID\x12\x1c\n" +
	"\tNameValue\x18\x03 \x01(\tR\tNameValue\x12\x14\n" +
	"\x05PetID\x18\x04 \x01(\x03R\x05PetID\x12\x1c\n" +
	"\tModelName\x18\x05 \x01(\tR\tModelName\x12*\n" +
	"\x10AllowStepOnBlock\x18\x06 \x01(\bR\x10AllowStepOnBlock\x12\x1e\n" +
	"\n" +
	"AvoidOwner\x18\a \x01(\bR\n" +
	"AvoidOwner\x12\x16\n" +
	"\x06Silent\x18\b \x01(\bR\x06Silent\x12\x18\n" +
	"\aRespawn\x18\t \x01(\bR\aRespawn\x12\x1a\n" +
	"\bEntityID\x18\n" +
	" \x01(\tR\bEntityID\x12\x12\n" +
	"\x04Code\x18\v \x01(\x03R\x04CodeB_Z]github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/pet;petb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_goTypes = []any{
	(*TeleportPet)(nil),     // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPet
	(*TeleportPetData)(nil), // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPetData
	(*Basic)(nil),           // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
}
var file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPet.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPet.TeleportPetData:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.pet.teleport_pet.TeleportPetData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_init() }
func file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_init() {
	if File_py_rpc_mod_event_minecraft_pet_teleport_pet_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_pet_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_pet_teleport_pet_proto = out.File
	file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_pet_teleport_pet_proto_depIdxs = nil
}
