// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: game_control/resources_control/inventory.proto

package resources_control_pb

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SlotLocation 描述一个物品的所在的位置
type SlotLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowID 指示该物品所在的库存窗口 ID
	WindowID int32 `protobuf:"varint,1,opt,name=WindowID,proto3" json:"WindowID,omitempty"`
	// SlotID 指示该物品所在库存的槽位索引
	SlotID        uint32 `protobuf:"varint,2,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLocation) Reset() {
	*x = SlotLocation{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLocation) ProtoMessage() {}

func (x *SlotLocation) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLocation.ProtoReflect.Descriptor instead.
func (*SlotLocation) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *SlotLocation) GetWindowID() int32 {
	if x != nil {
		return x.WindowID
	}
	return 0
}

func (x *SlotLocation) GetSlotID() uint32 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

// GetInventoryRequest 是获取窗口 ID 为 windowID 的库存的请求。
type GetInventoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowID 是机器人已打开(或持有)的库存的窗口 ID
	WindowID      int32 `protobuf:"varint,1,opt,name=WindowID,proto3" json:"WindowID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryRequest) GetWindowID() int32 {
	if x != nil {
		return x.WindowID
	}
	return 0
}

// GetInventoryResponse 是窗口 ID 为 windowID 的库存。
type GetInventoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found 指示目标库存是否存在。
	Found bool `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	// Items 是当前库存的全部物品堆栈实例。
	Items         []*SlotItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetInventoryResponse) GetItems() []*SlotItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetItemStackRequest 是加载位于 windowID 的库存中索引为 slotID 的物品的请求。
type GetItemStackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowID 是机器人已打开(或持有)的库存的窗口 ID
	WindowID int32 `protobuf:"varint,1,opt,name=WindowID,proto3" json:"WindowID,omitempty"`
	// SlotID 是单个物品栏槽位的索引，它是从 0 开始索引的
	SlotID        uint32 `protobuf:"varint,2,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemStackRequest) Reset() {
	*x = GetItemStackRequest{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemStackRequest) ProtoMessage() {}

func (x *GetItemStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemStackRequest.ProtoReflect.Descriptor instead.
func (*GetItemStackRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemStackRequest) GetWindowID() int32 {
	if x != nil {
		return x.WindowID
	}
	return 0
}

func (x *GetItemStackRequest) GetSlotID() uint32 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

// GetItemStackResponse 是位于 windowID 的库存中索引为 slotID 的物品。
type GetItemStackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InventoryFound 指示目标库存是否存在。
	InventoryFound bool `protobuf:"varint,1,opt,name=InventoryFound,proto3" json:"InventoryFound,omitempty"`
	// ItemFound 表示目标槽位是否返回了物品。
	ItemFound bool `protobuf:"varint,2,opt,name=ItemFound,proto3" json:"ItemFound,omitempty"`
	// Item 是当前库存中物品栏编号为 slotID 的物品堆栈信息。
	// 如果不存在，确保返回一个新的空气物品的堆栈实例表示，而非空指针
	Item          *protocol.ItemInstance `protobuf:"bytes,3,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemStackResponse) Reset() {
	*x = GetItemStackResponse{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemStackResponse) ProtoMessage() {}

func (x *GetItemStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemStackResponse.ProtoReflect.Descriptor instead.
func (*GetItemStackResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemStackResponse) GetInventoryFound() bool {
	if x != nil {
		return x.InventoryFound
	}
	return false
}

func (x *GetItemStackResponse) GetItemFound() bool {
	if x != nil {
		return x.ItemFound
	}
	return false
}

func (x *GetItemStackResponse) GetItem() *protocol.ItemInstance {
	if x != nil {
		return x.Item
	}
	return nil
}

// GetAllItemStacksRequest 是列出窗口 ID 为 windowID 的库存中的所有物品堆栈实例的请求。
type GetAllItemStacksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowID 是机器人已打开(或持有)的库存的窗口 ID
	WindowID      int32 `protobuf:"varint,1,opt,name=WindowID,proto3" json:"WindowID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemStacksRequest) Reset() {
	*x = GetAllItemStacksRequest{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemStacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemStacksRequest) ProtoMessage() {}

func (x *GetAllItemStacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemStacksRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemStacksRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllItemStacksRequest) GetWindowID() int32 {
	if x != nil {
		return x.WindowID
	}
	return 0
}

// GetAllItemStacksResponse 是窗口 ID 为 windowID 的库存中的所有物品堆栈实例。
type GetAllItemStacksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InventoryFound 指示目标库存是否存在。
	InventoryFound bool `protobuf:"varint,1,opt,name=InventoryFound,proto3" json:"InventoryFound,omitempty"`
	// Items 是当前库存的全部物品堆栈实例。
	Items         []*SlotItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemStacksResponse) Reset() {
	*x = GetAllItemStacksResponse{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemStacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemStacksResponse) ProtoMessage() {}

func (x *GetAllItemStacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemStacksResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemStacksResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllItemStacksResponse) GetInventoryFound() bool {
	if x != nil {
		return x.InventoryFound
	}
	return false
}

func (x *GetAllItemStacksResponse) GetItems() []*SlotItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ListWindowIDsRequest 是列出当前所有库存的窗口 ID 的空请求。
type ListWindowIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWindowIDsRequest) Reset() {
	*x = ListWindowIDsRequest{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWindowIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWindowIDsRequest) ProtoMessage() {}

func (x *ListWindowIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWindowIDsRequest.ProtoReflect.Descriptor instead.
func (*ListWindowIDsRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{7}
}

// ListWindowIDsResponse 是当前所有库存的窗口 ID。
type ListWindowIDsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowIDs 是当前所有库存的窗口 ID。
	WindowIDs     []int32 `protobuf:"varint,1,rep,packed,name=WindowIDs,proto3" json:"WindowIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWindowIDsResponse) Reset() {
	*x = ListWindowIDsResponse{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWindowIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWindowIDsResponse) ProtoMessage() {}

func (x *ListWindowIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWindowIDsResponse.ProtoReflect.Descriptor instead.
func (*ListWindowIDsResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ListWindowIDsResponse) GetWindowIDs() []int32 {
	if x != nil {
		return x.WindowIDs
	}
	return nil
}

// SlotItem 描述当前库存中某个槽位的物品堆栈实例。
type SlotItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SlotID 是单个物品栏槽位的索引，它是从 0 开始索引的
	SlotID uint32 `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	// Item 是当前库存中物品栏编号为 slotID 的物品堆栈信息。
	Item          *protocol.ItemInstance `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotItem) Reset() {
	*x = SlotItem{}
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotItem) ProtoMessage() {}

func (x *SlotItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotItem.ProtoReflect.Descriptor instead.
func (*SlotItem) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *SlotItem) GetSlotID() uint32 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *SlotItem) GetItem() *protocol.ItemInstance {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_game_control_resources_control_inventory_proto protoreflect.FileDescriptor

const file_game_control_resources_control_inventory_proto_rawDesc = "" +
	"\n" +
	".game_control/resources_control/inventory.proto\x12'emptydea.game_control.resources_control\x1a\n" +
	"item.proto\"B\n" +
	"\fSlotLocation\x12\x1a\n" +
	"\bWindowID\x18\x01 \x01(\x05R\bWindowID\x12\x16\n" +
	"\x06SlotID\x18\x02 \x01(\rR\x06SlotID\"1\n" +
	"\x13GetInventoryRequest\x12\x1a\n" +
	"\bWindowID\x18\x01 \x01(\x05R\bWindowID\"u\n" +
	"\x14GetInventoryResponse\x12\x14\n" +
	"\x05Found\x18\x01 \x01(\bR\x05Found\x12G\n" +
	"\x05Items\x18\x02 \x03(\v21.emptydea.game_control.resources_control.SlotItemR\x05Items\"I\n" +
	"\x13GetItemStackRequest\x12\x1a\n" +
	"\bWindowID\x18\x01 \x01(\x05R\bWindowID\x12\x16\n" +
	"\x06SlotID\x18\x02 \x01(\rR\x06SlotID\"\xa3\x01\n" +
	"\x14GetItemStackResponse\x12&\n" +
	"\x0eInventoryFound\x18\x01 \x01(\bR\x0eInventoryFound\x12\x1c\n" +
	"\tItemFound\x18\x02 \x01(\bR\tItemFound\x12E\n" +
	"\x04Item\x18\x03 \x01(\v21.mousetunnel.minecraft.protocol.item.ItemInstanceR\x04Item\"5\n" +
	"\x17GetAllItemStacksRequest\x12\x1a\n" +
	"\bWindowID\x18\x01 \x01(\x05R\bWindowID\"\x8b\x01\n" +
	"\x18GetAllItemStacksResponse\x12&\n" +
	"\x0eInventoryFound\x18\x01 \x01(\bR\x0eInventoryFound\x12G\n" +
	"\x05Items\x18\x02 \x03(\v21.emptydea.game_control.resources_control.SlotItemR\x05Items\"\x16\n" +
	"\x14ListWindowIDsRequest\"5\n" +
	"\x15ListWindowIDsResponse\x12\x1c\n" +
	"\tWindowIDs\x18\x01 \x03(\x05R\tWindowIDs\"i\n" +
	"\bSlotItem\x12\x16\n" +
	"\x06SlotID\x18\x01 \x01(\rR\x06SlotID\x12E\n" +
	"\x04Item\x18\x02 \x01(\v21.mousetunnel.minecraft.protocol.item.ItemInstanceR\x04Item2\xd9\x04\n" +
	"\x10InventoryService\x12\x8b\x01\n" +
	"\fGetInventory\x12<.emptydea.game_control.resources_control.GetInventoryRequest\x1a=.emptydea.game_control.resources_control.GetInventoryResponse\x12\x8b\x01\n" +
	"\fGetItemStack\x12<.emptydea.game_control.resources_control.GetItemStackRequest\x1a=.emptydea.game_control.resources_control.GetItemStackResponse\x12\x97\x01\n" +
	"\x10GetAllItemStacks\x12@.emptydea.game_control.resources_control.GetAllItemStacksRequest\x1aA.emptydea.game_control.resources_control.GetAllItemStacksResponse\x12\x8e\x01\n" +
	"\rListWindowIDs\x12=.emptydea.game_control.resources_control.ListWindowIDsRequest\x1a>.emptydea.game_control.resources_control.ListWindowIDsResponseB]Z[github.com/EmptyDea-Team/EmptyDea-core-api/pb/game_control/resources_control;resources_control_pbb\x06proto3"

var (
	file_game_control_resources_control_inventory_proto_rawDescOnce sync.Once
	file_game_control_resources_control_inventory_proto_rawDescData []byte
)

func file_game_control_resources_control_inventory_proto_rawDescGZIP() []byte {
	file_game_control_resources_control_inventory_proto_rawDescOnce.Do(func() {
		file_game_control_resources_control_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_control_resources_control_inventory_proto_rawDesc), len(file_game_control_resources_control_inventory_proto_rawDesc)))
	})
	return file_game_control_resources_control_inventory_proto_rawDescData
}

var file_game_control_resources_control_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_control_resources_control_inventory_proto_goTypes = []any{
	(*SlotLocation)(nil),             // 0: emptydea.game_control.resources_control.SlotLocation
	(*GetInventoryRequest)(nil),      // 1: emptydea.game_control.resources_control.GetInventoryRequest
	(*GetInventoryResponse)(nil),     // 2: emptydea.game_control.resources_control.GetInventoryResponse
	(*GetItemStackRequest)(nil),      // 3: emptydea.game_control.resources_control.GetItemStackRequest
	(*GetItemStackResponse)(nil),     // 4: emptydea.game_control.resources_control.GetItemStackResponse
	(*GetAllItemStacksRequest)(nil),  // 5: emptydea.game_control.resources_control.GetAllItemStacksRequest
	(*GetAllItemStacksResponse)(nil), // 6: emptydea.game_control.resources_control.GetAllItemStacksResponse
	(*ListWindowIDsRequest)(nil),     // 7: emptydea.game_control.resources_control.ListWindowIDsRequest
	(*ListWindowIDsResponse)(nil),    // 8: emptydea.game_control.resources_control.ListWindowIDsResponse
	(*SlotItem)(nil),                 // 9: emptydea.game_control.resources_control.SlotItem
	(*protocol.ItemInstance)(nil),    // 10: mousetunnel.minecraft.protocol.item.ItemInstance
}
var file_game_control_resources_control_inventory_proto_depIdxs = []int32{
	9,  // 0: emptydea.game_control.resources_control.GetInventoryResponse.Items:type_name -> emptydea.game_control.resources_control.SlotItem
	10, // 1: emptydea.game_control.resources_control.GetItemStackResponse.Item:type_name -> mousetunnel.minecraft.protocol.item.ItemInstance
	9,  // 2: emptydea.game_control.resources_control.GetAllItemStacksResponse.Items:type_name -> emptydea.game_control.resources_control.SlotItem
	10, // 3: emptydea.game_control.resources_control.SlotItem.Item:type_name -> mousetunnel.minecraft.protocol.item.ItemInstance
	1,  // 4: emptydea.game_control.resources_control.InventoryService.GetInventory:input_type -> emptydea.game_control.resources_control.GetInventoryRequest
	3,  // 5: emptydea.game_control.resources_control.InventoryService.GetItemStack:input_type -> emptydea.game_control.resources_control.GetItemStackRequest
	5,  // 6: emptydea.game_control.resources_control.InventoryService.GetAllItemStacks:input_type -> emptydea.game_control.resources_control.GetAllItemStacksRequest
	7,  // 7: emptydea.game_control.resources_control.InventoryService.ListWindowIDs:input_type -> emptydea.game_control.resources_control.ListWindowIDsRequest
	2,  // 8: emptydea.game_control.resources_control.InventoryService.GetInventory:output_type -> emptydea.game_control.resources_control.GetInventoryResponse
	4,  // 9: emptydea.game_control.resources_control.InventoryService.GetItemStack:output_type -> emptydea.game_control.resources_control.GetItemStackResponse
	6,  // 10: emptydea.game_control.resources_control.InventoryService.GetAllItemStacks:output_type -> emptydea.game_control.resources_control.GetAllItemStacksResponse
	8,  // 11: emptydea.game_control.resources_control.InventoryService.ListWindowIDs:output_type -> emptydea.game_control.resources_control.ListWindowIDsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_game_control_resources_control_inventory_proto_init() }
func file_game_control_resources_control_inventory_proto_init() {
	if File_game_control_resources_control_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_control_resources_control_inventory_proto_rawDesc), len(file_game_control_resources_control_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_control_resources_control_inventory_proto_goTypes,
		DependencyIndexes: file_game_control_resources_control_inventory_proto_depIdxs,
		MessageInfos:      file_game_control_resources_control_inventory_proto_msgTypes,
	}.Build()
	File_game_control_resources_control_inventory_proto = out.File
	file_game_control_resources_control_inventory_proto_goTypes = nil
	file_game_control_resources_control_inventory_proto_depIdxs = nil
}
