// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: game_control/resources_control/inventory.proto

package resources_control_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_GetInventory_FullMethodName     = "/emptydea.game_control.resources_control.InventoryService/GetInventory"
	InventoryService_GetItemStack_FullMethodName     = "/emptydea.game_control.resources_control.InventoryService/GetItemStack"
	InventoryService_GetAllItemStacks_FullMethodName = "/emptydea.game_control.resources_control.InventoryService/GetAllItemStacks"
	InventoryService_ListWindowNames_FullMethodName  = "/emptydea.game_control.resources_control.InventoryService/ListWindowNames"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService 描述机器人已打开(或持有)的所有库存，
// 例如背包、副手、胸甲和动态容器。
type InventoryServiceClient interface {
	// GetInventory 返回窗口名为 WindowName 的库存。
	// 如果目标库存不存在，则返回的 existed 为假
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	// GetItemStack 加载位于 WindowName 的库存中索引为 slotID 的物品。
	// 如果目标库存不存在，则返回的 inventoryExisted 为假
	GetItemStack(ctx context.Context, in *GetItemStackRequest, opts ...grpc.CallOption) (*GetItemStackResponse, error)
	// GetAllItemStacks 列出窗口名为 WindowName 的库存中的所有物品堆栈实例
	GetAllItemStacks(ctx context.Context, in *GetAllItemStacksRequest, opts ...grpc.CallOption) (*GetAllItemStacksResponse, error)
	// ListWindowNames 列出当前所有库存的窗口名。
	ListWindowNames(ctx context.Context, in *ListWindowNamesRequest, opts ...grpc.CallOption) (*ListWindowNamesResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetItemStack(ctx context.Context, in *GetItemStackRequest, opts ...grpc.CallOption) (*GetItemStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemStackResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetItemStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetAllItemStacks(ctx context.Context, in *GetAllItemStacksRequest, opts ...grpc.CallOption) (*GetAllItemStacksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllItemStacksResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetAllItemStacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListWindowNames(ctx context.Context, in *ListWindowNamesRequest, opts ...grpc.CallOption) (*ListWindowNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWindowNamesResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListWindowNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// InventoryService 描述机器人已打开(或持有)的所有库存，
// 例如背包、副手、胸甲和动态容器。
type InventoryServiceServer interface {
	// GetInventory 返回窗口名为 WindowName 的库存。
	// 如果目标库存不存在，则返回的 existed 为假
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	// GetItemStack 加载位于 WindowName 的库存中索引为 slotID 的物品。
	// 如果目标库存不存在，则返回的 inventoryExisted 为假
	GetItemStack(context.Context, *GetItemStackRequest) (*GetItemStackResponse, error)
	// GetAllItemStacks 列出窗口名为 WindowName 的库存中的所有物品堆栈实例
	GetAllItemStacks(context.Context, *GetAllItemStacksRequest) (*GetAllItemStacksResponse, error)
	// ListWindowNames 列出当前所有库存的窗口名。
	ListWindowNames(context.Context, *ListWindowNamesRequest) (*ListWindowNamesResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedInventoryServiceServer) GetItemStack(context.Context, *GetItemStackRequest) (*GetItemStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemStack not implemented")
}
func (UnimplementedInventoryServiceServer) GetAllItemStacks(context.Context, *GetAllItemStacksRequest) (*GetAllItemStacksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItemStacks not implemented")
}
func (UnimplementedInventoryServiceServer) ListWindowNames(context.Context, *ListWindowNamesRequest) (*ListWindowNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWindowNames not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetItemStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetItemStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetItemStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetItemStack(ctx, req.(*GetItemStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetAllItemStacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllItemStacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetAllItemStacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetAllItemStacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetAllItemStacks(ctx, req.(*GetAllItemStacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListWindowNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWindowNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListWindowNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListWindowNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListWindowNames(ctx, req.(*ListWindowNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emptydea.game_control.resources_control.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _InventoryService_GetInventory_Handler,
		},
		{
			MethodName: "GetItemStack",
			Handler:    _InventoryService_GetItemStack_Handler,
		},
		{
			MethodName: "GetAllItemStacks",
			Handler:    _InventoryService_GetAllItemStacks_Handler,
		},
		{
			MethodName: "ListWindowNames",
			Handler:    _InventoryService_ListWindowNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_control/resources_control/inventory.proto",
}
