// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: game_control/resources_control/uqholder.proto

package resources_control_pb

import (
	game_control "github.com/EmptyDea-Team/EmptyDea-core-api/pb/game_control"
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	mgl32 "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/mgl32"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayerRef 是可跨 getter 使用的玩家引用。
type PlayerRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID 返回玩家 UUID 字符串。
	UUID          string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRef) Reset() {
	*x = PlayerRef{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRef) ProtoMessage() {}

func (x *PlayerRef) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRef.ProtoReflect.Descriptor instead.
func (*PlayerRef) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRef) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

// PlayerLookupResponse 是玩家索引查询结果。
type PlayerLookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found 表示是否找到玩家。
	Found bool `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	// Player 是找到的玩家引用。
	Player        *PlayerRef `protobuf:"bytes,2,opt,name=Player,proto3" json:"Player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLookupResponse) Reset() {
	*x = PlayerLookupResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLookupResponse) ProtoMessage() {}

func (x *PlayerLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLookupResponse.ProtoReflect.Descriptor instead.
func (*PlayerLookupResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PlayerLookupResponse) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

// PlayerRefsResponse 是当前在线玩家列表。
type PlayerRefsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Players 是当前在线玩家列表。
	Players       []*PlayerRef `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRefsResponse) Reset() {
	*x = PlayerRefsResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRefsResponse) ProtoMessage() {}

func (x *PlayerRefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRefsResponse.ProtoReflect.Descriptor instead.
func (*PlayerRefsResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerRefsResponse) GetPlayers() []*PlayerRef {
	if x != nil {
		return x.Players
	}
	return nil
}

// GetPlayerByUUIDRequest 是按 UUID 字符串查询玩家的请求。
type GetPlayerByUUIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID 是玩家 UUID 字符串。
	UUID          string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByUUIDRequest) Reset() {
	*x = GetPlayerByUUIDRequest{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByUUIDRequest) ProtoMessage() {}

func (x *GetPlayerByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerByUUIDRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

// GetPlayerByNameRequest 是按玩家名查询玩家的请求。
type GetPlayerByNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name 是玩家名。
	Name          string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByNameRequest) Reset() {
	*x = GetPlayerByNameRequest{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByNameRequest) ProtoMessage() {}

func (x *GetPlayerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByNameRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetPlayerByUniqueIDRequest 是按实体唯一 ID 查询玩家的请求。
type GetPlayerByUniqueIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UniqueID 是玩家实体唯一 ID。
	UniqueID      int64 `protobuf:"varint,1,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByUniqueIDRequest) Reset() {
	*x = GetPlayerByUniqueIDRequest{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByUniqueIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByUniqueIDRequest) ProtoMessage() {}

func (x *GetPlayerByUniqueIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByUniqueIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByUniqueIDRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerByUniqueIDRequest) GetUniqueID() int64 {
	if x != nil {
		return x.UniqueID
	}
	return 0
}

// GetPlayerByRuntimeIDRequest 是按实体运行时 ID 查询玩家的请求。
type GetPlayerByRuntimeIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuntimeID 是玩家实体运行时 ID。
	RuntimeID     uint64 `protobuf:"varint,1,opt,name=RuntimeID,proto3" json:"RuntimeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByRuntimeIDRequest) Reset() {
	*x = GetPlayerByRuntimeIDRequest{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByRuntimeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByRuntimeIDRequest) ProtoMessage() {}

func (x *GetPlayerByRuntimeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByRuntimeIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByRuntimeIDRequest) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlayerByRuntimeIDRequest) GetRuntimeID() uint64 {
	if x != nil {
		return x.RuntimeID
	}
	return 0
}

// EntityRef 是可跨 getter 使用的实体引用。
type EntityRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuntimeID 返回实体运行时 ID。
	RuntimeID     uint64 `protobuf:"varint,1,opt,name=RuntimeID,proto3" json:"RuntimeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{7}
}

func (x *EntityRef) GetRuntimeID() uint64 {
	if x != nil {
		return x.RuntimeID
	}
	return 0
}

// EntityLookupResponse 是实体索引查询结果。
type EntityLookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found 表示是否找到实体。
	Found bool `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	// Entity 是找到的实体引用。
	Entity        *EntityRef `protobuf:"bytes,2,opt,name=Entity,proto3" json:"Entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityLookupResponse) Reset() {
	*x = EntityLookupResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityLookupResponse) ProtoMessage() {}

func (x *EntityLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityLookupResponse.ProtoReflect.Descriptor instead.
func (*EntityLookupResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{8}
}

func (x *EntityLookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *EntityLookupResponse) GetEntity() *EntityRef {
	if x != nil {
		return x.Entity
	}
	return nil
}

// GameRuleKey 是单条游戏规则的名称。
type GameRuleKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name 是游戏规则名称。
	Name          string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRuleKey) Reset() {
	*x = GameRuleKey{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRuleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRuleKey) ProtoMessage() {}

func (x *GameRuleKey) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRuleKey.ProtoReflect.Descriptor instead.
func (*GameRuleKey) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{9}
}

func (x *GameRuleKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GameRuleNamesResponse 是游戏规则状态视图中的名称列表。
type GameRuleNamesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names 是游戏规则状态视图中的名称列表。
	Names         []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRuleNamesResponse) Reset() {
	*x = GameRuleNamesResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRuleNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRuleNamesResponse) ProtoMessage() {}

func (x *GameRuleNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRuleNamesResponse.ProtoReflect.Descriptor instead.
func (*GameRuleNamesResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{10}
}

func (x *GameRuleNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// MobEffectRef 是实体身上的单个药水效果状态引用。
type MobEffectRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuntimeID 返回实体运行时 ID。
	RuntimeID uint64 `protobuf:"varint,1,opt,name=RuntimeID,proto3" json:"RuntimeID,omitempty"`
	// EffectType 返回药水效果类型。
	EffectType    int32 `protobuf:"varint,2,opt,name=EffectType,proto3" json:"EffectType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobEffectRef) Reset() {
	*x = MobEffectRef{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobEffectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobEffectRef) ProtoMessage() {}

func (x *MobEffectRef) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobEffectRef.ProtoReflect.Descriptor instead.
func (*MobEffectRef) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{11}
}

func (x *MobEffectRef) GetRuntimeID() uint64 {
	if x != nil {
		return x.RuntimeID
	}
	return 0
}

func (x *MobEffectRef) GetEffectType() int32 {
	if x != nil {
		return x.EffectType
	}
	return 0
}

// MobEffectTypesResponse 是实体药水效果类型查询结果。
type MobEffectTypesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found 表示是否找到实体或效果集合。
	Found bool `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	// EffectTypes 是实体身上已维护的药水效果类型列表。
	EffectTypes   []int32 `protobuf:"varint,2,rep,packed,name=EffectTypes,proto3" json:"EffectTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobEffectTypesResponse) Reset() {
	*x = MobEffectTypesResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobEffectTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobEffectTypesResponse) ProtoMessage() {}

func (x *MobEffectTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobEffectTypesResponse.ProtoReflect.Descriptor instead.
func (*MobEffectTypesResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{12}
}

func (x *MobEffectTypesResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *MobEffectTypesResponse) GetEffectTypes() []int32 {
	if x != nil {
		return x.EffectTypes
	}
	return nil
}

// BoolResponse 是非可选 bool 返回值。
type BoolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value 是实际 bool 结果。
	Value         bool `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{13}
}

func (x *BoolResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// Vec3Value 表示可能不存在的三维向量值。
type Vec3Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ok 表示 Value 是否存在且有效。
	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	// Value 是当前位置。
	Value         *mgl32.Vec3 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3Value) Reset() {
	*x = Vec3Value{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3Value) ProtoMessage() {}

func (x *Vec3Value) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3Value.ProtoReflect.Descriptor instead.
func (*Vec3Value) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{14}
}

func (x *Vec3Value) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Vec3Value) GetValue() *mgl32.Vec3 {
	if x != nil {
		return x.Value
	}
	return nil
}

// EntityMetadataValue 表示可能不存在的实体元数据。
type EntityMetadataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ok 表示 Value 是否存在且有效。
	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	// Value 是实体元数据。
	Value         *protocol.EntityMetadata `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMetadataValue) Reset() {
	*x = EntityMetadataValue{}
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMetadataValue) ProtoMessage() {}

func (x *EntityMetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_resources_control_uqholder_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMetadataValue.ProtoReflect.Descriptor instead.
func (*EntityMetadataValue) Descriptor() ([]byte, []int) {
	return file_game_control_resources_control_uqholder_proto_rawDescGZIP(), []int{15}
}

func (x *EntityMetadataValue) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EntityMetadataValue) GetValue() *protocol.EntityMetadata {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_game_control_resources_control_uqholder_proto protoreflect.FileDescriptor

const file_game_control_resources_control_uqholder_proto_rawDesc = "" +
	"\n" +
	"-game_control/resources_control/uqholder.proto\x12'emptydea.game_control.resources_control\x1a\x19game_control/common.proto\x1a\x15entity_metadata.proto\x1a\vmgl32.proto\"\x1f\n" +
	"\tPlayerRef\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"x\n" +
	"\x14PlayerLookupResponse\x12\x14\n" +
	"\x05Found\x18\x01 \x01(\bR\x05Found\x12J\n" +
	"\x06Player\x18\x02 \x01(\v22.emptydea.game_control.resources_control.PlayerRefR\x06Player\"b\n" +
	"\x12PlayerRefsResponse\x12L\n" +
	"\aPlayers\x18\x01 \x03(\v22.emptydea.game_control.resources_control.PlayerRefR\aPlayers\",\n" +
	"\x16GetPlayerByUUIDRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\",\n" +
	"\x16GetPlayerByNameRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"8\n" +
	"\x1aGetPlayerByUniqueIDRequest\x12\x1a\n" +
	"\bUniqueID\x18\x01 \x01(\x03R\bUniqueID\";\n" +
	"\x1bGetPlayerByRuntimeIDRequest\x12\x1c\n" +
	"\tRuntimeID\x18\x01 \x01(\x04R\tRuntimeID\")\n" +
	"\tEntityRef\x12\x1c\n" +
	"\tRuntimeID\x18\x01 \x01(\x04R\tRuntimeID\"x\n" +
	"\x14EntityLookupResponse\x12\x14\n" +
	"\x05Found\x18\x01 \x01(\bR\x05Found\x12J\n" +
	"\x06Entity\x18\x02 \x01(\v22.emptydea.game_control.resources_control.EntityRefR\x06Entity\"!\n" +
	"\vGameRuleKey\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"-\n" +
	"\x15GameRuleNamesResponse\x12\x14\n" +
	"\x05Names\x18\x01 \x03(\tR\x05Names\"L\n" +
	"\fMobEffectRef\x12\x1c\n" +
	"\tRuntimeID\x18\x01 \x01(\x04R\tRuntimeID\x12\x1e\n" +
	"\n" +
	"EffectType\x18\x02 \x01(\x05R\n" +
	"EffectType\"P\n" +
	"\x16MobEffectTypesResponse\x12\x14\n" +
	"\x05Found\x18\x01 \x01(\bR\x05Found\x12 \n" +
	"\vEffectTypes\x18\x02 \x03(\x05R\vEffectTypes\"$\n" +
	"\fBoolResponse\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\bR\x05Value\"]\n" +
	"\tVec3Value\x12\x0e\n" +
	"\x02Ok\x18\x01 \x01(\bR\x02Ok\x12@\n" +
	"\x05Value\x18\x02 \x01(\v2*.mousetunnel.minecraft.protocol.mgl32.Vec3R\x05Value\"{\n" +
	"\x13EntityMetadataValue\x12\x0e\n" +
	"\x02Ok\x18\x01 \x01(\bR\x02Ok\x12T\n" +
	"\x05Value\x18\x02 \x01(\v2>.mousetunnel.minecraft.protocol.entity_metadata.EntityMetadataR\x05Value2\xaeB\n" +
	"\bUQHolder\x12N\n" +
	"\n" +
	"GetBotName\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.StringValue\x12N\n" +
	"\n" +
	"GetBotXUID\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.StringValue\x12N\n" +
	"\n" +
	"GetBotUUID\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.StringValue\x12W\n" +
	"\x14GetBotEntityUniqueID\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int64Value\x12Y\n" +
	"\x15GetBotEntityRuntimeID\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.Uint64Value\x12b\n" +
	"\x0eGetBotPosition\x12\x1c.emptydea.game_control.Empty\x1a2.emptydea.game_control.resources_control.Vec3Value\x12R\n" +
	"\x0fGetBotDimension\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int32Value\x12Q\n" +
	"\x0eGetBotGameMode\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int32Value\x12Q\n" +
	"\fGetBotHealth\x12\x1c.emptydea.game_control.Empty\x1a#.emptydea.game_control.Float32Value\x12Q\n" +
	"\fGetBotHunger\x12\x1c.emptydea.game_control.Empty\x1a#.emptydea.game_control.Float32Value\x12U\n" +
	"\x10GetBotSaturation\x12\x1c.emptydea.game_control.Empty\x1a#.emptydea.game_control.Float32Value\x12T\n" +
	"\x10GetBotHotBarSlot\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.Uint32Value\x12m\n" +
	"\x10GetOnlinePlayers\x12\x1c.emptydea.game_control.Empty\x1a;.emptydea.game_control.resources_control.PlayerRefsResponse\x12\x91\x01\n" +
	"\x0fGetPlayerByUUID\x12?.emptydea.game_control.resources_control.GetPlayerByUUIDRequest\x1a=.emptydea.game_control.resources_control.PlayerLookupResponse\x12\x91\x01\n" +
	"\x0fGetPlayerByName\x12?.emptydea.game_control.resources_control.GetPlayerByNameRequest\x1a=.emptydea.game_control.resources_control.PlayerLookupResponse\x12\x99\x01\n" +
	"\x13GetPlayerByUniqueID\x12C.emptydea.game_control.resources_control.GetPlayerByUniqueIDRequest\x1a=.emptydea.game_control.resources_control.PlayerLookupResponse\x12\x9b\x01\n" +
	"\x14GetPlayerByRuntimeID\x12D.emptydea.game_control.resources_control.GetPlayerByRuntimeIDRequest\x1a=.emptydea.game_control.resources_control.PlayerLookupResponse\x12g\n" +
	"\rGetPlayerUUID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12g\n" +
	"\rGetPlayerName\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12g\n" +
	"\rGetPlayerXUID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12p\n" +
	"\x17GetPlayerEntityUniqueID\x122.emptydea.game_control.resources_control.PlayerRef\x1a!.emptydea.game_control.Int64Value\x12r\n" +
	"\x18GetPlayerEntityRuntimeID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint64Value\x12l\n" +
	"\x13GetPlayerNeteaseUID\x122.emptydea.game_control.resources_control.PlayerRef\x1a!.emptydea.game_control.Int64Value\x12j\n" +
	"\x12GetPlayerLoginTime\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.TimeValue\x12q\n" +
	"\x17GetPlayerPlatformChatID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12o\n" +
	"\x16GetPlayerBuildPlatform\x122.emptydea.game_control.resources_control.PlayerRef\x1a!.emptydea.game_control.Int32Value\x12i\n" +
	"\x0fGetPlayerSkinID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12k\n" +
	"\x11GetPlayerDeviceID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.StringValue\x12\x8b\x01\n" +
	"\x17GetPlayerEntityMetadata\x122.emptydea.game_control.resources_control.PlayerRef\x1a<.emptydea.game_control.resources_control.EntityMetadataValue\x12{\n" +
	"\x11GetPlayerPosition\x122.emptydea.game_control.resources_control.PlayerRef\x1a2.emptydea.game_control.resources_control.Vec3Value\x12i\n" +
	"\x0eGetPlayerPitch\x122.emptydea.game_control.resources_control.PlayerRef\x1a#.emptydea.game_control.Float32Value\x12g\n" +
	"\fGetPlayerYaw\x122.emptydea.game_control.resources_control.PlayerRef\x1a#.emptydea.game_control.Float32Value\x12k\n" +
	"\x10GetPlayerHeadYaw\x122.emptydea.game_control.resources_control.PlayerRef\x1a#.emptydea.game_control.Float32Value\x12k\n" +
	"\x11GetPlayerMoveMode\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint32Value\x12i\n" +
	"\x11GetPlayerOnGround\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12x\n" +
	"\x1eGetPlayerRiddenEntityRuntimeID\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint64Value\x12g\n" +
	"\rGetPlayerTick\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint64Value\x12g\n" +
	"\x0fGetPlayerOnline\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12u\n" +
	"\x1bGetPlayerCommandPermissions\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint32Value\x12n\n" +
	"\x14GetPlayerPermissions\x122.emptydea.game_control.resources_control.PlayerRef\x1a\".emptydea.game_control.Uint32Value\x12l\n" +
	"\x11GetPlayerFlySpeed\x122.emptydea.game_control.resources_control.PlayerRef\x1a#.emptydea.game_control.Float32Value\x12m\n" +
	"\x12GetPlayerWalkSpeed\x122.emptydea.game_control.resources_control.PlayerRef\x1a#.emptydea.game_control.Float32Value\x12i\n" +
	"\x11GetPlayerCanBuild\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12h\n" +
	"\x10GetPlayerCanMine\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12w\n" +
	"\x1fGetPlayerCanUseDoorsAndSwitches\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12r\n" +
	"\x1aGetPlayerCanOpenContainers\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12q\n" +
	"\x19GetPlayerCanAttackPlayers\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12n\n" +
	"\x16GetPlayerCanAttackMobs\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12w\n" +
	"\x1fGetPlayerCanUseOperatorCommands\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12l\n" +
	"\x14GetPlayerCanTeleport\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12o\n" +
	"\x17GetPlayerIsInvulnerable\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12i\n" +
	"\x11GetPlayerIsFlying\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12g\n" +
	"\x0fGetPlayerCanFly\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12p\n" +
	"\x18GetPlayerCanInstantBuild\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12p\n" +
	"\x18GetPlayerCanUseLightning\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12h\n" +
	"\x10GetPlayerIsMuted\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12o\n" +
	"\x17GetPlayerIsWorldBuilder\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12j\n" +
	"\x12GetPlayerHasNoClip\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12t\n" +
	"\x1cGetPlayerIsPrivilegedBuilder\x122.emptydea.game_control.resources_control.PlayerRef\x1a .emptydea.game_control.BoolValue\x12V\n" +
	"\x13GetWorldCurrentTick\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int64Value\x12V\n" +
	"\x11GetWorldSyncRatio\x12\x1c.emptydea.game_control.Empty\x1a#.emptydea.game_control.Float32Value\x12O\n" +
	"\fGetWorldTime\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int32Value\x12R\n" +
	"\x0fGetWorldDayTime\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int32Value\x12[\n" +
	"\x16GetWorldDayTimePercent\x12\x1c.emptydea.game_control.Empty\x1a#.emptydea.game_control.Float32Value\x12V\n" +
	"\x12GetWorldDifficulty\x12\x1c.emptydea.game_control.Empty\x1a\".emptydea.game_control.Uint32Value\x12S\n" +
	"\x10GetWorldGameMode\x12\x1c.emptydea.game_control.Empty\x1a!.emptydea.game_control.Int32Value\x12p\n" +
	"\x10GetGameRuleNames\x12\x1c.emptydea.game_control.Empty\x1a>.emptydea.game_control.resources_control.GameRuleNamesResponse\x12z\n" +
	" GetGameRuleCanBeModifiedByPlayer\x124.emptydea.game_control.resources_control.GameRuleKey\x1a .emptydea.game_control.BoolValue\x12l\n" +
	"\x10GetGameRuleValue\x124.emptydea.game_control.resources_control.GameRuleKey\x1a\".emptydea.game_control.StringValue\x12\x89\x01\n" +
	"\x14GetEntityByRuntimeID\x122.emptydea.game_control.resources_control.EntityRef\x1a=.emptydea.game_control.resources_control.EntityLookupResponse\x12l\n" +
	"\x12GetEntityRuntimeID\x122.emptydea.game_control.resources_control.EntityRef\x1a\".emptydea.game_control.Uint64Value\x12j\n" +
	"\x11GetEntityUniqueID\x122.emptydea.game_control.resources_control.EntityRef\x1a!.emptydea.game_control.Int64Value\x12j\n" +
	"\x0fGetEntityHealth\x122.emptydea.game_control.resources_control.EntityRef\x1a#.emptydea.game_control.Float32Value\x12\x8b\x01\n" +
	"\x14GetEntityEffectTypes\x122.emptydea.game_control.resources_control.EntityRef\x1a?.emptydea.game_control.resources_control.MobEffectTypesResponse\x12t\n" +
	"\x18GetEntityEffectAmplifier\x125.emptydea.game_control.resources_control.MobEffectRef\x1a!.emptydea.game_control.Int32Value\x12s\n" +
	"\x17GetEntityEffectDuration\x125.emptydea.game_control.resources_control.MobEffectRef\x1a!.emptydea.game_control.Int32Value\x12s\n" +
	"\x18GetEntityEffectParticles\x125.emptydea.game_control.resources_control.MobEffectRef\x1a .emptydea.game_control.BoolValue\x12w\n" +
	"\x1aGetEntityEffectUpdatedTick\x125.emptydea.game_control.resources_control.MobEffectRef\x1a\".emptydea.game_control.Uint64ValueB]Z[github.com/EmptyDea-Team/EmptyDea-core-api/pb/game_control/resources_control;resources_control_pbb\x06proto3"

var (
	file_game_control_resources_control_uqholder_proto_rawDescOnce sync.Once
	file_game_control_resources_control_uqholder_proto_rawDescData []byte
)

func file_game_control_resources_control_uqholder_proto_rawDescGZIP() []byte {
	file_game_control_resources_control_uqholder_proto_rawDescOnce.Do(func() {
		file_game_control_resources_control_uqholder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_control_resources_control_uqholder_proto_rawDesc), len(file_game_control_resources_control_uqholder_proto_rawDesc)))
	})
	return file_game_control_resources_control_uqholder_proto_rawDescData
}

var file_game_control_resources_control_uqholder_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_game_control_resources_control_uqholder_proto_goTypes = []any{
	(*PlayerRef)(nil),                   // 0: emptydea.game_control.resources_control.PlayerRef
	(*PlayerLookupResponse)(nil),        // 1: emptydea.game_control.resources_control.PlayerLookupResponse
	(*PlayerRefsResponse)(nil),          // 2: emptydea.game_control.resources_control.PlayerRefsResponse
	(*GetPlayerByUUIDRequest)(nil),      // 3: emptydea.game_control.resources_control.GetPlayerByUUIDRequest
	(*GetPlayerByNameRequest)(nil),      // 4: emptydea.game_control.resources_control.GetPlayerByNameRequest
	(*GetPlayerByUniqueIDRequest)(nil),  // 5: emptydea.game_control.resources_control.GetPlayerByUniqueIDRequest
	(*GetPlayerByRuntimeIDRequest)(nil), // 6: emptydea.game_control.resources_control.GetPlayerByRuntimeIDRequest
	(*EntityRef)(nil),                   // 7: emptydea.game_control.resources_control.EntityRef
	(*EntityLookupResponse)(nil),        // 8: emptydea.game_control.resources_control.EntityLookupResponse
	(*GameRuleKey)(nil),                 // 9: emptydea.game_control.resources_control.GameRuleKey
	(*GameRuleNamesResponse)(nil),       // 10: emptydea.game_control.resources_control.GameRuleNamesResponse
	(*MobEffectRef)(nil),                // 11: emptydea.game_control.resources_control.MobEffectRef
	(*MobEffectTypesResponse)(nil),      // 12: emptydea.game_control.resources_control.MobEffectTypesResponse
	(*BoolResponse)(nil),                // 13: emptydea.game_control.resources_control.BoolResponse
	(*Vec3Value)(nil),                   // 14: emptydea.game_control.resources_control.Vec3Value
	(*EntityMetadataValue)(nil),         // 15: emptydea.game_control.resources_control.EntityMetadataValue
	(*mgl32.Vec3)(nil),                  // 16: mousetunnel.minecraft.protocol.mgl32.Vec3
	(*protocol.EntityMetadata)(nil),     // 17: mousetunnel.minecraft.protocol.entity_metadata.EntityMetadata
	(*game_control.Empty)(nil),          // 18: emptydea.game_control.Empty
	(*game_control.StringValue)(nil),    // 19: emptydea.game_control.StringValue
	(*game_control.Int64Value)(nil),     // 20: emptydea.game_control.Int64Value
	(*game_control.Uint64Value)(nil),    // 21: emptydea.game_control.Uint64Value
	(*game_control.Int32Value)(nil),     // 22: emptydea.game_control.Int32Value
	(*game_control.Float32Value)(nil),   // 23: emptydea.game_control.Float32Value
	(*game_control.Uint32Value)(nil),    // 24: emptydea.game_control.Uint32Value
	(*game_control.TimeValue)(nil),      // 25: emptydea.game_control.TimeValue
	(*game_control.BoolValue)(nil),      // 26: emptydea.game_control.BoolValue
}
var file_game_control_resources_control_uqholder_proto_depIdxs = []int32{
	0,  // 0: emptydea.game_control.resources_control.PlayerLookupResponse.Player:type_name -> emptydea.game_control.resources_control.PlayerRef
	0,  // 1: emptydea.game_control.resources_control.PlayerRefsResponse.Players:type_name -> emptydea.game_control.resources_control.PlayerRef
	7,  // 2: emptydea.game_control.resources_control.EntityLookupResponse.Entity:type_name -> emptydea.game_control.resources_control.EntityRef
	16, // 3: emptydea.game_control.resources_control.Vec3Value.Value:type_name -> mousetunnel.minecraft.protocol.mgl32.Vec3
	17, // 4: emptydea.game_control.resources_control.EntityMetadataValue.Value:type_name -> mousetunnel.minecraft.protocol.entity_metadata.EntityMetadata
	18, // 5: emptydea.game_control.resources_control.UQHolder.GetBotName:input_type -> emptydea.game_control.Empty
	18, // 6: emptydea.game_control.resources_control.UQHolder.GetBotXUID:input_type -> emptydea.game_control.Empty
	18, // 7: emptydea.game_control.resources_control.UQHolder.GetBotUUID:input_type -> emptydea.game_control.Empty
	18, // 8: emptydea.game_control.resources_control.UQHolder.GetBotEntityUniqueID:input_type -> emptydea.game_control.Empty
	18, // 9: emptydea.game_control.resources_control.UQHolder.GetBotEntityRuntimeID:input_type -> emptydea.game_control.Empty
	18, // 10: emptydea.game_control.resources_control.UQHolder.GetBotPosition:input_type -> emptydea.game_control.Empty
	18, // 11: emptydea.game_control.resources_control.UQHolder.GetBotDimension:input_type -> emptydea.game_control.Empty
	18, // 12: emptydea.game_control.resources_control.UQHolder.GetBotGameMode:input_type -> emptydea.game_control.Empty
	18, // 13: emptydea.game_control.resources_control.UQHolder.GetBotHealth:input_type -> emptydea.game_control.Empty
	18, // 14: emptydea.game_control.resources_control.UQHolder.GetBotHunger:input_type -> emptydea.game_control.Empty
	18, // 15: emptydea.game_control.resources_control.UQHolder.GetBotSaturation:input_type -> emptydea.game_control.Empty
	18, // 16: emptydea.game_control.resources_control.UQHolder.GetBotHotBarSlot:input_type -> emptydea.game_control.Empty
	18, // 17: emptydea.game_control.resources_control.UQHolder.GetOnlinePlayers:input_type -> emptydea.game_control.Empty
	3,  // 18: emptydea.game_control.resources_control.UQHolder.GetPlayerByUUID:input_type -> emptydea.game_control.resources_control.GetPlayerByUUIDRequest
	4,  // 19: emptydea.game_control.resources_control.UQHolder.GetPlayerByName:input_type -> emptydea.game_control.resources_control.GetPlayerByNameRequest
	5,  // 20: emptydea.game_control.resources_control.UQHolder.GetPlayerByUniqueID:input_type -> emptydea.game_control.resources_control.GetPlayerByUniqueIDRequest
	6,  // 21: emptydea.game_control.resources_control.UQHolder.GetPlayerByRuntimeID:input_type -> emptydea.game_control.resources_control.GetPlayerByRuntimeIDRequest
	0,  // 22: emptydea.game_control.resources_control.UQHolder.GetPlayerUUID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 23: emptydea.game_control.resources_control.UQHolder.GetPlayerName:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 24: emptydea.game_control.resources_control.UQHolder.GetPlayerXUID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 25: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityUniqueID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 26: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityRuntimeID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 27: emptydea.game_control.resources_control.UQHolder.GetPlayerNeteaseUID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 28: emptydea.game_control.resources_control.UQHolder.GetPlayerLoginTime:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 29: emptydea.game_control.resources_control.UQHolder.GetPlayerPlatformChatID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 30: emptydea.game_control.resources_control.UQHolder.GetPlayerBuildPlatform:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 31: emptydea.game_control.resources_control.UQHolder.GetPlayerSkinID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 32: emptydea.game_control.resources_control.UQHolder.GetPlayerDeviceID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 33: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityMetadata:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 34: emptydea.game_control.resources_control.UQHolder.GetPlayerPosition:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 35: emptydea.game_control.resources_control.UQHolder.GetPlayerPitch:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 36: emptydea.game_control.resources_control.UQHolder.GetPlayerYaw:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 37: emptydea.game_control.resources_control.UQHolder.GetPlayerHeadYaw:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 38: emptydea.game_control.resources_control.UQHolder.GetPlayerMoveMode:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 39: emptydea.game_control.resources_control.UQHolder.GetPlayerOnGround:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 40: emptydea.game_control.resources_control.UQHolder.GetPlayerRiddenEntityRuntimeID:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 41: emptydea.game_control.resources_control.UQHolder.GetPlayerTick:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 42: emptydea.game_control.resources_control.UQHolder.GetPlayerOnline:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 43: emptydea.game_control.resources_control.UQHolder.GetPlayerCommandPermissions:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 44: emptydea.game_control.resources_control.UQHolder.GetPlayerPermissions:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 45: emptydea.game_control.resources_control.UQHolder.GetPlayerFlySpeed:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 46: emptydea.game_control.resources_control.UQHolder.GetPlayerWalkSpeed:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 47: emptydea.game_control.resources_control.UQHolder.GetPlayerCanBuild:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 48: emptydea.game_control.resources_control.UQHolder.GetPlayerCanMine:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 49: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseDoorsAndSwitches:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 50: emptydea.game_control.resources_control.UQHolder.GetPlayerCanOpenContainers:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 51: emptydea.game_control.resources_control.UQHolder.GetPlayerCanAttackPlayers:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 52: emptydea.game_control.resources_control.UQHolder.GetPlayerCanAttackMobs:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 53: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseOperatorCommands:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 54: emptydea.game_control.resources_control.UQHolder.GetPlayerCanTeleport:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 55: emptydea.game_control.resources_control.UQHolder.GetPlayerIsInvulnerable:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 56: emptydea.game_control.resources_control.UQHolder.GetPlayerIsFlying:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 57: emptydea.game_control.resources_control.UQHolder.GetPlayerCanFly:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 58: emptydea.game_control.resources_control.UQHolder.GetPlayerCanInstantBuild:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 59: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseLightning:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 60: emptydea.game_control.resources_control.UQHolder.GetPlayerIsMuted:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 61: emptydea.game_control.resources_control.UQHolder.GetPlayerIsWorldBuilder:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 62: emptydea.game_control.resources_control.UQHolder.GetPlayerHasNoClip:input_type -> emptydea.game_control.resources_control.PlayerRef
	0,  // 63: emptydea.game_control.resources_control.UQHolder.GetPlayerIsPrivilegedBuilder:input_type -> emptydea.game_control.resources_control.PlayerRef
	18, // 64: emptydea.game_control.resources_control.UQHolder.GetWorldCurrentTick:input_type -> emptydea.game_control.Empty
	18, // 65: emptydea.game_control.resources_control.UQHolder.GetWorldSyncRatio:input_type -> emptydea.game_control.Empty
	18, // 66: emptydea.game_control.resources_control.UQHolder.GetWorldTime:input_type -> emptydea.game_control.Empty
	18, // 67: emptydea.game_control.resources_control.UQHolder.GetWorldDayTime:input_type -> emptydea.game_control.Empty
	18, // 68: emptydea.game_control.resources_control.UQHolder.GetWorldDayTimePercent:input_type -> emptydea.game_control.Empty
	18, // 69: emptydea.game_control.resources_control.UQHolder.GetWorldDifficulty:input_type -> emptydea.game_control.Empty
	18, // 70: emptydea.game_control.resources_control.UQHolder.GetWorldGameMode:input_type -> emptydea.game_control.Empty
	18, // 71: emptydea.game_control.resources_control.UQHolder.GetGameRuleNames:input_type -> emptydea.game_control.Empty
	9,  // 72: emptydea.game_control.resources_control.UQHolder.GetGameRuleCanBeModifiedByPlayer:input_type -> emptydea.game_control.resources_control.GameRuleKey
	9,  // 73: emptydea.game_control.resources_control.UQHolder.GetGameRuleValue:input_type -> emptydea.game_control.resources_control.GameRuleKey
	7,  // 74: emptydea.game_control.resources_control.UQHolder.GetEntityByRuntimeID:input_type -> emptydea.game_control.resources_control.EntityRef
	7,  // 75: emptydea.game_control.resources_control.UQHolder.GetEntityRuntimeID:input_type -> emptydea.game_control.resources_control.EntityRef
	7,  // 76: emptydea.game_control.resources_control.UQHolder.GetEntityUniqueID:input_type -> emptydea.game_control.resources_control.EntityRef
	7,  // 77: emptydea.game_control.resources_control.UQHolder.GetEntityHealth:input_type -> emptydea.game_control.resources_control.EntityRef
	7,  // 78: emptydea.game_control.resources_control.UQHolder.GetEntityEffectTypes:input_type -> emptydea.game_control.resources_control.EntityRef
	11, // 79: emptydea.game_control.resources_control.UQHolder.GetEntityEffectAmplifier:input_type -> emptydea.game_control.resources_control.MobEffectRef
	11, // 80: emptydea.game_control.resources_control.UQHolder.GetEntityEffectDuration:input_type -> emptydea.game_control.resources_control.MobEffectRef
	11, // 81: emptydea.game_control.resources_control.UQHolder.GetEntityEffectParticles:input_type -> emptydea.game_control.resources_control.MobEffectRef
	11, // 82: emptydea.game_control.resources_control.UQHolder.GetEntityEffectUpdatedTick:input_type -> emptydea.game_control.resources_control.MobEffectRef
	19, // 83: emptydea.game_control.resources_control.UQHolder.GetBotName:output_type -> emptydea.game_control.StringValue
	19, // 84: emptydea.game_control.resources_control.UQHolder.GetBotXUID:output_type -> emptydea.game_control.StringValue
	19, // 85: emptydea.game_control.resources_control.UQHolder.GetBotUUID:output_type -> emptydea.game_control.StringValue
	20, // 86: emptydea.game_control.resources_control.UQHolder.GetBotEntityUniqueID:output_type -> emptydea.game_control.Int64Value
	21, // 87: emptydea.game_control.resources_control.UQHolder.GetBotEntityRuntimeID:output_type -> emptydea.game_control.Uint64Value
	14, // 88: emptydea.game_control.resources_control.UQHolder.GetBotPosition:output_type -> emptydea.game_control.resources_control.Vec3Value
	22, // 89: emptydea.game_control.resources_control.UQHolder.GetBotDimension:output_type -> emptydea.game_control.Int32Value
	22, // 90: emptydea.game_control.resources_control.UQHolder.GetBotGameMode:output_type -> emptydea.game_control.Int32Value
	23, // 91: emptydea.game_control.resources_control.UQHolder.GetBotHealth:output_type -> emptydea.game_control.Float32Value
	23, // 92: emptydea.game_control.resources_control.UQHolder.GetBotHunger:output_type -> emptydea.game_control.Float32Value
	23, // 93: emptydea.game_control.resources_control.UQHolder.GetBotSaturation:output_type -> emptydea.game_control.Float32Value
	24, // 94: emptydea.game_control.resources_control.UQHolder.GetBotHotBarSlot:output_type -> emptydea.game_control.Uint32Value
	2,  // 95: emptydea.game_control.resources_control.UQHolder.GetOnlinePlayers:output_type -> emptydea.game_control.resources_control.PlayerRefsResponse
	1,  // 96: emptydea.game_control.resources_control.UQHolder.GetPlayerByUUID:output_type -> emptydea.game_control.resources_control.PlayerLookupResponse
	1,  // 97: emptydea.game_control.resources_control.UQHolder.GetPlayerByName:output_type -> emptydea.game_control.resources_control.PlayerLookupResponse
	1,  // 98: emptydea.game_control.resources_control.UQHolder.GetPlayerByUniqueID:output_type -> emptydea.game_control.resources_control.PlayerLookupResponse
	1,  // 99: emptydea.game_control.resources_control.UQHolder.GetPlayerByRuntimeID:output_type -> emptydea.game_control.resources_control.PlayerLookupResponse
	19, // 100: emptydea.game_control.resources_control.UQHolder.GetPlayerUUID:output_type -> emptydea.game_control.StringValue
	19, // 101: emptydea.game_control.resources_control.UQHolder.GetPlayerName:output_type -> emptydea.game_control.StringValue
	19, // 102: emptydea.game_control.resources_control.UQHolder.GetPlayerXUID:output_type -> emptydea.game_control.StringValue
	20, // 103: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityUniqueID:output_type -> emptydea.game_control.Int64Value
	21, // 104: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityRuntimeID:output_type -> emptydea.game_control.Uint64Value
	20, // 105: emptydea.game_control.resources_control.UQHolder.GetPlayerNeteaseUID:output_type -> emptydea.game_control.Int64Value
	25, // 106: emptydea.game_control.resources_control.UQHolder.GetPlayerLoginTime:output_type -> emptydea.game_control.TimeValue
	19, // 107: emptydea.game_control.resources_control.UQHolder.GetPlayerPlatformChatID:output_type -> emptydea.game_control.StringValue
	22, // 108: emptydea.game_control.resources_control.UQHolder.GetPlayerBuildPlatform:output_type -> emptydea.game_control.Int32Value
	19, // 109: emptydea.game_control.resources_control.UQHolder.GetPlayerSkinID:output_type -> emptydea.game_control.StringValue
	19, // 110: emptydea.game_control.resources_control.UQHolder.GetPlayerDeviceID:output_type -> emptydea.game_control.StringValue
	15, // 111: emptydea.game_control.resources_control.UQHolder.GetPlayerEntityMetadata:output_type -> emptydea.game_control.resources_control.EntityMetadataValue
	14, // 112: emptydea.game_control.resources_control.UQHolder.GetPlayerPosition:output_type -> emptydea.game_control.resources_control.Vec3Value
	23, // 113: emptydea.game_control.resources_control.UQHolder.GetPlayerPitch:output_type -> emptydea.game_control.Float32Value
	23, // 114: emptydea.game_control.resources_control.UQHolder.GetPlayerYaw:output_type -> emptydea.game_control.Float32Value
	23, // 115: emptydea.game_control.resources_control.UQHolder.GetPlayerHeadYaw:output_type -> emptydea.game_control.Float32Value
	24, // 116: emptydea.game_control.resources_control.UQHolder.GetPlayerMoveMode:output_type -> emptydea.game_control.Uint32Value
	26, // 117: emptydea.game_control.resources_control.UQHolder.GetPlayerOnGround:output_type -> emptydea.game_control.BoolValue
	21, // 118: emptydea.game_control.resources_control.UQHolder.GetPlayerRiddenEntityRuntimeID:output_type -> emptydea.game_control.Uint64Value
	21, // 119: emptydea.game_control.resources_control.UQHolder.GetPlayerTick:output_type -> emptydea.game_control.Uint64Value
	26, // 120: emptydea.game_control.resources_control.UQHolder.GetPlayerOnline:output_type -> emptydea.game_control.BoolValue
	24, // 121: emptydea.game_control.resources_control.UQHolder.GetPlayerCommandPermissions:output_type -> emptydea.game_control.Uint32Value
	24, // 122: emptydea.game_control.resources_control.UQHolder.GetPlayerPermissions:output_type -> emptydea.game_control.Uint32Value
	23, // 123: emptydea.game_control.resources_control.UQHolder.GetPlayerFlySpeed:output_type -> emptydea.game_control.Float32Value
	23, // 124: emptydea.game_control.resources_control.UQHolder.GetPlayerWalkSpeed:output_type -> emptydea.game_control.Float32Value
	26, // 125: emptydea.game_control.resources_control.UQHolder.GetPlayerCanBuild:output_type -> emptydea.game_control.BoolValue
	26, // 126: emptydea.game_control.resources_control.UQHolder.GetPlayerCanMine:output_type -> emptydea.game_control.BoolValue
	26, // 127: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseDoorsAndSwitches:output_type -> emptydea.game_control.BoolValue
	26, // 128: emptydea.game_control.resources_control.UQHolder.GetPlayerCanOpenContainers:output_type -> emptydea.game_control.BoolValue
	26, // 129: emptydea.game_control.resources_control.UQHolder.GetPlayerCanAttackPlayers:output_type -> emptydea.game_control.BoolValue
	26, // 130: emptydea.game_control.resources_control.UQHolder.GetPlayerCanAttackMobs:output_type -> emptydea.game_control.BoolValue
	26, // 131: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseOperatorCommands:output_type -> emptydea.game_control.BoolValue
	26, // 132: emptydea.game_control.resources_control.UQHolder.GetPlayerCanTeleport:output_type -> emptydea.game_control.BoolValue
	26, // 133: emptydea.game_control.resources_control.UQHolder.GetPlayerIsInvulnerable:output_type -> emptydea.game_control.BoolValue
	26, // 134: emptydea.game_control.resources_control.UQHolder.GetPlayerIsFlying:output_type -> emptydea.game_control.BoolValue
	26, // 135: emptydea.game_control.resources_control.UQHolder.GetPlayerCanFly:output_type -> emptydea.game_control.BoolValue
	26, // 136: emptydea.game_control.resources_control.UQHolder.GetPlayerCanInstantBuild:output_type -> emptydea.game_control.BoolValue
	26, // 137: emptydea.game_control.resources_control.UQHolder.GetPlayerCanUseLightning:output_type -> emptydea.game_control.BoolValue
	26, // 138: emptydea.game_control.resources_control.UQHolder.GetPlayerIsMuted:output_type -> emptydea.game_control.BoolValue
	26, // 139: emptydea.game_control.resources_control.UQHolder.GetPlayerIsWorldBuilder:output_type -> emptydea.game_control.BoolValue
	26, // 140: emptydea.game_control.resources_control.UQHolder.GetPlayerHasNoClip:output_type -> emptydea.game_control.BoolValue
	26, // 141: emptydea.game_control.resources_control.UQHolder.GetPlayerIsPrivilegedBuilder:output_type -> emptydea.game_control.BoolValue
	20, // 142: emptydea.game_control.resources_control.UQHolder.GetWorldCurrentTick:output_type -> emptydea.game_control.Int64Value
	23, // 143: emptydea.game_control.resources_control.UQHolder.GetWorldSyncRatio:output_type -> emptydea.game_control.Float32Value
	22, // 144: emptydea.game_control.resources_control.UQHolder.GetWorldTime:output_type -> emptydea.game_control.Int32Value
	22, // 145: emptydea.game_control.resources_control.UQHolder.GetWorldDayTime:output_type -> emptydea.game_control.Int32Value
	23, // 146: emptydea.game_control.resources_control.UQHolder.GetWorldDayTimePercent:output_type -> emptydea.game_control.Float32Value
	24, // 147: emptydea.game_control.resources_control.UQHolder.GetWorldDifficulty:output_type -> emptydea.game_control.Uint32Value
	22, // 148: emptydea.game_control.resources_control.UQHolder.GetWorldGameMode:output_type -> emptydea.game_control.Int32Value
	10, // 149: emptydea.game_control.resources_control.UQHolder.GetGameRuleNames:output_type -> emptydea.game_control.resources_control.GameRuleNamesResponse
	26, // 150: emptydea.game_control.resources_control.UQHolder.GetGameRuleCanBeModifiedByPlayer:output_type -> emptydea.game_control.BoolValue
	19, // 151: emptydea.game_control.resources_control.UQHolder.GetGameRuleValue:output_type -> emptydea.game_control.StringValue
	8,  // 152: emptydea.game_control.resources_control.UQHolder.GetEntityByRuntimeID:output_type -> emptydea.game_control.resources_control.EntityLookupResponse
	21, // 153: emptydea.game_control.resources_control.UQHolder.GetEntityRuntimeID:output_type -> emptydea.game_control.Uint64Value
	20, // 154: emptydea.game_control.resources_control.UQHolder.GetEntityUniqueID:output_type -> emptydea.game_control.Int64Value
	23, // 155: emptydea.game_control.resources_control.UQHolder.GetEntityHealth:output_type -> emptydea.game_control.Float32Value
	12, // 156: emptydea.game_control.resources_control.UQHolder.GetEntityEffectTypes:output_type -> emptydea.game_control.resources_control.MobEffectTypesResponse
	22, // 157: emptydea.game_control.resources_control.UQHolder.GetEntityEffectAmplifier:output_type -> emptydea.game_control.Int32Value
	22, // 158: emptydea.game_control.resources_control.UQHolder.GetEntityEffectDuration:output_type -> emptydea.game_control.Int32Value
	26, // 159: emptydea.game_control.resources_control.UQHolder.GetEntityEffectParticles:output_type -> emptydea.game_control.BoolValue
	21, // 160: emptydea.game_control.resources_control.UQHolder.GetEntityEffectUpdatedTick:output_type -> emptydea.game_control.Uint64Value
	83, // [83:161] is the sub-list for method output_type
	5,  // [5:83] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_game_control_resources_control_uqholder_proto_init() }
func file_game_control_resources_control_uqholder_proto_init() {
	if File_game_control_resources_control_uqholder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_control_resources_control_uqholder_proto_rawDesc), len(file_game_control_resources_control_uqholder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_control_resources_control_uqholder_proto_goTypes,
		DependencyIndexes: file_game_control_resources_control_uqholder_proto_depIdxs,
		MessageInfos:      file_game_control_resources_control_uqholder_proto_msgTypes,
	}.Build()
	File_game_control_resources_control_uqholder_proto = out.File
	file_game_control_resources_control_uqholder_proto_goTypes = nil
	file_game_control_resources_control_uqholder_proto_depIdxs = nil
}
