// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/chat_extension/player_exit_room.proto

package chat_extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayerExitRoom 在玩家离开房间时同步退出玩家信息。
//
// PlayerExitRoom synchronises leaving player information when a player exits the room.
type PlayerExitRoom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	// UID 保存离开房间的网易 UID 列表。
	//
	// UID stores the list of NetEase UIDs that left the room.
	// Go type: []NetEaseUserUID
	UID []*NetEaseUserUID `protobuf:"bytes,2,rep,name=UID,proto3" json:"UID,omitempty"`
	// ExitPlayerID 是退出房间的玩家运行时 ID。
	//
	// ExitPlayerID is the runtime ID of the player that left the room.
	ExitPlayerID  *RuntimeID `protobuf:"bytes,3,opt,name=ExitPlayerID,proto3" json:"ExitPlayerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerExitRoom) Reset() {
	*x = PlayerExitRoom{}
	mi := &file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerExitRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExitRoom) ProtoMessage() {}

func (x *PlayerExitRoom) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExitRoom.ProtoReflect.Descriptor instead.
func (*PlayerExitRoom) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerExitRoom) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *PlayerExitRoom) GetUID() []*NetEaseUserUID {
	if x != nil {
		return x.UID
	}
	return nil
}

func (x *PlayerExitRoom) GetExitPlayerID() *RuntimeID {
	if x != nil {
		return x.ExitPlayerID
	}
	return nil
}

var File_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDesc = "" +
	"\n" +
	"@py_rpc/mod_event/minecraft/chat_extension/player_exit_room.proto\x12Ymousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_exit_room\x1a5py_rpc/mod_event/minecraft/chat_extension/basic.proto\x1a?py_rpc/mod_event/minecraft/chat_extension/player_add_room.proto\"\x83\x03\n" +
	"\x0ePlayerExitRoom\x12k\n" +
	"\x05Basic\x18\x01 \x01(\v2U.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.BasicR\x05Basic\x12z\n" +
	"\x03UID\x18\x02 \x03(\v2h.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.NetEaseUserUIDR\x03UID\x12\x87\x01\n" +
	"\fExitPlayerID\x18\x03 \x01(\v2c.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.RuntimeIDR\fExitPlayerIDBuZsgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/chat_extension;chat_extensionb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_goTypes = []any{
	(*PlayerExitRoom)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_exit_room.PlayerExitRoom
	(*Basic)(nil),          // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.Basic
	(*NetEaseUserUID)(nil), // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.NetEaseUserUID
	(*RuntimeID)(nil),      // 3: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.RuntimeID
}
var file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_exit_room.PlayerExitRoom.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.Basic
	2, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_exit_room.PlayerExitRoom.UID:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.NetEaseUserUID
	3, // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_exit_room.PlayerExitRoom.ExitPlayerID:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.player_add_room.RuntimeID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_init() }
func file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_init() {
	if File_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_chat_extension_basic_proto_init()
	file_py_rpc_mod_event_minecraft_chat_extension_player_add_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto = out.File
	file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_chat_extension_player_exit_room_proto_depIdxs = nil
}
