// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/chat_extension/sync_player_dimension_id_changed.proto

package chat_extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncPlayerDimensionIDChanged 同步玩家运行时 ID 到维度 ID 的变化。
//
// SyncPlayerDimensionIDChanged synchronises runtime ID to dimension ID changes.
type SyncPlayerDimensionIDChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	// DimID 保存运行时 ID 到维度 ID 的映射。
	//
	// DimID stores the mapping from runtime ID to dimension ID.
	// Go type: map[RuntimeID]int64
	DimID         map[string]int64 `protobuf:"bytes,2,rep,name=DimID,proto3" json:"DimID,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPlayerDimensionIDChanged) Reset() {
	*x = SyncPlayerDimensionIDChanged{}
	mi := &file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPlayerDimensionIDChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPlayerDimensionIDChanged) ProtoMessage() {}

func (x *SyncPlayerDimensionIDChanged) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPlayerDimensionIDChanged.ProtoReflect.Descriptor instead.
func (*SyncPlayerDimensionIDChanged) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescGZIP(), []int{0}
}

func (x *SyncPlayerDimensionIDChanged) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *SyncPlayerDimensionIDChanged) GetDimID() map[string]int64 {
	if x != nil {
		return x.DimID
	}
	return nil
}

var File_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDesc = "" +
	"\n" +
	"Ppy_rpc/mod_event/minecraft/chat_extension/sync_player_dimension_id_changed.proto\x12imousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed\x1a5py_rpc/mod_event/minecraft/chat_extension/basic.proto\x1a?py_rpc/mod_event/minecraft/chat_extension/player_add_room.proto\"\xf1\x02\n" +
	"\x1cSyncPlayerDimensionIDChanged\x12k\n" +
	"\x05Basic\x18\x01 \x01(\v2U.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.BasicR\x05Basic\x12\xa9\x01\n" +
	"\x05DimID\x18\x02 \x03(\v2\x92\x01.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged.DimIDEntryR\x05DimID\x1a8\n" +
	"\n" +
	"DimIDEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B{Zygithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/chat_extension;chat_extensionb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_goTypes = []any{
	(*SyncPlayerDimensionIDChanged)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged
	nil,                                  // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged.DimIDEntry
	(*Basic)(nil),                        // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.Basic
}
var file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged.DimID:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_extension.sync_player_dimension_id_changed.SyncPlayerDimensionIDChanged.DimIDEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_init()
}
func file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_init() {
	if File_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_chat_extension_basic_proto_init()
	file_py_rpc_mod_event_minecraft_chat_extension_player_add_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto = out.File
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_chat_extension_sync_player_dimension_id_changed_proto_depIdxs = nil
}
