// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: game_control/game_interface/item_copy.proto

package game_interface_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemInfo 是物品的信息
type ItemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 物品的数量
	Count uint32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	// 物品的类型
	ItemType      uint32 `protobuf:"varint,2,opt,name=ItemType,proto3" json:"ItemType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_game_control_game_interface_item_copy_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInfo) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemInfo) GetItemType() uint32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

// ItemInfoWithSlot 是具有物品栏槽位的 ItemInfo
type ItemInfoWithSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 该物品位于哪个槽位
	Slot uint32 `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	// 该物品的信息
	Item          *ItemInfo `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfoWithSlot) Reset() {
	*x = ItemInfoWithSlot{}
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfoWithSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfoWithSlot) ProtoMessage() {}

func (x *ItemInfoWithSlot) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfoWithSlot.ProtoReflect.Descriptor instead.
func (*ItemInfoWithSlot) Descriptor() ([]byte, []int) {
	return file_game_control_game_interface_item_copy_proto_rawDescGZIP(), []int{1}
}

func (x *ItemInfoWithSlot) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ItemInfoWithSlot) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

// CopyItemRequest 是批量复制物品的请求。
type CopyItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ContainerInfo 是目标容器或操作方块上下文。
	ContainerInfo *UseItemOnBlocks `protobuf:"bytes,1,opt,name=ContainerInfo,proto3" json:"ContainerInfo,omitempty"`
	// BaseItems 是作为复制来源的基础物品槽位列表。
	BaseItems []*ItemInfoWithSlot `protobuf:"bytes,2,rep,name=BaseItems,proto3" json:"BaseItems,omitempty"`
	// TargetItems 是目标槽位期望写入的物品列表。
	//
	// targetItems 的长度应该与目标容器的格子数量相等，并且空气物品应当
	// 置为 nil。
	TargetItems   []*ItemInfo `protobuf:"bytes,3,rep,name=TargetItems,proto3" json:"TargetItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyItemRequest) Reset() {
	*x = CopyItemRequest{}
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyItemRequest) ProtoMessage() {}

func (x *CopyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyItemRequest.ProtoReflect.Descriptor instead.
func (*CopyItemRequest) Descriptor() ([]byte, []int) {
	return file_game_control_game_interface_item_copy_proto_rawDescGZIP(), []int{2}
}

func (x *CopyItemRequest) GetContainerInfo() *UseItemOnBlocks {
	if x != nil {
		return x.ContainerInfo
	}
	return nil
}

func (x *CopyItemRequest) GetBaseItems() []*ItemInfoWithSlot {
	if x != nil {
		return x.BaseItems
	}
	return nil
}

func (x *CopyItemRequest) GetTargetItems() []*ItemInfo {
	if x != nil {
		return x.TargetItems
	}
	return nil
}

// CopyItemResponse 是复制物品后的空响应。
type CopyItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyItemResponse) Reset() {
	*x = CopyItemResponse{}
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyItemResponse) ProtoMessage() {}

func (x *CopyItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_control_game_interface_item_copy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyItemResponse.ProtoReflect.Descriptor instead.
func (*CopyItemResponse) Descriptor() ([]byte, []int) {
	return file_game_control_game_interface_item_copy_proto_rawDescGZIP(), []int{3}
}

var File_game_control_game_interface_item_copy_proto protoreflect.FileDescriptor

const file_game_control_game_interface_item_copy_proto_rawDesc = "" +
	"\n" +
	"+game_control/game_interface/item_copy.proto\x12$emptydea.game_control.game_interface\x1a+game_control/game_interface/bot_click.proto\"<\n" +
	"\bItemInfo\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\rR\x05Count\x12\x1a\n" +
	"\bItemType\x18\x02 \x01(\rR\bItemType\"j\n" +
	"\x10ItemInfoWithSlot\x12\x12\n" +
	"\x04Slot\x18\x01 \x01(\rR\x04Slot\x12B\n" +
	"\x04Item\x18\x02 \x01(\v2..emptydea.game_control.game_interface.ItemInfoR\x04Item\"\x96\x02\n" +
	"\x0fCopyItemRequest\x12[\n" +
	"\rContainerInfo\x18\x01 \x01(\v25.emptydea.game_control.game_interface.UseItemOnBlocksR\rContainerInfo\x12T\n" +
	"\tBaseItems\x18\x02 \x03(\v26.emptydea.game_control.game_interface.ItemInfoWithSlotR\tBaseItems\x12P\n" +
	"\vTargetItems\x18\x03 \x03(\v2..emptydea.game_control.game_interface.ItemInfoR\vTargetItems\"\x12\n" +
	"\x10CopyItemResponse2\x8c\x01\n" +
	"\x0fItemCopyService\x12y\n" +
	"\bCopyItem\x125.emptydea.game_control.game_interface.CopyItemRequest\x1a6.emptydea.game_control.game_interface.CopyItemResponseBWZUgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/game_control/game_interface;game_interface_pbb\x06proto3"

var (
	file_game_control_game_interface_item_copy_proto_rawDescOnce sync.Once
	file_game_control_game_interface_item_copy_proto_rawDescData []byte
)

func file_game_control_game_interface_item_copy_proto_rawDescGZIP() []byte {
	file_game_control_game_interface_item_copy_proto_rawDescOnce.Do(func() {
		file_game_control_game_interface_item_copy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_control_game_interface_item_copy_proto_rawDesc), len(file_game_control_game_interface_item_copy_proto_rawDesc)))
	})
	return file_game_control_game_interface_item_copy_proto_rawDescData
}

var file_game_control_game_interface_item_copy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_control_game_interface_item_copy_proto_goTypes = []any{
	(*ItemInfo)(nil),         // 0: emptydea.game_control.game_interface.ItemInfo
	(*ItemInfoWithSlot)(nil), // 1: emptydea.game_control.game_interface.ItemInfoWithSlot
	(*CopyItemRequest)(nil),  // 2: emptydea.game_control.game_interface.CopyItemRequest
	(*CopyItemResponse)(nil), // 3: emptydea.game_control.game_interface.CopyItemResponse
	(*UseItemOnBlocks)(nil),  // 4: emptydea.game_control.game_interface.UseItemOnBlocks
}
var file_game_control_game_interface_item_copy_proto_depIdxs = []int32{
	0, // 0: emptydea.game_control.game_interface.ItemInfoWithSlot.Item:type_name -> emptydea.game_control.game_interface.ItemInfo
	4, // 1: emptydea.game_control.game_interface.CopyItemRequest.ContainerInfo:type_name -> emptydea.game_control.game_interface.UseItemOnBlocks
	1, // 2: emptydea.game_control.game_interface.CopyItemRequest.BaseItems:type_name -> emptydea.game_control.game_interface.ItemInfoWithSlot
	0, // 3: emptydea.game_control.game_interface.CopyItemRequest.TargetItems:type_name -> emptydea.game_control.game_interface.ItemInfo
	2, // 4: emptydea.game_control.game_interface.ItemCopyService.CopyItem:input_type -> emptydea.game_control.game_interface.CopyItemRequest
	3, // 5: emptydea.game_control.game_interface.ItemCopyService.CopyItem:output_type -> emptydea.game_control.game_interface.CopyItemResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_control_game_interface_item_copy_proto_init() }
func file_game_control_game_interface_item_copy_proto_init() {
	if File_game_control_game_interface_item_copy_proto != nil {
		return
	}
	file_game_control_game_interface_bot_click_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_control_game_interface_item_copy_proto_rawDesc), len(file_game_control_game_interface_item_copy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_control_game_interface_item_copy_proto_goTypes,
		DependencyIndexes: file_game_control_game_interface_item_copy_proto_depIdxs,
		MessageInfos:      file_game_control_game_interface_item_copy_proto_msgTypes,
	}.Build()
	File_game_control_game_interface_item_copy_proto = out.File
	file_game_control_game_interface_item_copy_proto_goTypes = nil
	file_game_control_game_interface_item_copy_proto_depIdxs = nil
}
