// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/get_mcp_check_num.proto

package py_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMCPCheckNum 是网易登录流程中的 MCP check-number 挑战请求。
//
// GetMCPCheckNum is one of the NetEase login challenges.
type GetMCPCheckNum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MCPHex 是服务器发送的动态 MCP 字节码十六进制字符串。
	//
	// MCPHex is the hexadecimal dynamic MCP bytecode string sent by the server.
	MCPHex string `protobuf:"bytes,1,opt,name=MCPHex,proto3" json:"MCPHex,omitempty"`
	// Challenge 保存嵌套的 check-number 挑战参数。
	//
	// Challenge stores the nested check-number challenge arguments.
	Challenge     *GetMCPCheckNumChallenge `protobuf:"bytes,2,opt,name=Challenge,proto3" json:"Challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMCPCheckNum) Reset() {
	*x = GetMCPCheckNum{}
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMCPCheckNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMCPCheckNum) ProtoMessage() {}

func (x *GetMCPCheckNum) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMCPCheckNum.ProtoReflect.Descriptor instead.
func (*GetMCPCheckNum) Descriptor() ([]byte, []int) {
	return file_py_rpc_get_mcp_check_num_proto_rawDescGZIP(), []int{0}
}

func (x *GetMCPCheckNum) GetMCPHex() string {
	if x != nil {
		return x.MCPHex
	}
	return ""
}

func (x *GetMCPCheckNum) GetChallenge() *GetMCPCheckNumChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// GetMCPCheckNumChallenge 保存 GetMCPCheckNum 的嵌套挑战参数。
//
// GetMCPCheckNumChallenge stores the nested GetMCPCheckNum challenge arguments.
type GetMCPCheckNumChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value 是参与 MCP check-number 计算的挑战值。
	//
	// Value is the challenge value used for the MCP check-number calculation.
	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	// FirstExtraData 是挑战索引 1 的保留扩展数据列表。
	//
	// FirstExtraData is the reserved extension data list at challenge index 1.
	FirstExtraData *MCPCheckChallengeExtraData `protobuf:"bytes,2,opt,name=FirstExtraData,proto3" json:"FirstExtraData,omitempty"`
	// SecondExtraData 是挑战索引 2 的保留扩展数据列表。
	//
	// SecondExtraData is the reserved extension data list at challenge index 2.
	SecondExtraData *MCPCheckChallengeExtraData `protobuf:"bytes,3,opt,name=SecondExtraData,proto3" json:"SecondExtraData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMCPCheckNumChallenge) Reset() {
	*x = GetMCPCheckNumChallenge{}
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMCPCheckNumChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMCPCheckNumChallenge) ProtoMessage() {}

func (x *GetMCPCheckNumChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMCPCheckNumChallenge.ProtoReflect.Descriptor instead.
func (*GetMCPCheckNumChallenge) Descriptor() ([]byte, []int) {
	return file_py_rpc_get_mcp_check_num_proto_rawDescGZIP(), []int{1}
}

func (x *GetMCPCheckNumChallenge) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetMCPCheckNumChallenge) GetFirstExtraData() *MCPCheckChallengeExtraData {
	if x != nil {
		return x.FirstExtraData
	}
	return nil
}

func (x *GetMCPCheckNumChallenge) GetSecondExtraData() *MCPCheckChallengeExtraData {
	if x != nil {
		return x.SecondExtraData
	}
	return nil
}

// MCPCheckChallengeExtraData 是 MCP 校验请求中的保留扩展列表。
//
// MCPCheckChallengeExtraData is the reserved extension list in an MCP check
// challenge.
type MCPCheckChallengeExtraData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Go type: []string
	Value         []string `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCheckChallengeExtraData) Reset() {
	*x = MCPCheckChallengeExtraData{}
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCheckChallengeExtraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCheckChallengeExtraData) ProtoMessage() {}

func (x *MCPCheckChallengeExtraData) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_get_mcp_check_num_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCheckChallengeExtraData.ProtoReflect.Descriptor instead.
func (*MCPCheckChallengeExtraData) Descriptor() ([]byte, []int) {
	return file_py_rpc_get_mcp_check_num_proto_rawDescGZIP(), []int{2}
}

func (x *MCPCheckChallengeExtraData) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_py_rpc_get_mcp_check_num_proto protoreflect.FileDescriptor

const file_py_rpc_get_mcp_check_num_proto_rawDesc = "" +
	"\n" +
	"\x1epy_rpc/get_mcp_check_num.proto\x127mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num\"\x98\x01\n" +
	"\x0eGetMCPCheckNum\x12\x16\n" +
	"\x06MCPHex\x18\x01 \x01(\tR\x06MCPHex\x12n\n" +
	"\tChallenge\x18\x02 \x01(\v2P.mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNumChallengeR\tChallenge\"\xab\x02\n" +
	"\x17GetMCPCheckNumChallenge\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\x12{\n" +
	"\x0eFirstExtraData\x18\x02 \x01(\v2S.mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.MCPCheckChallengeExtraDataR\x0eFirstExtraData\x12}\n" +
	"\x0fSecondExtraData\x18\x03 \x01(\v2S.mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.MCPCheckChallengeExtraDataR\x0fSecondExtraData\"2\n" +
	"\x1aMCPCheckChallengeExtraData\x12\x14\n" +
	"\x05Value\x18\x01 \x03(\tR\x05ValueBPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc;py_rpcb\x06proto3"

var (
	file_py_rpc_get_mcp_check_num_proto_rawDescOnce sync.Once
	file_py_rpc_get_mcp_check_num_proto_rawDescData []byte
)

func file_py_rpc_get_mcp_check_num_proto_rawDescGZIP() []byte {
	file_py_rpc_get_mcp_check_num_proto_rawDescOnce.Do(func() {
		file_py_rpc_get_mcp_check_num_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_get_mcp_check_num_proto_rawDesc), len(file_py_rpc_get_mcp_check_num_proto_rawDesc)))
	})
	return file_py_rpc_get_mcp_check_num_proto_rawDescData
}

var file_py_rpc_get_mcp_check_num_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_py_rpc_get_mcp_check_num_proto_goTypes = []any{
	(*GetMCPCheckNum)(nil),             // 0: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNum
	(*GetMCPCheckNumChallenge)(nil),    // 1: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNumChallenge
	(*MCPCheckChallengeExtraData)(nil), // 2: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.MCPCheckChallengeExtraData
}
var file_py_rpc_get_mcp_check_num_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNum.Challenge:type_name -> mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNumChallenge
	2, // 1: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNumChallenge.FirstExtraData:type_name -> mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.MCPCheckChallengeExtraData
	2, // 2: mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.GetMCPCheckNumChallenge.SecondExtraData:type_name -> mousetunnel.minecraft.protocol.py_rpc.get_mcp_check_num.MCPCheckChallengeExtraData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_py_rpc_get_mcp_check_num_proto_init() }
func file_py_rpc_get_mcp_check_num_proto_init() {
	if File_py_rpc_get_mcp_check_num_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_get_mcp_check_num_proto_rawDesc), len(file_py_rpc_get_mcp_check_num_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_get_mcp_check_num_proto_goTypes,
		DependencyIndexes: file_py_rpc_get_mcp_check_num_proto_depIdxs,
		MessageInfos:      file_py_rpc_get_mcp_check_num_proto_msgTypes,
	}.Build()
	File_py_rpc_get_mcp_check_num_proto = out.File
	file_py_rpc_get_mcp_check_num_proto_goTypes = nil
	file_py_rpc_get_mcp_check_num_proto_depIdxs = nil
}
