// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event.proto

package py_rpc

import (
	define "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/define"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModEventTypeEnum int32

const (
	// ModEventTypeC2S 表示客户端到服务器的 ModEvent。
	//
	// ModEventTypeC2S marks a client-to-server ModEvent.
	ModEventTypeEnum_ModEventTypeC2S ModEventTypeEnum = 0
	// ModEventTypeS2C 表示服务器到客户端的 ModEvent。
	//
	// ModEventTypeS2C marks a server-to-client ModEvent.
	ModEventTypeEnum_ModEventTypeS2C ModEventTypeEnum = 1
)

// Enum value maps for ModEventTypeEnum.
var (
	ModEventTypeEnum_name = map[int32]string{
		0: "ModEventTypeC2S",
		1: "ModEventTypeS2C",
	}
	ModEventTypeEnum_value = map[string]int32{
		"ModEventTypeC2S": 0,
		"ModEventTypeS2C": 1,
	}
)

func (x ModEventTypeEnum) Enum() *ModEventTypeEnum {
	p := new(ModEventTypeEnum)
	*p = x
	return p
}

func (x ModEventTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModEventTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_py_rpc_mod_event_proto_enumTypes[0].Descriptor()
}

func (ModEventTypeEnum) Type() protoreflect.EnumType {
	return &file_py_rpc_mod_event_proto_enumTypes[0]
}

func (x ModEventTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModEventTypeEnum.Descriptor instead.
func (ModEventTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_proto_rawDescGZIP(), []int{0}
}

// ModEvent 保存网易 ModEvent PyRpc 载荷。
//
// ModEvent stores a NetEase ModEvent PyRpc payload.
type ModEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type 选择 Name 返回 ModEventC2S 还是 ModEventS2C。
	//
	// Type selects whether Name returns ModEventC2S or ModEventS2C.
	// Go type: uint8
	Type uint32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// PackageName 是顶层网易模块包名，例如 Minecraft。
	//
	// PackageName is the top-level NetEase module package, for example Minecraft.
	PackageName string `protobuf:"bytes,2,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	// ModuleName 是包内模块名，例如 chatExtension。
	//
	// ModuleName is the package module name, for example chatExtension.
	ModuleName string `protobuf:"bytes,3,opt,name=ModuleName,proto3" json:"ModuleName,omitempty"`
	// EventName 是模块内的具体事件名。
	//
	// EventName is the concrete event name inside the module.
	EventName string `protobuf:"bytes,4,opt,name=EventName,proto3" json:"EventName,omitempty"`
	// Event 是该 ModEvent 对应的强类型事件。设置后 MakeGo 会直接使用该事件生成载荷。
	//
	// Event is the strongly typed event represented by this ModEvent. When set,
	// MakeGo uses the event to generate the payload.
	Event         *define.Event `protobuf:"bytes,5,opt,name=Event,proto3" json:"Event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModEvent) Reset() {
	*x = ModEvent{}
	mi := &file_py_rpc_mod_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModEvent) ProtoMessage() {}

func (x *ModEvent) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModEvent.ProtoReflect.Descriptor instead.
func (*ModEvent) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_proto_rawDescGZIP(), []int{0}
}

func (x *ModEvent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ModEvent) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ModEvent) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ModEvent) GetEvent() *define.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_py_rpc_mod_event_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_proto_rawDesc = "" +
	"\n" +
	"\x16py_rpc/mod_event.proto\x12/mousetunnel.minecraft.protocol.py_rpc.mod_event\x1a\x1cgoogle/protobuf/struct.proto\x1a$py_rpc/mod_event/define/define.proto\"\xda\x01\n" +
	"\bModEvent\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\rR\x04Type\x12 \n" +
	"\vPackageName\x18\x02 \x01(\tR\vPackageName\x12\x1e\n" +
	"\n" +
	"ModuleName\x18\x03 \x01(\tR\n" +
	"ModuleName\x12\x1c\n" +
	"\tEventName\x18\x04 \x01(\tR\tEventName\x12Z\n" +
	"\x05Event\x18\x05 \x01(\v2D.mousetunnel.minecraft.protocol.py_rpc.mod_event.define.define.EventR\x05Event*<\n" +
	"\x10ModEventTypeEnum\x12\x13\n" +
	"\x0fModEventTypeC2S\x10\x00\x12\x13\n" +
	"\x0fModEventTypeS2C\x10\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc;py_rpcb\x06proto3"

var (
	file_py_rpc_mod_event_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_proto_rawDescData []byte
)

func file_py_rpc_mod_event_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_proto_rawDesc), len(file_py_rpc_mod_event_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_proto_rawDescData
}

var file_py_rpc_mod_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_py_rpc_mod_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_rpc_mod_event_proto_goTypes = []any{
	(ModEventTypeEnum)(0), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.ModEventTypeEnum
	(*ModEvent)(nil),      // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.ModEvent
	(*define.Event)(nil),  // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.define.define.Event
}
var file_py_rpc_mod_event_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.ModEvent.Event:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.define.define.Event
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_proto_init() }
func file_py_rpc_mod_event_proto_init() {
	if File_py_rpc_mod_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_proto_rawDesc), len(file_py_rpc_mod_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_proto_depIdxs,
		EnumInfos:         file_py_rpc_mod_event_proto_enumTypes,
		MessageInfos:      file_py_rpc_mod_event_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_proto = out.File
	file_py_rpc_mod_event_proto_goTypes = nil
	file_py_rpc_mod_event_proto_depIdxs = nil
}
