// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/set_owner_id.proto

package py_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetOwnerID 设置玩家的网易 User ID。
//
// SetOwnerID sets the NetEase user ID of the player.
type SetOwnerID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OwnerID 是分配给该客户端的网易 User ID。
	//
	// OwnerID is the NetEase user ID assigned to this client.
	OwnerID       uint64 `protobuf:"varint,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOwnerID) Reset() {
	*x = SetOwnerID{}
	mi := &file_py_rpc_set_owner_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOwnerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOwnerID) ProtoMessage() {}

func (x *SetOwnerID) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_set_owner_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOwnerID.ProtoReflect.Descriptor instead.
func (*SetOwnerID) Descriptor() ([]byte, []int) {
	return file_py_rpc_set_owner_id_proto_rawDescGZIP(), []int{0}
}

func (x *SetOwnerID) GetOwnerID() uint64 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

var File_py_rpc_set_owner_id_proto protoreflect.FileDescriptor

const file_py_rpc_set_owner_id_proto_rawDesc = "" +
	"\n" +
	"\x19py_rpc/set_owner_id.proto\x122mousetunnel.minecraft.protocol.py_rpc.set_owner_id\"&\n" +
	"\n" +
	"SetOwnerID\x12\x18\n" +
	"\aOwnerID\x18\x01 \x01(\x04R\aOwnerIDBJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc;py_rpcb\x06proto3"

var (
	file_py_rpc_set_owner_id_proto_rawDescOnce sync.Once
	file_py_rpc_set_owner_id_proto_rawDescData []byte
)

func file_py_rpc_set_owner_id_proto_rawDescGZIP() []byte {
	file_py_rpc_set_owner_id_proto_rawDescOnce.Do(func() {
		file_py_rpc_set_owner_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_set_owner_id_proto_rawDesc), len(file_py_rpc_set_owner_id_proto_rawDesc)))
	})
	return file_py_rpc_set_owner_id_proto_rawDescData
}

var file_py_rpc_set_owner_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_rpc_set_owner_id_proto_goTypes = []any{
	(*SetOwnerID)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.set_owner_id.SetOwnerID
}
var file_py_rpc_set_owner_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_py_rpc_set_owner_id_proto_init() }
func file_py_rpc_set_owner_id_proto_init() {
	if File_py_rpc_set_owner_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_set_owner_id_proto_rawDesc), len(file_py_rpc_set_owner_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_set_owner_id_proto_goTypes,
		DependencyIndexes: file_py_rpc_set_owner_id_proto_depIdxs,
		MessageInfos:      file_py_rpc_set_owner_id_proto_msgTypes,
	}.Build()
	File_py_rpc_set_owner_id_proto = out.File
	file_py_rpc_set_owner_id_proto_goTypes = nil
	file_py_rpc_set_owner_id_proto_depIdxs = nil
}
