// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_actors/conduit.proto

package block_actors

import (
	general_actors "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors/general_actors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Conduit 描述潮涌核心方块实体。
//
// Conduit describes the conduit block actor.
type Conduit struct {
	state      protoimpl.MessageState     `protogen:"open.v1"`
	BlockActor *general_actors.BlockActor `protobuf:"bytes,1,opt,name=BlockActor,proto3" json:"BlockActor,omitempty"`
	// TAG_Byte(1) = 0
	// Go type: byte
	Active uint32 `protobuf:"varint,2,opt,name=Active,proto3" json:"Active,omitempty"`
	// TAG_Long(5) = -1
	Target        int64 `protobuf:"varint,3,opt,name=Target,proto3" json:"Target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conduit) Reset() {
	*x = Conduit{}
	mi := &file_block_actors_conduit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conduit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conduit) ProtoMessage() {}

func (x *Conduit) ProtoReflect() protoreflect.Message {
	mi := &file_block_actors_conduit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conduit.ProtoReflect.Descriptor instead.
func (*Conduit) Descriptor() ([]byte, []int) {
	return file_block_actors_conduit_proto_rawDescGZIP(), []int{0}
}

func (x *Conduit) GetBlockActor() *general_actors.BlockActor {
	if x != nil {
		return x.BlockActor
	}
	return nil
}

func (x *Conduit) GetActive() uint32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *Conduit) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

var File_block_actors_conduit_proto protoreflect.FileDescriptor

const file_block_actors_conduit_proto_rawDesc = "" +
	"\n" +
	"\x1ablock_actors/conduit.proto\x123mousetunnel.minecraft.protocol.block_actors.conduit\x1a-block_actors/general_actors/block_actor.proto\"\xad\x01\n" +
	"\aConduit\x12r\n" +
	"\n" +
	"BlockActor\x18\x01 \x01(\v2R.mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActorR\n" +
	"BlockActor\x12\x16\n" +
	"\x06Active\x18\x02 \x01(\rR\x06Active\x12\x16\n" +
	"\x06Target\x18\x03 \x01(\x03R\x06TargetBVZTgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors;block_actorsb\x06proto3"

var (
	file_block_actors_conduit_proto_rawDescOnce sync.Once
	file_block_actors_conduit_proto_rawDescData []byte
)

func file_block_actors_conduit_proto_rawDescGZIP() []byte {
	file_block_actors_conduit_proto_rawDescOnce.Do(func() {
		file_block_actors_conduit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_actors_conduit_proto_rawDesc), len(file_block_actors_conduit_proto_rawDesc)))
	})
	return file_block_actors_conduit_proto_rawDescData
}

var file_block_actors_conduit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_actors_conduit_proto_goTypes = []any{
	(*Conduit)(nil),                   // 0: mousetunnel.minecraft.protocol.block_actors.conduit.Conduit
	(*general_actors.BlockActor)(nil), // 1: mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
}
var file_block_actors_conduit_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.block_actors.conduit.Conduit.BlockActor:type_name -> mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_block_actors_conduit_proto_init() }
func file_block_actors_conduit_proto_init() {
	if File_block_actors_conduit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_actors_conduit_proto_rawDesc), len(file_block_actors_conduit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_actors_conduit_proto_goTypes,
		DependencyIndexes: file_block_actors_conduit_proto_depIdxs,
		MessageInfos:      file_block_actors_conduit_proto_msgTypes,
	}.Build()
	File_block_actors_conduit_proto = out.File
	file_block_actors_conduit_proto_goTypes = nil
	file_block_actors_conduit_proto_depIdxs = nil
}
