// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_actors/enchant_table.proto

package block_actors

import (
	general_actors "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors/general_actors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnchantTable 描述附魔台方块实体。
//
// EnchantTable describes the enchanting table block actor.
type EnchantTable struct {
	state      protoimpl.MessageState     `protogen:"open.v1"`
	BlockActor *general_actors.BlockActor `protobuf:"bytes,1,opt,name=BlockActor,proto3" json:"BlockActor,omitempty"`
	// TAG_Float(6) = 0
	// Go type: float32
	Rotation      float32 `protobuf:"fixed32,2,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnchantTable) Reset() {
	*x = EnchantTable{}
	mi := &file_block_actors_enchant_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnchantTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnchantTable) ProtoMessage() {}

func (x *EnchantTable) ProtoReflect() protoreflect.Message {
	mi := &file_block_actors_enchant_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnchantTable.ProtoReflect.Descriptor instead.
func (*EnchantTable) Descriptor() ([]byte, []int) {
	return file_block_actors_enchant_table_proto_rawDescGZIP(), []int{0}
}

func (x *EnchantTable) GetBlockActor() *general_actors.BlockActor {
	if x != nil {
		return x.BlockActor
	}
	return nil
}

func (x *EnchantTable) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

var File_block_actors_enchant_table_proto protoreflect.FileDescriptor

const file_block_actors_enchant_table_proto_rawDesc = "" +
	"\n" +
	" block_actors/enchant_table.proto\x129mousetunnel.minecraft.protocol.block_actors.enchant_table\x1a-block_actors/general_actors/block_actor.proto\"\x9e\x01\n" +
	"\fEnchantTable\x12r\n" +
	"\n" +
	"BlockActor\x18\x01 \x01(\v2R.mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActorR\n" +
	"BlockActor\x12\x1a\n" +
	"\bRotation\x18\x02 \x01(\x02R\bRotationB\\ZZgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors;block_actorsb\x06proto3"

var (
	file_block_actors_enchant_table_proto_rawDescOnce sync.Once
	file_block_actors_enchant_table_proto_rawDescData []byte
)

func file_block_actors_enchant_table_proto_rawDescGZIP() []byte {
	file_block_actors_enchant_table_proto_rawDescOnce.Do(func() {
		file_block_actors_enchant_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_actors_enchant_table_proto_rawDesc), len(file_block_actors_enchant_table_proto_rawDesc)))
	})
	return file_block_actors_enchant_table_proto_rawDescData
}

var file_block_actors_enchant_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_actors_enchant_table_proto_goTypes = []any{
	(*EnchantTable)(nil),              // 0: mousetunnel.minecraft.protocol.block_actors.enchant_table.EnchantTable
	(*general_actors.BlockActor)(nil), // 1: mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
}
var file_block_actors_enchant_table_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.block_actors.enchant_table.EnchantTable.BlockActor:type_name -> mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_block_actors_enchant_table_proto_init() }
func file_block_actors_enchant_table_proto_init() {
	if File_block_actors_enchant_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_actors_enchant_table_proto_rawDesc), len(file_block_actors_enchant_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_actors_enchant_table_proto_goTypes,
		DependencyIndexes: file_block_actors_enchant_table_proto_depIdxs,
		MessageInfos:      file_block_actors_enchant_table_proto_msgTypes,
	}.Build()
	File_block_actors_enchant_table_proto = out.File
	file_block_actors_enchant_table_proto_goTypes = nil
	file_block_actors_enchant_table_proto_depIdxs = nil
}
