// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_actors/jukebox.proto

package block_actors

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	general_actors "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors/general_actors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Jukebox 描述唱片机方块实体。
//
// Jukebox describes the jukebox block actor.
type Jukebox struct {
	state      protoimpl.MessageState     `protogen:"open.v1"`
	BlockActor *general_actors.BlockActor `protobuf:"bytes,1,opt,name=BlockActor,proto3" json:"BlockActor,omitempty"`
	// TAG_Compound(10)
	// Go type: *protocol.Item
	RecordItem    *protocol.Item `protobuf:"bytes,2,opt,name=RecordItem,proto3" json:"RecordItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jukebox) Reset() {
	*x = Jukebox{}
	mi := &file_block_actors_jukebox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jukebox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jukebox) ProtoMessage() {}

func (x *Jukebox) ProtoReflect() protoreflect.Message {
	mi := &file_block_actors_jukebox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jukebox.ProtoReflect.Descriptor instead.
func (*Jukebox) Descriptor() ([]byte, []int) {
	return file_block_actors_jukebox_proto_rawDescGZIP(), []int{0}
}

func (x *Jukebox) GetBlockActor() *general_actors.BlockActor {
	if x != nil {
		return x.BlockActor
	}
	return nil
}

func (x *Jukebox) GetRecordItem() *protocol.Item {
	if x != nil {
		return x.RecordItem
	}
	return nil
}

var File_block_actors_jukebox_proto protoreflect.FileDescriptor

const file_block_actors_jukebox_proto_rawDesc = "" +
	"\n" +
	"\x1ablock_actors/jukebox.proto\x123mousetunnel.minecraft.protocol.block_actors.jukebox\x1a-block_actors/general_actors/block_actor.proto\x1a\x0enbt_item.proto\"\xcc\x01\n" +
	"\aJukebox\x12r\n" +
	"\n" +
	"BlockActor\x18\x01 \x01(\v2R.mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActorR\n" +
	"BlockActor\x12M\n" +
	"\n" +
	"RecordItem\x18\x02 \x01(\v2-.mousetunnel.minecraft.protocol.nbt_item.ItemR\n" +
	"RecordItemBVZTgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors;block_actorsb\x06proto3"

var (
	file_block_actors_jukebox_proto_rawDescOnce sync.Once
	file_block_actors_jukebox_proto_rawDescData []byte
)

func file_block_actors_jukebox_proto_rawDescGZIP() []byte {
	file_block_actors_jukebox_proto_rawDescOnce.Do(func() {
		file_block_actors_jukebox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_actors_jukebox_proto_rawDesc), len(file_block_actors_jukebox_proto_rawDesc)))
	})
	return file_block_actors_jukebox_proto_rawDescData
}

var file_block_actors_jukebox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_actors_jukebox_proto_goTypes = []any{
	(*Jukebox)(nil),                   // 0: mousetunnel.minecraft.protocol.block_actors.jukebox.Jukebox
	(*general_actors.BlockActor)(nil), // 1: mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
	(*protocol.Item)(nil),             // 2: mousetunnel.minecraft.protocol.nbt_item.Item
}
var file_block_actors_jukebox_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.block_actors.jukebox.Jukebox.BlockActor:type_name -> mousetunnel.minecraft.protocol.block_actors.general_actors.block_actor.BlockActor
	2, // 1: mousetunnel.minecraft.protocol.block_actors.jukebox.Jukebox.RecordItem:type_name -> mousetunnel.minecraft.protocol.nbt_item.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_block_actors_jukebox_proto_init() }
func file_block_actors_jukebox_proto_init() {
	if File_block_actors_jukebox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_actors_jukebox_proto_rawDesc), len(file_block_actors_jukebox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_actors_jukebox_proto_goTypes,
		DependencyIndexes: file_block_actors_jukebox_proto_depIdxs,
		MessageInfos:      file_block_actors_jukebox_proto_msgTypes,
	}.Build()
	File_block_actors_jukebox_proto = out.File
	file_block_actors_jukebox_proto_goTypes = nil
	file_block_actors_jukebox_proto_depIdxs = nil
}
