// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: login/request.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthResult 是 Parse 的返回结果，包含客户端的 ecdsa.PublicKey 和玩家是否通过 XBOX Live 登录的标记。
//
// AuthResult is returned by a call to Parse. It holds the ecdsa.PublicKey of the client and a bool that
// indicates if the player was logged in with XBOX Live.
//
// Added: v1.21.90
type AuthResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PublicKey 是已验证的客户端公钥，用于加密。
	//
	// PublicKey is the verified client public key used for encryption.
	//
	// Added: v1.21.90
	// Go type: *ecdsa.PublicKey
	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	// XBOXLiveAuthenticated 表示登录请求是否通过 Xbox Live 认证。
	//
	// XBOXLiveAuthenticated indicates if the login request was authenticated through Xbox Live.
	//
	// Added: v1.21.90
	XBOXLiveAuthenticated bool `protobuf:"varint,2,opt,name=XBOXLiveAuthenticated,proto3" json:"XBOXLiveAuthenticated,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_login_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_login_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_login_request_proto_rawDescGZIP(), []int{0}
}

func (x *AuthResult) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AuthResult) GetXBOXLiveAuthenticated() bool {
	if x != nil {
		return x.XBOXLiveAuthenticated
	}
	return false
}

var File_login_request_proto protoreflect.FileDescriptor

const file_login_request_proto_rawDesc = "" +
	"\n" +
	"\x13login/request.proto\x12,mousetunnel.minecraft.protocol.login.request\"`\n" +
	"\n" +
	"AuthResult\x12\x1c\n" +
	"\tPublicKey\x18\x01 \x01(\fR\tPublicKey\x124\n" +
	"\x15XBOXLiveAuthenticated\x18\x02 \x01(\bR\x15XBOXLiveAuthenticatedBNZLgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/login;loginb\x06proto3"

var (
	file_login_request_proto_rawDescOnce sync.Once
	file_login_request_proto_rawDescData []byte
)

func file_login_request_proto_rawDescGZIP() []byte {
	file_login_request_proto_rawDescOnce.Do(func() {
		file_login_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_request_proto_rawDesc), len(file_login_request_proto_rawDesc)))
	})
	return file_login_request_proto_rawDescData
}

var file_login_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_login_request_proto_goTypes = []any{
	(*AuthResult)(nil), // 0: mousetunnel.minecraft.protocol.login.request.AuthResult
}
var file_login_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_request_proto_init() }
func file_login_request_proto_init() {
	if File_login_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_request_proto_rawDesc), len(file_login_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_request_proto_goTypes,
		DependencyIndexes: file_login_request_proto_depIdxs,
		MessageInfos:      file_login_request_proto_msgTypes,
	}.Build()
	File_login_request_proto = out.File
	file_login_request_proto_goTypes = nil
	file_login_request_proto_depIdxs = nil
}
