// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/animate_entity.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnimateEntity 由服务器发送，用于在客户端侧播放实体动画。它可以播放单个动画，
// 也可以激活动画控制器，并由控制器根据不同条件启动一系列动画。
// 该数据包的大部分文档可在下方链接中找到。
//
// AnimateEntity is sent by the server to animate an entity client-side. It may be used to play a single
// animation, or to activate a controller which can start a sequence of animations based on different
// conditions specified in an animation controller.
// Much of the documentation of this packet can be found at
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference
//
// Added: v1.16.100
type AnimateEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Animation 是要开始播放的单个动画名称。
	//
	// Animation is the name of a single animation to start playing.
	//
	// Added: v1.16.100
	Animation string `protobuf:"bytes,1,opt,name=Animation,proto3" json:"Animation,omitempty"`
	// NextState 是首先进入的状态。这些状态声明在动画控制器中，动画控制器本身也是动画；
	// 每个状态又可以包含动画和用于切换到下一个状态的转换条件。
	//
	// NextState is the first state to start with. These states are declared in animation controllers (which,
	// in themselves, are animations too). These states in turn may have animations and transitions to move to
	// a next state.
	//
	// Added: v1.16.100
	NextState string `protobuf:"bytes,2,opt,name=NextState,proto3" json:"NextState,omitempty"`
	// StopCondition 是一个 MoLang 表达式，用于指定动画何时停止。
	//
	// StopCondition is a MoLang expression that specifies when the animation should be stopped.
	//
	// Added: v1.16.100
	StopCondition string `protobuf:"bytes,3,opt,name=StopCondition,proto3" json:"StopCondition,omitempty"`
	// StopConditionVersion 是 MoLang 停止条件版本。
	//
	// StopConditionVersion is the MoLang stop condition version.
	//
	// Added: v1.17.30
	StopConditionVersion int32 `protobuf:"varint,4,opt,name=StopConditionVersion,proto3" json:"StopConditionVersion,omitempty"`
	// Controller 是用于管理动画的动画控制器。这些控制器决定何时播放哪个动画。
	//
	// Controller is the animation controller that is used to manage animations. These controllers decide when
	// to play which animation.
	//
	// Added: v1.16.100
	Controller string `protobuf:"bytes,5,opt,name=Controller,proto3" json:"Controller,omitempty"`
	// BlendOutTime 目前看起来尚未被使用。
	//
	// BlendOutTime does not currently seem to be used.
	//
	// Added: v1.16.100
	// Go type: float32
	BlendOutTime float32 `protobuf:"fixed32,6,opt,name=BlendOutTime,proto3" json:"BlendOutTime,omitempty"`
	// EntityRuntimeIDs 是应应用该动画的实体运行时 ID 列表。
	//
	// EntityRuntimeIDs is list of runtime IDs of entities that the animation should be applied to.
	//
	// Added: v1.16.100
	// Go type: []uint64
	EntityRuntimeIDs []uint64 `protobuf:"varint,7,rep,packed,name=EntityRuntimeIDs,proto3" json:"EntityRuntimeIDs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnimateEntity) Reset() {
	*x = AnimateEntity{}
	mi := &file_packet_animate_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimateEntity) ProtoMessage() {}

func (x *AnimateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_packet_animate_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimateEntity.ProtoReflect.Descriptor instead.
func (*AnimateEntity) Descriptor() ([]byte, []int) {
	return file_packet_animate_entity_proto_rawDescGZIP(), []int{0}
}

func (x *AnimateEntity) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *AnimateEntity) GetNextState() string {
	if x != nil {
		return x.NextState
	}
	return ""
}

func (x *AnimateEntity) GetStopCondition() string {
	if x != nil {
		return x.StopCondition
	}
	return ""
}

func (x *AnimateEntity) GetStopConditionVersion() int32 {
	if x != nil {
		return x.StopConditionVersion
	}
	return 0
}

func (x *AnimateEntity) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *AnimateEntity) GetBlendOutTime() float32 {
	if x != nil {
		return x.BlendOutTime
	}
	return 0
}

func (x *AnimateEntity) GetEntityRuntimeIDs() []uint64 {
	if x != nil {
		return x.EntityRuntimeIDs
	}
	return nil
}

var File_packet_animate_entity_proto protoreflect.FileDescriptor

const file_packet_animate_entity_proto_rawDesc = "" +
	"\n" +
	"\x1bpacket/animate_entity.proto\x124mousetunnel.minecraft.protocol.packet.animate_entity\x1a\x14packet_options.proto\"\x9c\x02\n" +
	"\rAnimateEntity\x12\x1c\n" +
	"\tAnimation\x18\x01 \x01(\tR\tAnimation\x12\x1c\n" +
	"\tNextState\x18\x02 \x01(\tR\tNextState\x12$\n" +
	"\rStopCondition\x18\x03 \x01(\tR\rStopCondition\x122\n" +
	"\x14StopConditionVersion\x18\x04 \x01(\x05R\x14StopConditionVersion\x12\x1e\n" +
	"\n" +
	"Controller\x18\x05 \x01(\tR\n" +
	"Controller\x12\"\n" +
	"\fBlendOutTime\x18\x06 \x01(\x02R\fBlendOutTime\x12*\n" +
	"\x10EntityRuntimeIDs\x18\a \x03(\x04R\x10EntityRuntimeIDs:\x05\xc0\xc8\x05\x9e\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_animate_entity_proto_rawDescOnce sync.Once
	file_packet_animate_entity_proto_rawDescData []byte
)

func file_packet_animate_entity_proto_rawDescGZIP() []byte {
	file_packet_animate_entity_proto_rawDescOnce.Do(func() {
		file_packet_animate_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_animate_entity_proto_rawDesc), len(file_packet_animate_entity_proto_rawDesc)))
	})
	return file_packet_animate_entity_proto_rawDescData
}

var file_packet_animate_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_animate_entity_proto_goTypes = []any{
	(*AnimateEntity)(nil), // 0: mousetunnel.minecraft.protocol.packet.animate_entity.AnimateEntity
}
var file_packet_animate_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_animate_entity_proto_init() }
func file_packet_animate_entity_proto_init() {
	if File_packet_animate_entity_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_animate_entity_proto_rawDesc), len(file_packet_animate_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_animate_entity_proto_goTypes,
		DependencyIndexes: file_packet_animate_entity_proto_depIdxs,
		MessageInfos:      file_packet_animate_entity_proto_msgTypes,
	}.Build()
	File_packet_animate_entity_proto = out.File
	file_packet_animate_entity_proto_goTypes = nil
	file_packet_animate_entity_proto_depIdxs = nil
}
