// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/block_event.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockEvent 由服务器发送，用于发起与特定方块相关的事件，例如打开箱子。
//
// BlockEvent is sent by the server to initiate a certain event that has something to do with blocks in
// specific, for example opening a chest.
//
// Added: v1.11.1
type BlockEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position 是发生事件的方块位置。
	//
	// Position is the position of the block that an event occurred at.
	//
	// Added: v1.11.1
	Position *protocol.BlockPos `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	// EventType 是方块事件类型。事件类型决定后续事件数据的使用方式，
	// 它是上方常量之一。
	//
	// EventType is the type of the block event. The event type decides the way the event data that follows
	// is used. It is one of the constants found above.
	//
	// Added: v1.11.1
	EventType int32 `protobuf:"varint,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
	// EventData 保存特定于事件类型的数据。例如对箱子而言，打开箱子时数据必须为 1，
	// 关闭箱子时应为 0。
	//
	// EventData holds event type specific data. For chests for example, opening the chest means the data must
	// hold 1, whereas closing it should hold 0.
	//
	// Added: v1.11.1
	EventData     int32 `protobuf:"varint,3,opt,name=EventData,proto3" json:"EventData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_packet_block_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packet_block_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_packet_block_event_proto_rawDescGZIP(), []int{0}
}

func (x *BlockEvent) GetPosition() *protocol.BlockPos {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BlockEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *BlockEvent) GetEventData() int32 {
	if x != nil {
		return x.EventData
	}
	return 0
}

var File_packet_block_event_proto protoreflect.FileDescriptor

const file_packet_block_event_proto_rawDesc = "" +
	"\n" +
	"\x18packet/block_event.proto\x121mousetunnel.minecraft.protocol.packet.block_event\x1a\x0fblock_pos.proto\x1a\x14packet_options.proto\"\x9e\x01\n" +
	"\n" +
	"BlockEvent\x12N\n" +
	"\bPosition\x18\x01 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\bPosition\x12\x1c\n" +
	"\tEventType\x18\x02 \x01(\x05R\tEventType\x12\x1c\n" +
	"\tEventData\x18\x03 \x01(\x05R\tEventData:\x04\xc0\xc8\x05\x1aBPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_block_event_proto_rawDescOnce sync.Once
	file_packet_block_event_proto_rawDescData []byte
)

func file_packet_block_event_proto_rawDescGZIP() []byte {
	file_packet_block_event_proto_rawDescOnce.Do(func() {
		file_packet_block_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_block_event_proto_rawDesc), len(file_packet_block_event_proto_rawDesc)))
	})
	return file_packet_block_event_proto_rawDescData
}

var file_packet_block_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_block_event_proto_goTypes = []any{
	(*BlockEvent)(nil),        // 0: mousetunnel.minecraft.protocol.packet.block_event.BlockEvent
	(*protocol.BlockPos)(nil), // 1: mousetunnel.minecraft.protocol.block_pos.BlockPos
}
var file_packet_block_event_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.block_event.BlockEvent.Position:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_block_event_proto_init() }
func file_packet_block_event_proto_init() {
	if File_packet_block_event_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_block_event_proto_rawDesc), len(file_packet_block_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_block_event_proto_goTypes,
		DependencyIndexes: file_packet_block_event_proto_depIdxs,
		MessageInfos:      file_packet_block_event_proto_msgTypes,
	}.Build()
	File_packet_block_event_proto = out.File
	file_packet_block_event_proto_goTypes = nil
	file_packet_block_event_proto_depIdxs = nil
}
