// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/camera_instruction.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraInstructionOptionalBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalBool) Reset() {
	*x = CameraInstructionOptionalBool{}
	mi := &file_packet_camera_instruction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalBool) ProtoMessage() {}

func (x *CameraInstructionOptionalBool) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalBool.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalBool) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{0}
}

func (x *CameraInstructionOptionalBool) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type CameraInstructionOptionalCameraInstructionFade struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Present       bool                            `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         *protocol.CameraInstructionFade `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalCameraInstructionFade) Reset() {
	*x = CameraInstructionOptionalCameraInstructionFade{}
	mi := &file_packet_camera_instruction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalCameraInstructionFade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalCameraInstructionFade) ProtoMessage() {}

func (x *CameraInstructionOptionalCameraInstructionFade) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalCameraInstructionFade.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalCameraInstructionFade) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{1}
}

func (x *CameraInstructionOptionalCameraInstructionFade) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalCameraInstructionFade) GetValue() *protocol.CameraInstructionFade {
	if x != nil {
		return x.Value
	}
	return nil
}

type CameraInstructionOptionalCameraInstructionFieldOfView struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Present       bool                                   `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         *protocol.CameraInstructionFieldOfView `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalCameraInstructionFieldOfView) Reset() {
	*x = CameraInstructionOptionalCameraInstructionFieldOfView{}
	mi := &file_packet_camera_instruction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalCameraInstructionFieldOfView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalCameraInstructionFieldOfView) ProtoMessage() {}

func (x *CameraInstructionOptionalCameraInstructionFieldOfView) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalCameraInstructionFieldOfView.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalCameraInstructionFieldOfView) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{2}
}

func (x *CameraInstructionOptionalCameraInstructionFieldOfView) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalCameraInstructionFieldOfView) GetValue() *protocol.CameraInstructionFieldOfView {
	if x != nil {
		return x.Value
	}
	return nil
}

type CameraInstructionOptionalCameraInstructionSet struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Present       bool                           `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         *protocol.CameraInstructionSet `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalCameraInstructionSet) Reset() {
	*x = CameraInstructionOptionalCameraInstructionSet{}
	mi := &file_packet_camera_instruction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalCameraInstructionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalCameraInstructionSet) ProtoMessage() {}

func (x *CameraInstructionOptionalCameraInstructionSet) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalCameraInstructionSet.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalCameraInstructionSet) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{3}
}

func (x *CameraInstructionOptionalCameraInstructionSet) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalCameraInstructionSet) GetValue() *protocol.CameraInstructionSet {
	if x != nil {
		return x.Value
	}
	return nil
}

type CameraInstructionOptionalCameraInstructionTarget struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Present       bool                              `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         *protocol.CameraInstructionTarget `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalCameraInstructionTarget) Reset() {
	*x = CameraInstructionOptionalCameraInstructionTarget{}
	mi := &file_packet_camera_instruction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalCameraInstructionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalCameraInstructionTarget) ProtoMessage() {}

func (x *CameraInstructionOptionalCameraInstructionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalCameraInstructionTarget.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalCameraInstructionTarget) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{4}
}

func (x *CameraInstructionOptionalCameraInstructionTarget) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalCameraInstructionTarget) GetValue() *protocol.CameraInstructionTarget {
	if x != nil {
		return x.Value
	}
	return nil
}

type CameraInstructionOptionalCameraSplineInstruction struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Present       bool                              `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         *protocol.CameraSplineInstruction `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalCameraSplineInstruction) Reset() {
	*x = CameraInstructionOptionalCameraSplineInstruction{}
	mi := &file_packet_camera_instruction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalCameraSplineInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalCameraSplineInstruction) ProtoMessage() {}

func (x *CameraInstructionOptionalCameraSplineInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalCameraSplineInstruction.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalCameraSplineInstruction) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{5}
}

func (x *CameraInstructionOptionalCameraSplineInstruction) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalCameraSplineInstruction) GetValue() *protocol.CameraSplineInstruction {
	if x != nil {
		return x.Value
	}
	return nil
}

type CameraInstructionOptionalInt64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=Present,proto3" json:"Present,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraInstructionOptionalInt64) Reset() {
	*x = CameraInstructionOptionalInt64{}
	mi := &file_packet_camera_instruction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstructionOptionalInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstructionOptionalInt64) ProtoMessage() {}

func (x *CameraInstructionOptionalInt64) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstructionOptionalInt64.ProtoReflect.Descriptor instead.
func (*CameraInstructionOptionalInt64) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{6}
}

func (x *CameraInstructionOptionalInt64) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *CameraInstructionOptionalInt64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// CameraInstruction 为自定义相机提供特定的操作指令。
//
// CameraInstruction gives a custom camera specific instructions to operate.
//
// Added: v1.20.30
type CameraInstruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set 是相机指令，用于将相机设置为指定预设。
	//
	// Set is a camera instruction that sets the camera to a specified preset.
	//
	// Added: v1.20.30
	// Go type: protocol.Optional[protocol.CameraInstructionSet]
	Set *CameraInstructionOptionalCameraInstructionSet `protobuf:"bytes,1,opt,name=Set,proto3" json:"Set,omitempty"`
	// Clear 可设为 true，用于清除所有当前相机指令。
	//
	// Clear can be set to true to clear all the current camera instructions.
	//
	// Added: v1.20.30
	// Go type: protocol.Optional[bool]
	Clear *CameraInstructionOptionalBool `protobuf:"bytes,2,opt,name=Clear,proto3" json:"Clear,omitempty"`
	// Fade 是相机指令，用于将屏幕淡入或淡出到指定颜色。
	//
	// Fade is a camera instruction that fades the screen to a specified colour.
	//
	// Added: v1.20.30
	// Go type: protocol.Optional[protocol.CameraInstructionFade]
	Fade *CameraInstructionOptionalCameraInstructionFade `protobuf:"bytes,3,opt,name=Fade,proto3" json:"Fade,omitempty"`
	// Target 是相机指令，用于瞄准特定实体。
	//
	// Target is a camera instruction that targets a specific entity.
	//
	// Added: v1.21.20
	// Go type: protocol.Optional[protocol.CameraInstructionTarget]
	Target *CameraInstructionOptionalCameraInstructionTarget `protobuf:"bytes,4,opt,name=Target,proto3" json:"Target,omitempty"`
	// RemoveTarget 可设为 true，用于移除当前辅助瞄准目标。
	//
	// RemoveTarget can be set to true to remove the current aim assist target.
	//
	// Added: v1.21.20
	// Go type: protocol.Optional[bool]
	RemoveTarget *CameraInstructionOptionalBool `protobuf:"bytes,5,opt,name=RemoveTarget,proto3" json:"RemoveTarget,omitempty"`
	// FieldOfView 是相机指令，用于更新相机视野。
	//
	// FieldOfView is a camera instruction that updates the field of view for the camera.
	//
	// Added: v1.21.100
	// Go type: protocol.Optional[protocol.CameraInstructionFieldOfView]
	FieldOfView *CameraInstructionOptionalCameraInstructionFieldOfView `protobuf:"bytes,6,opt,name=FieldOfView,proto3" json:"FieldOfView,omitempty"`
	// Spline 是相机指令，用于创建相机跟随的样条路径。
	//
	// Spline is a camera instruction that creates a spline path for the camera to follow.
	//
	// Added: v1.21.111
	// Go type: protocol.Optional[protocol.CameraSplineInstruction]
	Spline *CameraInstructionOptionalCameraSplineInstruction `protobuf:"bytes,7,opt,name=Spline,proto3" json:"Spline,omitempty"`
	// AttachToEntity 是相机要附着到的实体 ID。
	//
	// AttachToEntity is the entity ID to attach the camera to.
	//
	// Added: v1.21.111
	// Go type: protocol.Optional[int64]
	AttachToEntity *CameraInstructionOptionalInt64 `protobuf:"bytes,8,opt,name=AttachToEntity,proto3" json:"AttachToEntity,omitempty"`
	// DetachFromEntity 可设为 true，用于将相机从当前实体上分离。
	//
	// DetachFromEntity can be set to true to detach the camera from the current entity.
	//
	// Added: v1.21.111
	// Go type: protocol.Optional[bool]
	DetachFromEntity *CameraInstructionOptionalBool `protobuf:"bytes,9,opt,name=DetachFromEntity,proto3" json:"DetachFromEntity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CameraInstruction) Reset() {
	*x = CameraInstruction{}
	mi := &file_packet_camera_instruction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInstruction) ProtoMessage() {}

func (x *CameraInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_packet_camera_instruction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInstruction.ProtoReflect.Descriptor instead.
func (*CameraInstruction) Descriptor() ([]byte, []int) {
	return file_packet_camera_instruction_proto_rawDescGZIP(), []int{7}
}

func (x *CameraInstruction) GetSet() *CameraInstructionOptionalCameraInstructionSet {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *CameraInstruction) GetClear() *CameraInstructionOptionalBool {
	if x != nil {
		return x.Clear
	}
	return nil
}

func (x *CameraInstruction) GetFade() *CameraInstructionOptionalCameraInstructionFade {
	if x != nil {
		return x.Fade
	}
	return nil
}

func (x *CameraInstruction) GetTarget() *CameraInstructionOptionalCameraInstructionTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CameraInstruction) GetRemoveTarget() *CameraInstructionOptionalBool {
	if x != nil {
		return x.RemoveTarget
	}
	return nil
}

func (x *CameraInstruction) GetFieldOfView() *CameraInstructionOptionalCameraInstructionFieldOfView {
	if x != nil {
		return x.FieldOfView
	}
	return nil
}

func (x *CameraInstruction) GetSpline() *CameraInstructionOptionalCameraSplineInstruction {
	if x != nil {
		return x.Spline
	}
	return nil
}

func (x *CameraInstruction) GetAttachToEntity() *CameraInstructionOptionalInt64 {
	if x != nil {
		return x.AttachToEntity
	}
	return nil
}

func (x *CameraInstruction) GetDetachFromEntity() *CameraInstructionOptionalBool {
	if x != nil {
		return x.DetachFromEntity
	}
	return nil
}

var File_packet_camera_instruction_proto protoreflect.FileDescriptor

const file_packet_camera_instruction_proto_rawDesc = "" +
	"\n" +
	"\x1fpacket/camera_instruction.proto\x128mousetunnel.minecraft.protocol.packet.camera_instruction\x1a\fcamera.proto\x1a\x14packet_options.proto\"O\n" +
	"\x1dCameraInstructionOptionalBool\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\bR\x05Value\"\x9e\x01\n" +
	".CameraInstructionOptionalCameraInstructionFade\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12R\n" +
	"\x05Value\x18\x02 \x01(\v2<.mousetunnel.minecraft.protocol.camera.CameraInstructionFadeR\x05Value\"\xac\x01\n" +
	"5CameraInstructionOptionalCameraInstructionFieldOfView\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12Y\n" +
	"\x05Value\x18\x02 \x01(\v2C.mousetunnel.minecraft.protocol.camera.CameraInstructionFieldOfViewR\x05Value\"\x9c\x01\n" +
	"-CameraInstructionOptionalCameraInstructionSet\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12Q\n" +
	"\x05Value\x18\x02 \x01(\v2;.mousetunnel.minecraft.protocol.camera.CameraInstructionSetR\x05Value\"\xa2\x01\n" +
	"0CameraInstructionOptionalCameraInstructionTarget\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12T\n" +
	"\x05Value\x18\x02 \x01(\v2>.mousetunnel.minecraft.protocol.camera.CameraInstructionTargetR\x05Value\"\xa2\x01\n" +
	"0CameraInstructionOptionalCameraSplineInstruction\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12T\n" +
	"\x05Value\x18\x02 \x01(\v2>.mousetunnel.minecraft.protocol.camera.CameraSplineInstructionR\x05Value\"P\n" +
	"\x1eCameraInstructionOptionalInt64\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\bR\aPresent\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x03R\x05Value\"\xa6\t\n" +
	"\x11CameraInstruction\x12y\n" +
	"\x03Set\x18\x01 \x01(\v2g.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionSetR\x03Set\x12m\n" +
	"\x05Clear\x18\x02 \x01(\v2W.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBoolR\x05Clear\x12|\n" +
	"\x04Fade\x18\x03 \x01(\v2h.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFadeR\x04Fade\x12\x82\x01\n" +
	"\x06Target\x18\x04 \x01(\v2j.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionTargetR\x06Target\x12{\n" +
	"\fRemoveTarget\x18\x05 \x01(\v2W.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBoolR\fRemoveTarget\x12\x91\x01\n" +
	"\vFieldOfView\x18\x06 \x01(\v2o.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFieldOfViewR\vFieldOfView\x12\x82\x01\n" +
	"\x06Spline\x18\a \x01(\v2j.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraSplineInstructionR\x06Spline\x12\x80\x01\n" +
	"\x0eAttachToEntity\x18\b \x01(\v2X.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalInt64R\x0eAttachToEntity\x12\x83\x01\n" +
	"\x10DetachFromEntity\x18\t \x01(\v2W.mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBoolR\x10DetachFromEntity:\x05\xc0\xc8\x05\xac\x02BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_camera_instruction_proto_rawDescOnce sync.Once
	file_packet_camera_instruction_proto_rawDescData []byte
)

func file_packet_camera_instruction_proto_rawDescGZIP() []byte {
	file_packet_camera_instruction_proto_rawDescOnce.Do(func() {
		file_packet_camera_instruction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_camera_instruction_proto_rawDesc), len(file_packet_camera_instruction_proto_rawDesc)))
	})
	return file_packet_camera_instruction_proto_rawDescData
}

var file_packet_camera_instruction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_packet_camera_instruction_proto_goTypes = []any{
	(*CameraInstructionOptionalBool)(nil),                         // 0: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBool
	(*CameraInstructionOptionalCameraInstructionFade)(nil),        // 1: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFade
	(*CameraInstructionOptionalCameraInstructionFieldOfView)(nil), // 2: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFieldOfView
	(*CameraInstructionOptionalCameraInstructionSet)(nil),         // 3: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionSet
	(*CameraInstructionOptionalCameraInstructionTarget)(nil),      // 4: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionTarget
	(*CameraInstructionOptionalCameraSplineInstruction)(nil),      // 5: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraSplineInstruction
	(*CameraInstructionOptionalInt64)(nil),                        // 6: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalInt64
	(*CameraInstruction)(nil),                                     // 7: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction
	(*protocol.CameraInstructionFade)(nil),                        // 8: mousetunnel.minecraft.protocol.camera.CameraInstructionFade
	(*protocol.CameraInstructionFieldOfView)(nil),                 // 9: mousetunnel.minecraft.protocol.camera.CameraInstructionFieldOfView
	(*protocol.CameraInstructionSet)(nil),                         // 10: mousetunnel.minecraft.protocol.camera.CameraInstructionSet
	(*protocol.CameraInstructionTarget)(nil),                      // 11: mousetunnel.minecraft.protocol.camera.CameraInstructionTarget
	(*protocol.CameraSplineInstruction)(nil),                      // 12: mousetunnel.minecraft.protocol.camera.CameraSplineInstruction
}
var file_packet_camera_instruction_proto_depIdxs = []int32{
	8,  // 0: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFade.Value:type_name -> mousetunnel.minecraft.protocol.camera.CameraInstructionFade
	9,  // 1: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFieldOfView.Value:type_name -> mousetunnel.minecraft.protocol.camera.CameraInstructionFieldOfView
	10, // 2: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionSet.Value:type_name -> mousetunnel.minecraft.protocol.camera.CameraInstructionSet
	11, // 3: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionTarget.Value:type_name -> mousetunnel.minecraft.protocol.camera.CameraInstructionTarget
	12, // 4: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraSplineInstruction.Value:type_name -> mousetunnel.minecraft.protocol.camera.CameraSplineInstruction
	3,  // 5: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.Set:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionSet
	0,  // 6: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.Clear:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBool
	1,  // 7: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.Fade:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFade
	4,  // 8: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.Target:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionTarget
	0,  // 9: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.RemoveTarget:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBool
	2,  // 10: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.FieldOfView:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraInstructionFieldOfView
	5,  // 11: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.Spline:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalCameraSplineInstruction
	6,  // 12: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.AttachToEntity:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalInt64
	0,  // 13: mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstruction.DetachFromEntity:type_name -> mousetunnel.minecraft.protocol.packet.camera_instruction.CameraInstructionOptionalBool
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_packet_camera_instruction_proto_init() }
func file_packet_camera_instruction_proto_init() {
	if File_packet_camera_instruction_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_camera_instruction_proto_rawDesc), len(file_packet_camera_instruction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_camera_instruction_proto_goTypes,
		DependencyIndexes: file_packet_camera_instruction_proto_depIdxs,
		MessageInfos:      file_packet_camera_instruction_proto_msgTypes,
	}.Build()
	File_packet_camera_instruction_proto = out.File
	file_packet_camera_instruction_proto_goTypes = nil
	file_packet_camera_instruction_proto_depIdxs = nil
}
