// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/change_mob_property.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeMobProperty 是服务器发送给客户端的数据包，用于在客户端侧更改生物的某个属性。
//
// ChangeMobProperty is a packet sent from the server to the client to change one of the properties of a mob client-side.
//
// Added: v1.18.30
type ChangeMobProperty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EntityUniqueID 是属性正在被更改的实体唯一 ID。
	//
	// EntityUniqueID is the unique ID of the entity whose property is being changed.
	//
	// Added: v1.18.30
	EntityUniqueID int64 `protobuf:"varint,1,opt,name=EntityUniqueID,proto3" json:"EntityUniqueID,omitempty"`
	// Property 是正在更新的属性名称。
	//
	// Property is the name of the property being updated.
	//
	// Added: v1.18.30
	Property string `protobuf:"bytes,2,opt,name=Property,proto3" json:"Property,omitempty"`
	// BoolValue 在属性值为 bool 类型时设置。如果类型不是 bool，该字段会被忽略。
	//
	// BoolValue is set if the property value is a bool type. If the type is not a bool, this field is ignored.
	//
	// Added: v1.18.30
	BoolValue bool `protobuf:"varint,3,opt,name=BoolValue,proto3" json:"BoolValue,omitempty"`
	// StringValue 在属性值为 string 类型时设置。如果类型不是 string，该字段会被忽略。
	//
	// StringValue is set if the property value is a string type. If the type is not a string, this field is ignored.
	//
	// Added: v1.18.30
	StringValue string `protobuf:"bytes,4,opt,name=StringValue,proto3" json:"StringValue,omitempty"`
	// IntValue 在属性值为 int 类型时设置。如果类型不是 int，该字段会被忽略。
	//
	// IntValue is set if the property value is an int type. If the type is not an int, this field is ignored.
	//
	// Added: v1.18.30
	IntValue int32 `protobuf:"varint,5,opt,name=IntValue,proto3" json:"IntValue,omitempty"`
	// FloatValue 在属性值为 float 类型时设置。如果类型不是 float，该字段会被忽略。
	//
	// FloatValue is set if the property value is a float type. If the type is not a float, this field is ignored.
	//
	// Added: v1.18.30
	// Go type: float32
	FloatValue    float32 `protobuf:"fixed32,6,opt,name=FloatValue,proto3" json:"FloatValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMobProperty) Reset() {
	*x = ChangeMobProperty{}
	mi := &file_packet_change_mob_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMobProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMobProperty) ProtoMessage() {}

func (x *ChangeMobProperty) ProtoReflect() protoreflect.Message {
	mi := &file_packet_change_mob_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMobProperty.ProtoReflect.Descriptor instead.
func (*ChangeMobProperty) Descriptor() ([]byte, []int) {
	return file_packet_change_mob_property_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeMobProperty) GetEntityUniqueID() int64 {
	if x != nil {
		return x.EntityUniqueID
	}
	return 0
}

func (x *ChangeMobProperty) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *ChangeMobProperty) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *ChangeMobProperty) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ChangeMobProperty) GetIntValue() int32 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

func (x *ChangeMobProperty) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

var File_packet_change_mob_property_proto protoreflect.FileDescriptor

const file_packet_change_mob_property_proto_rawDesc = "" +
	"\n" +
	" packet/change_mob_property.proto\x129mousetunnel.minecraft.protocol.packet.change_mob_property\x1a\x14packet_options.proto\"\xda\x01\n" +
	"\x11ChangeMobProperty\x12&\n" +
	"\x0eEntityUniqueID\x18\x01 \x01(\x03R\x0eEntityUniqueID\x12\x1a\n" +
	"\bProperty\x18\x02 \x01(\tR\bProperty\x12\x1c\n" +
	"\tBoolValue\x18\x03 \x01(\bR\tBoolValue\x12 \n" +
	"\vStringValue\x18\x04 \x01(\tR\vStringValue\x12\x1a\n" +
	"\bIntValue\x18\x05 \x01(\x05R\bIntValue\x12\x1e\n" +
	"\n" +
	"FloatValue\x18\x06 \x01(\x02R\n" +
	"FloatValue:\x05\xc0\xc8\x05\xb4\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_change_mob_property_proto_rawDescOnce sync.Once
	file_packet_change_mob_property_proto_rawDescData []byte
)

func file_packet_change_mob_property_proto_rawDescGZIP() []byte {
	file_packet_change_mob_property_proto_rawDescOnce.Do(func() {
		file_packet_change_mob_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_change_mob_property_proto_rawDesc), len(file_packet_change_mob_property_proto_rawDesc)))
	})
	return file_packet_change_mob_property_proto_rawDescData
}

var file_packet_change_mob_property_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_change_mob_property_proto_goTypes = []any{
	(*ChangeMobProperty)(nil), // 0: mousetunnel.minecraft.protocol.packet.change_mob_property.ChangeMobProperty
}
var file_packet_change_mob_property_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_change_mob_property_proto_init() }
func file_packet_change_mob_property_proto_init() {
	if File_packet_change_mob_property_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_change_mob_property_proto_rawDesc), len(file_packet_change_mob_property_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_change_mob_property_proto_goTypes,
		DependencyIndexes: file_packet_change_mob_property_proto_depIdxs,
		MessageInfos:      file_packet_change_mob_property_proto_msgTypes,
	}.Build()
	File_packet_change_mob_property_proto = out.File
	file_packet_change_mob_property_proto_goTypes = nil
	file_packet_change_mob_property_proto_depIdxs = nil
}
