// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/client_start_item_cooldown.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientStartItemCooldown 由服务器发送给客户端，用于开始某个物品的冷却。
//
// ClientStartItemCooldown is sent by the server to the client to initiate a cooldown on an item.
//
// Added: v1.18.10
type ClientStartItemCooldown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category 是要开始冷却的物品类别。
	//
	// Category is the category of the item to start the cooldown on.
	//
	// Added: v1.18.10
	Category string `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	// Duration 是冷却应持续的 tick 数。
	//
	// Duration is the duration of ticks the cooldown should last.
	//
	// Added: v1.18.10
	Duration      int32 `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStartItemCooldown) Reset() {
	*x = ClientStartItemCooldown{}
	mi := &file_packet_client_start_item_cooldown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStartItemCooldown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStartItemCooldown) ProtoMessage() {}

func (x *ClientStartItemCooldown) ProtoReflect() protoreflect.Message {
	mi := &file_packet_client_start_item_cooldown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStartItemCooldown.ProtoReflect.Descriptor instead.
func (*ClientStartItemCooldown) Descriptor() ([]byte, []int) {
	return file_packet_client_start_item_cooldown_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStartItemCooldown) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClientStartItemCooldown) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_packet_client_start_item_cooldown_proto protoreflect.FileDescriptor

const file_packet_client_start_item_cooldown_proto_rawDesc = "" +
	"\n" +
	"'packet/client_start_item_cooldown.proto\x12@mousetunnel.minecraft.protocol.packet.client_start_item_cooldown\x1a\x14packet_options.proto\"X\n" +
	"\x17ClientStartItemCooldown\x12\x1a\n" +
	"\bCategory\x18\x01 \x01(\tR\bCategory\x12\x1a\n" +
	"\bDuration\x18\x02 \x01(\x05R\bDuration:\x05\xc0\xc8\x05\xb0\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_client_start_item_cooldown_proto_rawDescOnce sync.Once
	file_packet_client_start_item_cooldown_proto_rawDescData []byte
)

func file_packet_client_start_item_cooldown_proto_rawDescGZIP() []byte {
	file_packet_client_start_item_cooldown_proto_rawDescOnce.Do(func() {
		file_packet_client_start_item_cooldown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_client_start_item_cooldown_proto_rawDesc), len(file_packet_client_start_item_cooldown_proto_rawDesc)))
	})
	return file_packet_client_start_item_cooldown_proto_rawDescData
}

var file_packet_client_start_item_cooldown_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_client_start_item_cooldown_proto_goTypes = []any{
	(*ClientStartItemCooldown)(nil), // 0: mousetunnel.minecraft.protocol.packet.client_start_item_cooldown.ClientStartItemCooldown
}
var file_packet_client_start_item_cooldown_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_client_start_item_cooldown_proto_init() }
func file_packet_client_start_item_cooldown_proto_init() {
	if File_packet_client_start_item_cooldown_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_client_start_item_cooldown_proto_rawDesc), len(file_packet_client_start_item_cooldown_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_client_start_item_cooldown_proto_goTypes,
		DependencyIndexes: file_packet_client_start_item_cooldown_proto_depIdxs,
		MessageInfos:      file_packet_client_start_item_cooldown_proto_msgTypes,
	}.Build()
	File_packet_client_start_item_cooldown_proto = out.File
	file_packet_client_start_item_cooldown_proto_goTypes = nil
	file_packet_client_start_item_cooldown_proto_depIdxs = nil
}
