// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/code_builder_source.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodeBuilderOperationEnum int32

const (
	CodeBuilderOperationEnum_CodeBuilderOperationNone  CodeBuilderOperationEnum = 0
	CodeBuilderOperationEnum_CodeBuilderOperationGet   CodeBuilderOperationEnum = 1
	CodeBuilderOperationEnum_CodeBuilderOperationSet   CodeBuilderOperationEnum = 2
	CodeBuilderOperationEnum_CodeBuilderOperationReset CodeBuilderOperationEnum = 3
)

// Enum value maps for CodeBuilderOperationEnum.
var (
	CodeBuilderOperationEnum_name = map[int32]string{
		0: "CodeBuilderOperationNone",
		1: "CodeBuilderOperationGet",
		2: "CodeBuilderOperationSet",
		3: "CodeBuilderOperationReset",
	}
	CodeBuilderOperationEnum_value = map[string]int32{
		"CodeBuilderOperationNone":  0,
		"CodeBuilderOperationGet":   1,
		"CodeBuilderOperationSet":   2,
		"CodeBuilderOperationReset": 3,
	}
)

func (x CodeBuilderOperationEnum) Enum() *CodeBuilderOperationEnum {
	p := new(CodeBuilderOperationEnum)
	*p = x
	return p
}

func (x CodeBuilderOperationEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeBuilderOperationEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_code_builder_source_proto_enumTypes[0].Descriptor()
}

func (CodeBuilderOperationEnum) Type() protoreflect.EnumType {
	return &file_packet_code_builder_source_proto_enumTypes[0]
}

func (x CodeBuilderOperationEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeBuilderOperationEnum.Descriptor instead.
func (CodeBuilderOperationEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_code_builder_source_proto_rawDescGZIP(), []int{0}
}

type CodeBuilderCategoryEnum int32

const (
	CodeBuilderCategoryEnum_CodeBuilderCategoryNone          CodeBuilderCategoryEnum = 0
	CodeBuilderCategoryEnum_CodeBuilderCategoryStatus        CodeBuilderCategoryEnum = 1
	CodeBuilderCategoryEnum_CodeBuilderCategoryInstantiation CodeBuilderCategoryEnum = 2
)

// Enum value maps for CodeBuilderCategoryEnum.
var (
	CodeBuilderCategoryEnum_name = map[int32]string{
		0: "CodeBuilderCategoryNone",
		1: "CodeBuilderCategoryStatus",
		2: "CodeBuilderCategoryInstantiation",
	}
	CodeBuilderCategoryEnum_value = map[string]int32{
		"CodeBuilderCategoryNone":          0,
		"CodeBuilderCategoryStatus":        1,
		"CodeBuilderCategoryInstantiation": 2,
	}
)

func (x CodeBuilderCategoryEnum) Enum() *CodeBuilderCategoryEnum {
	p := new(CodeBuilderCategoryEnum)
	*p = x
	return p
}

func (x CodeBuilderCategoryEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeBuilderCategoryEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_code_builder_source_proto_enumTypes[1].Descriptor()
}

func (CodeBuilderCategoryEnum) Type() protoreflect.EnumType {
	return &file_packet_code_builder_source_proto_enumTypes[1]
}

func (x CodeBuilderCategoryEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeBuilderCategoryEnum.Descriptor instead.
func (CodeBuilderCategoryEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_code_builder_source_proto_rawDescGZIP(), []int{1}
}

type CodeBuilderStatusEnum int32

const (
	CodeBuilderStatusEnum_CodeBuilderStatusNone       CodeBuilderStatusEnum = 0
	CodeBuilderStatusEnum_CodeBuilderStatusNotStarted CodeBuilderStatusEnum = 1
	CodeBuilderStatusEnum_CodeBuilderStatusInProgress CodeBuilderStatusEnum = 2
	CodeBuilderStatusEnum_CodeBuilderStatusPaused     CodeBuilderStatusEnum = 3
	CodeBuilderStatusEnum_CodeBuilderStatusError      CodeBuilderStatusEnum = 4
	CodeBuilderStatusEnum_CodeBuilderStatusSucceeded  CodeBuilderStatusEnum = 5
)

// Enum value maps for CodeBuilderStatusEnum.
var (
	CodeBuilderStatusEnum_name = map[int32]string{
		0: "CodeBuilderStatusNone",
		1: "CodeBuilderStatusNotStarted",
		2: "CodeBuilderStatusInProgress",
		3: "CodeBuilderStatusPaused",
		4: "CodeBuilderStatusError",
		5: "CodeBuilderStatusSucceeded",
	}
	CodeBuilderStatusEnum_value = map[string]int32{
		"CodeBuilderStatusNone":       0,
		"CodeBuilderStatusNotStarted": 1,
		"CodeBuilderStatusInProgress": 2,
		"CodeBuilderStatusPaused":     3,
		"CodeBuilderStatusError":      4,
		"CodeBuilderStatusSucceeded":  5,
	}
)

func (x CodeBuilderStatusEnum) Enum() *CodeBuilderStatusEnum {
	p := new(CodeBuilderStatusEnum)
	*p = x
	return p
}

func (x CodeBuilderStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeBuilderStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_code_builder_source_proto_enumTypes[2].Descriptor()
}

func (CodeBuilderStatusEnum) Type() protoreflect.EnumType {
	return &file_packet_code_builder_source_proto_enumTypes[2]
}

func (x CodeBuilderStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeBuilderStatusEnum.Descriptor instead.
func (CodeBuilderStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_code_builder_source_proto_rawDescGZIP(), []int{2}
}

// CodeBuilderSource 是教育版数据包，由客户端发送给服务器，用于对 code builder 运行操作。
//
// CodeBuilderSource is an Education Edition packet sent by the client to the server to run an operation with a
// code builder.
//
// Added: v1.18.10
// Changed: v1.21.0, the Value payload field was replaced with the CodeStatus field.
type CodeBuilderSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation 用于区分执行的操作，它始终是上方列出的常量之一。
	//
	// Operation is used to distinguish the operation performed. It is always one of the constants listed above.
	//
	// Added: v1.18.10
	// Go type: byte
	Operation uint32 `protobuf:"varint,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	// Category 用于区分执行操作的类别，它始终是上方列出的常量之一。
	//
	// Category is used to distinguish the category of the operation performed. It is always one of the constants
	// listed above.
	//
	// Added: v1.18.10
	// Go type: byte
	Category uint32 `protobuf:"varint,2,opt,name=Category,proto3" json:"Category,omitempty"`
	// CodeStatus 是 code builder 的状态，它始终是上方列出的常量之一。
	//
	// CodeStatus is the status of the code builder. It is always one of the constants listed above.
	//
	// Added: v1.21.0
	// Go type: byte
	CodeStatus    uint32 `protobuf:"varint,3,opt,name=CodeStatus,proto3" json:"CodeStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeBuilderSource) Reset() {
	*x = CodeBuilderSource{}
	mi := &file_packet_code_builder_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeBuilderSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeBuilderSource) ProtoMessage() {}

func (x *CodeBuilderSource) ProtoReflect() protoreflect.Message {
	mi := &file_packet_code_builder_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeBuilderSource.ProtoReflect.Descriptor instead.
func (*CodeBuilderSource) Descriptor() ([]byte, []int) {
	return file_packet_code_builder_source_proto_rawDescGZIP(), []int{0}
}

func (x *CodeBuilderSource) GetOperation() uint32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *CodeBuilderSource) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *CodeBuilderSource) GetCodeStatus() uint32 {
	if x != nil {
		return x.CodeStatus
	}
	return 0
}

var File_packet_code_builder_source_proto protoreflect.FileDescriptor

const file_packet_code_builder_source_proto_rawDesc = "" +
	"\n" +
	" packet/code_builder_source.proto\x129mousetunnel.minecraft.protocol.packet.code_builder_source\x1a\x14packet_options.proto\"t\n" +
	"\x11CodeBuilderSource\x12\x1c\n" +
	"\tOperation\x18\x01 \x01(\rR\tOperation\x12\x1a\n" +
	"\bCategory\x18\x02 \x01(\rR\bCategory\x12\x1e\n" +
	"\n" +
	"CodeStatus\x18\x03 \x01(\rR\n" +
	"CodeStatus:\x05\xc0\xc8\x05\xb2\x01*\x91\x01\n" +
	"\x18CodeBuilderOperationEnum\x12\x1c\n" +
	"\x18CodeBuilderOperationNone\x10\x00\x12\x1b\n" +
	"\x17CodeBuilderOperationGet\x10\x01\x12\x1b\n" +
	"\x17CodeBuilderOperationSet\x10\x02\x12\x1d\n" +
	"\x19CodeBuilderOperationReset\x10\x03*{\n" +
	"\x17CodeBuilderCategoryEnum\x12\x1b\n" +
	"\x17CodeBuilderCategoryNone\x10\x00\x12\x1d\n" +
	"\x19CodeBuilderCategoryStatus\x10\x01\x12$\n" +
	" CodeBuilderCategoryInstantiation\x10\x02*\xcd\x01\n" +
	"\x15CodeBuilderStatusEnum\x12\x19\n" +
	"\x15CodeBuilderStatusNone\x10\x00\x12\x1f\n" +
	"\x1bCodeBuilderStatusNotStarted\x10\x01\x12\x1f\n" +
	"\x1bCodeBuilderStatusInProgress\x10\x02\x12\x1b\n" +
	"\x17CodeBuilderStatusPaused\x10\x03\x12\x1a\n" +
	"\x16CodeBuilderStatusError\x10\x04\x12\x1e\n" +
	"\x1aCodeBuilderStatusSucceeded\x10\x05BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_code_builder_source_proto_rawDescOnce sync.Once
	file_packet_code_builder_source_proto_rawDescData []byte
)

func file_packet_code_builder_source_proto_rawDescGZIP() []byte {
	file_packet_code_builder_source_proto_rawDescOnce.Do(func() {
		file_packet_code_builder_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_code_builder_source_proto_rawDesc), len(file_packet_code_builder_source_proto_rawDesc)))
	})
	return file_packet_code_builder_source_proto_rawDescData
}

var file_packet_code_builder_source_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_packet_code_builder_source_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_code_builder_source_proto_goTypes = []any{
	(CodeBuilderOperationEnum)(0), // 0: mousetunnel.minecraft.protocol.packet.code_builder_source.CodeBuilderOperationEnum
	(CodeBuilderCategoryEnum)(0),  // 1: mousetunnel.minecraft.protocol.packet.code_builder_source.CodeBuilderCategoryEnum
	(CodeBuilderStatusEnum)(0),    // 2: mousetunnel.minecraft.protocol.packet.code_builder_source.CodeBuilderStatusEnum
	(*CodeBuilderSource)(nil),     // 3: mousetunnel.minecraft.protocol.packet.code_builder_source.CodeBuilderSource
}
var file_packet_code_builder_source_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_code_builder_source_proto_init() }
func file_packet_code_builder_source_proto_init() {
	if File_packet_code_builder_source_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_code_builder_source_proto_rawDesc), len(file_packet_code_builder_source_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_code_builder_source_proto_goTypes,
		DependencyIndexes: file_packet_code_builder_source_proto_depIdxs,
		EnumInfos:         file_packet_code_builder_source_proto_enumTypes,
		MessageInfos:      file_packet_code_builder_source_proto_msgTypes,
	}.Build()
	File_packet_code_builder_source_proto = out.File
	file_packet_code_builder_source_proto_goTypes = nil
	file_packet_code_builder_source_proto_depIdxs = nil
}
