// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/container_open.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerOpen 由服务器发送，用于在客户端侧打开一个容器。该容器必须真实存在于世界中，
// 数据包才会生效。与 Java 版不同，基岩版要求箱子等容器必须存在且在范围内才能打开其物品栏。
//
// ContainerOpen is sent by the server to open a container client-side. This container must be physically
// present in the world, for the packet to have any effect. Unlike Java Edition, Bedrock Edition requires that
// chests for example must be present and in range to open its inventory.
//
// Added: v1.11.1
type ContainerOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WindowID 是正在打开窗口的 ID。之后可使用该 ID 通过 ContainerClose 数据包关闭容器。
	//
	// WindowID is the ID representing the window that is being opened. It may be used later to close the
	// container using a ContainerClose packet.
	//
	// Added: v1.11.1
	// Go type: byte
	WindowID uint32 `protobuf:"varint,1,opt,name=WindowID,proto3" json:"WindowID,omitempty"`
	// ContainerType 是在该数据包位置打开容器时容器的类型 ID。它取决于方块或实体，
	// 例如可以是箱子、漏斗的窗口类型，也可以是马的物品栏。
	//
	// ContainerType is the type ID of the container that is being opened when opening the container at the
	// position of the packet. It depends on the block/entity, and could, for example, be the window type of
	// a chest or a hopper, but also a horse inventory.
	//
	// Added: v1.11.1
	// Go type: byte
	ContainerType uint32 `protobuf:"varint,2,opt,name=ContainerType,proto3" json:"ContainerType,omitempty"`
	// ContainerPosition 是被打开容器的位置。该位置必须指向确实拥有容器的方块实体。
	// 如果不是这样，且没有同时提供有效的 ContainerEntityUniqueID，窗口不会打开，该数据包会被忽略。
	//
	// ContainerPosition is the position of the container opened. The position must point to a block entity
	// that actually has a container. If that is not the case, the window will not be opened and the packet
	// will be ignored, if a valid ContainerEntityUniqueID has not also been provided.
	//
	// Added: v1.11.1
	ContainerPosition *protocol.BlockPos `protobuf:"bytes,3,opt,name=ContainerPosition,proto3" json:"ContainerPosition,omitempty"`
	// ContainerEntityUniqueID 是被打开实体容器的唯一 ID。只有当 ContainerType 指向实体时才会使用，
	// 例如马。
	//
	// ContainerEntityUniqueID is the unique ID of the entity container that was opened. It is only used if
	// the ContainerType is one that points to an entity, for example a horse.
	//
	// Added: v1.11.1
	ContainerEntityUniqueID int64 `protobuf:"varint,4,opt,name=ContainerEntityUniqueID,proto3" json:"ContainerEntityUniqueID,omitempty"`
	// NetEaseUnknown1 是网易额外的容器打开字段。
	//
	// NetEaseUnknown1 is an extra NetEase container open field.
	//
	// Added: NetEase.
	NetEaseUnknown1 bool `protobuf:"varint,5,opt,name=NetEaseUnknown1,proto3" json:"NetEaseUnknown1,omitempty"`
	// NetEaseUnknown2 是网易额外的容器打开字段。
	//
	// NetEaseUnknown2 is an extra NetEase container open field.
	//
	// Added: NetEase.
	NetEaseUnknown2 string `protobuf:"bytes,6,opt,name=NetEaseUnknown2,proto3" json:"NetEaseUnknown2,omitempty"`
	// NetEaseUnknown3 是网易额外的容器打开字段。
	//
	// NetEaseUnknown3 is an extra NetEase container open field.
	//
	// Added: NetEase.
	NetEaseUnknown3 string `protobuf:"bytes,7,opt,name=NetEaseUnknown3,proto3" json:"NetEaseUnknown3,omitempty"`
	// NetEaseUnknown4 是网易额外的容器打开字段。
	//
	// NetEaseUnknown4 is an extra NetEase container open field.
	//
	// Added: NetEase.
	NetEaseUnknown4 bool `protobuf:"varint,8,opt,name=NetEaseUnknown4,proto3" json:"NetEaseUnknown4,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContainerOpen) Reset() {
	*x = ContainerOpen{}
	mi := &file_packet_container_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerOpen) ProtoMessage() {}

func (x *ContainerOpen) ProtoReflect() protoreflect.Message {
	mi := &file_packet_container_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerOpen.ProtoReflect.Descriptor instead.
func (*ContainerOpen) Descriptor() ([]byte, []int) {
	return file_packet_container_open_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerOpen) GetWindowID() uint32 {
	if x != nil {
		return x.WindowID
	}
	return 0
}

func (x *ContainerOpen) GetContainerType() uint32 {
	if x != nil {
		return x.ContainerType
	}
	return 0
}

func (x *ContainerOpen) GetContainerPosition() *protocol.BlockPos {
	if x != nil {
		return x.ContainerPosition
	}
	return nil
}

func (x *ContainerOpen) GetContainerEntityUniqueID() int64 {
	if x != nil {
		return x.ContainerEntityUniqueID
	}
	return 0
}

func (x *ContainerOpen) GetNetEaseUnknown1() bool {
	if x != nil {
		return x.NetEaseUnknown1
	}
	return false
}

func (x *ContainerOpen) GetNetEaseUnknown2() string {
	if x != nil {
		return x.NetEaseUnknown2
	}
	return ""
}

func (x *ContainerOpen) GetNetEaseUnknown3() string {
	if x != nil {
		return x.NetEaseUnknown3
	}
	return ""
}

func (x *ContainerOpen) GetNetEaseUnknown4() bool {
	if x != nil {
		return x.NetEaseUnknown4
	}
	return false
}

var File_packet_container_open_proto protoreflect.FileDescriptor

const file_packet_container_open_proto_rawDesc = "" +
	"\n" +
	"\x1bpacket/container_open.proto\x124mousetunnel.minecraft.protocol.packet.container_open\x1a\x0fblock_pos.proto\x1a\x14packet_options.proto\"\x9b\x03\n" +
	"\rContainerOpen\x12\x1a\n" +
	"\bWindowID\x18\x01 \x01(\rR\bWindowID\x12$\n" +
	"\rContainerType\x18\x02 \x01(\rR\rContainerType\x12`\n" +
	"\x11ContainerPosition\x18\x03 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\x11ContainerPosition\x128\n" +
	"\x17ContainerEntityUniqueID\x18\x04 \x01(\x03R\x17ContainerEntityUniqueID\x12(\n" +
	"\x0fNetEaseUnknown1\x18\x05 \x01(\bR\x0fNetEaseUnknown1\x12(\n" +
	"\x0fNetEaseUnknown2\x18\x06 \x01(\tR\x0fNetEaseUnknown2\x12(\n" +
	"\x0fNetEaseUnknown3\x18\a \x01(\tR\x0fNetEaseUnknown3\x12(\n" +
	"\x0fNetEaseUnknown4\x18\b \x01(\bR\x0fNetEaseUnknown4:\x04\xc0\xc8\x05.BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_container_open_proto_rawDescOnce sync.Once
	file_packet_container_open_proto_rawDescData []byte
)

func file_packet_container_open_proto_rawDescGZIP() []byte {
	file_packet_container_open_proto_rawDescOnce.Do(func() {
		file_packet_container_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_container_open_proto_rawDesc), len(file_packet_container_open_proto_rawDesc)))
	})
	return file_packet_container_open_proto_rawDescData
}

var file_packet_container_open_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_container_open_proto_goTypes = []any{
	(*ContainerOpen)(nil),     // 0: mousetunnel.minecraft.protocol.packet.container_open.ContainerOpen
	(*protocol.BlockPos)(nil), // 1: mousetunnel.minecraft.protocol.block_pos.BlockPos
}
var file_packet_container_open_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.container_open.ContainerOpen.ContainerPosition:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_container_open_proto_init() }
func file_packet_container_open_proto_init() {
	if File_packet_container_open_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_container_open_proto_rawDesc), len(file_packet_container_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_container_open_proto_goTypes,
		DependencyIndexes: file_packet_container_open_proto_depIdxs,
		MessageInfos:      file_packet_container_open_proto_msgTypes,
	}.Build()
	File_packet_container_open_proto = out.File
	file_packet_container_open_proto_goTypes = nil
	file_packet_container_open_proto_depIdxs = nil
}
