// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/crafting_data.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CraftingData 由服务器发送，用于让客户端知道服务器维护的所有合成数据。
// 这包括无序合成、工作台配方、熔炉配方等；每个合成站的配方都会包含在其中。
//
// CraftingData is sent by the server to let the client know all crafting data that the server maintains. This
// includes shapeless crafting, crafting table recipes, furnace recipes etc. Each crafting station's recipes
// are included in it.
//
// Added: v1.13
type CraftingData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipes 是服务器上所有可用配方的列表，其中包括无序、有序和熔炉配方等。
	// 客户端只能合成这些配方。
	//
	// Recipes is a list of all recipes available on the server. It includes among others shapeless, shaped
	// and furnace recipes. The client will only be able to craft these recipes.
	//
	// Added: v1.13
	// Go type: []protocol.Recipe
	Recipes []*protocol.Recipe `protobuf:"bytes,1,rep,name=Recipes,proto3" json:"Recipes,omitempty"`
	// PotionRecipes 是所有可在酿造台中使用的药水混合配方列表。
	//
	// PotionRecipes is a list of all potion mixing recipes which may be used in the brewing stand.
	//
	// Added: v1.13.0
	// Go type: []protocol.PotionRecipe
	PotionRecipes []*protocol.PotionRecipe `protobuf:"bytes,2,rep,name=PotionRecipes,proto3" json:"PotionRecipes,omitempty"`
	// PotionContainerChangeRecipes 是所有将药水从一种类型转换为另一种类型的配方列表，
	// 例如从可饮用药水转换为喷溅药水，或从喷溅药水转换为滞留药水。
	//
	// PotionContainerChangeRecipes is a list of all recipes to convert a potion from one type to another,
	// such as from a drinkable potion to a splash potion, or from a splash potion to a lingering potion.
	//
	// Added: v1.13.0
	// Go type: []protocol.PotionContainerChangeRecipe
	PotionContainerChangeRecipes []*protocol.PotionContainerChangeRecipe `protobuf:"bytes,3,rep,name=PotionContainerChangeRecipes,proto3" json:"PotionContainerChangeRecipes,omitempty"`
	// MaterialReducers 是教育版化学中使用的所有材料分解器列表。
	//
	// MaterialReducers is a list of all material reducers which is used in education edition chemistry.
	//
	// Added: v1.17.30
	// Go type: []protocol.MaterialReducer
	MaterialReducers []*protocol.MaterialReducer `protobuf:"bytes,4,rep,name=MaterialReducers,proto3" json:"MaterialReducers,omitempty"`
	// ClearRecipes 表示是否应清除客户端当前激活的所有配方。
	// 这样做意味着客户端自身不会再保留任何已激活配方：之前发送的所有 CraftingData 数据包也会被丢弃，
	// 只使用当前 CraftingData 数据包中的配方。
	//
	// ClearRecipes indicates if all recipes currently active on the client should be cleaned. Doing this
	// means that the client will have no recipes active by itself: Any CraftingData packets previously sent
	// will also be discarded, and only the recipes in this CraftingData packet will be used.
	//
	// Added: v1.13
	ClearRecipes bool `protobuf:"varint,5,opt,name=ClearRecipes,proto3" json:"ClearRecipes,omitempty"`
	// NetEaseUnknown1 是网易额外的合成数据。
	//
	// NetEaseUnknown1 is extra NetEase crafting data.
	//
	// Added: NetEase.
	// Go type: []byte
	NetEaseUnknown1 []byte `protobuf:"bytes,6,opt,name=NetEaseUnknown1,proto3" json:"NetEaseUnknown1,omitempty"`
	// NetEaseUnknown2 是网易额外的合成数据。
	//
	// NetEaseUnknown2 is extra NetEase crafting data.
	//
	// Added: NetEase.
	// Go type: []byte
	NetEaseUnknown2 []byte `protobuf:"bytes,7,opt,name=NetEaseUnknown2,proto3" json:"NetEaseUnknown2,omitempty"`
	// NetEaseUnknown3 是网易额外的合成数据。
	//
	// NetEaseUnknown3 is extra NetEase crafting data.
	//
	// Added: NetEase.
	// Go type: []byte
	NetEaseUnknown3 []byte `protobuf:"bytes,8,opt,name=NetEaseUnknown3,proto3" json:"NetEaseUnknown3,omitempty"`
	// NetEaseUnknown4 是网易额外的合成数据。
	//
	// NetEaseUnknown4 is extra NetEase crafting data.
	//
	// Added: NetEase.
	NetEaseUnknown4 string `protobuf:"bytes,9,opt,name=NetEaseUnknown4,proto3" json:"NetEaseUnknown4,omitempty"`
	// NetEaseUnknown5 是网易额外的合成数据。
	//
	// NetEaseUnknown5 is extra NetEase crafting data.
	//
	// Added: NetEase.
	NetEaseUnknown5 bool `protobuf:"varint,10,opt,name=NetEaseUnknown5,proto3" json:"NetEaseUnknown5,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CraftingData) Reset() {
	*x = CraftingData{}
	mi := &file_packet_crafting_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftingData) ProtoMessage() {}

func (x *CraftingData) ProtoReflect() protoreflect.Message {
	mi := &file_packet_crafting_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftingData.ProtoReflect.Descriptor instead.
func (*CraftingData) Descriptor() ([]byte, []int) {
	return file_packet_crafting_data_proto_rawDescGZIP(), []int{0}
}

func (x *CraftingData) GetRecipes() []*protocol.Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *CraftingData) GetPotionRecipes() []*protocol.PotionRecipe {
	if x != nil {
		return x.PotionRecipes
	}
	return nil
}

func (x *CraftingData) GetPotionContainerChangeRecipes() []*protocol.PotionContainerChangeRecipe {
	if x != nil {
		return x.PotionContainerChangeRecipes
	}
	return nil
}

func (x *CraftingData) GetMaterialReducers() []*protocol.MaterialReducer {
	if x != nil {
		return x.MaterialReducers
	}
	return nil
}

func (x *CraftingData) GetClearRecipes() bool {
	if x != nil {
		return x.ClearRecipes
	}
	return false
}

func (x *CraftingData) GetNetEaseUnknown1() []byte {
	if x != nil {
		return x.NetEaseUnknown1
	}
	return nil
}

func (x *CraftingData) GetNetEaseUnknown2() []byte {
	if x != nil {
		return x.NetEaseUnknown2
	}
	return nil
}

func (x *CraftingData) GetNetEaseUnknown3() []byte {
	if x != nil {
		return x.NetEaseUnknown3
	}
	return nil
}

func (x *CraftingData) GetNetEaseUnknown4() string {
	if x != nil {
		return x.NetEaseUnknown4
	}
	return ""
}

func (x *CraftingData) GetNetEaseUnknown5() bool {
	if x != nil {
		return x.NetEaseUnknown5
	}
	return false
}

var File_packet_crafting_data_proto protoreflect.FileDescriptor

const file_packet_crafting_data_proto_rawDesc = "" +
	"\n" +
	"\x1apacket/crafting_data.proto\x123mousetunnel.minecraft.protocol.packet.crafting_data\x1a\n" +
	"item.proto\x1a\x14packet_options.proto\x1a\frecipe.proto\"\x99\x05\n" +
	"\fCraftingData\x12G\n" +
	"\aRecipes\x18\x01 \x03(\v2-.mousetunnel.minecraft.protocol.recipe.RecipeR\aRecipes\x12Y\n" +
	"\rPotionRecipes\x18\x02 \x03(\v23.mousetunnel.minecraft.protocol.recipe.PotionRecipeR\rPotionRecipes\x12\x86\x01\n" +
	"\x1cPotionContainerChangeRecipes\x18\x03 \x03(\v2B.mousetunnel.minecraft.protocol.recipe.PotionContainerChangeRecipeR\x1cPotionContainerChangeRecipes\x12`\n" +
	"\x10MaterialReducers\x18\x04 \x03(\v24.mousetunnel.minecraft.protocol.item.MaterialReducerR\x10MaterialReducers\x12\"\n" +
	"\fClearRecipes\x18\x05 \x01(\bR\fClearRecipes\x12(\n" +
	"\x0fNetEaseUnknown1\x18\x06 \x01(\fR\x0fNetEaseUnknown1\x12(\n" +
	"\x0fNetEaseUnknown2\x18\a \x01(\fR\x0fNetEaseUnknown2\x12(\n" +
	"\x0fNetEaseUnknown3\x18\b \x01(\fR\x0fNetEaseUnknown3\x12(\n" +
	"\x0fNetEaseUnknown4\x18\t \x01(\tR\x0fNetEaseUnknown4\x12(\n" +
	"\x0fNetEaseUnknown5\x18\n" +
	" \x01(\bR\x0fNetEaseUnknown5:\x04\xc0\xc8\x054BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_crafting_data_proto_rawDescOnce sync.Once
	file_packet_crafting_data_proto_rawDescData []byte
)

func file_packet_crafting_data_proto_rawDescGZIP() []byte {
	file_packet_crafting_data_proto_rawDescOnce.Do(func() {
		file_packet_crafting_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_crafting_data_proto_rawDesc), len(file_packet_crafting_data_proto_rawDesc)))
	})
	return file_packet_crafting_data_proto_rawDescData
}

var file_packet_crafting_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_crafting_data_proto_goTypes = []any{
	(*CraftingData)(nil),                         // 0: mousetunnel.minecraft.protocol.packet.crafting_data.CraftingData
	(*protocol.Recipe)(nil),                      // 1: mousetunnel.minecraft.protocol.recipe.Recipe
	(*protocol.PotionRecipe)(nil),                // 2: mousetunnel.minecraft.protocol.recipe.PotionRecipe
	(*protocol.PotionContainerChangeRecipe)(nil), // 3: mousetunnel.minecraft.protocol.recipe.PotionContainerChangeRecipe
	(*protocol.MaterialReducer)(nil),             // 4: mousetunnel.minecraft.protocol.item.MaterialReducer
}
var file_packet_crafting_data_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.crafting_data.CraftingData.Recipes:type_name -> mousetunnel.minecraft.protocol.recipe.Recipe
	2, // 1: mousetunnel.minecraft.protocol.packet.crafting_data.CraftingData.PotionRecipes:type_name -> mousetunnel.minecraft.protocol.recipe.PotionRecipe
	3, // 2: mousetunnel.minecraft.protocol.packet.crafting_data.CraftingData.PotionContainerChangeRecipes:type_name -> mousetunnel.minecraft.protocol.recipe.PotionContainerChangeRecipe
	4, // 3: mousetunnel.minecraft.protocol.packet.crafting_data.CraftingData.MaterialReducers:type_name -> mousetunnel.minecraft.protocol.item.MaterialReducer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packet_crafting_data_proto_init() }
func file_packet_crafting_data_proto_init() {
	if File_packet_crafting_data_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_crafting_data_proto_rawDesc), len(file_packet_crafting_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_crafting_data_proto_goTypes,
		DependencyIndexes: file_packet_crafting_data_proto_depIdxs,
		MessageInfos:      file_packet_crafting_data_proto_msgTypes,
	}.Build()
	File_packet_crafting_data_proto = out.File
	file_packet_crafting_data_proto_goTypes = nil
	file_packet_crafting_data_proto_depIdxs = nil
}
