// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/dimension_data.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DimensionData 是服务器发送给客户端的数据包，包含服务器可能已注册的数据驱动维度信息。
// 该数据包默认似乎不会发送，通常只在注册了数据驱动维度时发送。
//
// DimensionData is a packet sent from the server to the client containing information about data-driven dimensions
// that the server may have registered. This packet does not seem to be sent by default, rather only being sent when
// any data-driven dimensions are registered.
//
// Added: v1.18.30
type DimensionData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Definitions 包含服务器上注册的数据驱动维度定义列表。
	//
	// Definitions contain a list of data-driven dimension definitions registered on the server.
	//
	// Added: v1.18.30
	// Go type: []protocol.DimensionDefinition
	Definitions   []*protocol.DimensionDefinition `protobuf:"bytes,1,rep,name=Definitions,proto3" json:"Definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionData) Reset() {
	*x = DimensionData{}
	mi := &file_packet_dimension_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionData) ProtoMessage() {}

func (x *DimensionData) ProtoReflect() protoreflect.Message {
	mi := &file_packet_dimension_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionData.ProtoReflect.Descriptor instead.
func (*DimensionData) Descriptor() ([]byte, []int) {
	return file_packet_dimension_data_proto_rawDescGZIP(), []int{0}
}

func (x *DimensionData) GetDefinitions() []*protocol.DimensionDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

var File_packet_dimension_data_proto protoreflect.FileDescriptor

const file_packet_dimension_data_proto_rawDesc = "" +
	"\n" +
	"\x1bpacket/dimension_data.proto\x124mousetunnel.minecraft.protocol.packet.dimension_data\x1a\x14packet_options.proto\x1a\vworld.proto\"s\n" +
	"\rDimensionData\x12[\n" +
	"\vDefinitions\x18\x01 \x03(\v29.mousetunnel.minecraft.protocol.world.DimensionDefinitionR\vDefinitions:\x05\xc0\xc8\x05\xb5\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_dimension_data_proto_rawDescOnce sync.Once
	file_packet_dimension_data_proto_rawDescData []byte
)

func file_packet_dimension_data_proto_rawDescGZIP() []byte {
	file_packet_dimension_data_proto_rawDescOnce.Do(func() {
		file_packet_dimension_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_dimension_data_proto_rawDesc), len(file_packet_dimension_data_proto_rawDesc)))
	})
	return file_packet_dimension_data_proto_rawDescData
}

var file_packet_dimension_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_dimension_data_proto_goTypes = []any{
	(*DimensionData)(nil),                // 0: mousetunnel.minecraft.protocol.packet.dimension_data.DimensionData
	(*protocol.DimensionDefinition)(nil), // 1: mousetunnel.minecraft.protocol.world.DimensionDefinition
}
var file_packet_dimension_data_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.dimension_data.DimensionData.Definitions:type_name -> mousetunnel.minecraft.protocol.world.DimensionDefinition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_dimension_data_proto_init() }
func file_packet_dimension_data_proto_init() {
	if File_packet_dimension_data_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_dimension_data_proto_rawDesc), len(file_packet_dimension_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_dimension_data_proto_goTypes,
		DependencyIndexes: file_packet_dimension_data_proto_depIdxs,
		MessageInfos:      file_packet_dimension_data_proto_msgTypes,
	}.Build()
	File_packet_dimension_data_proto = out.File
	file_packet_dimension_data_proto_goTypes = nil
	file_packet_dimension_data_proto_depIdxs = nil
}
