// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/item_registry.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemRegistry 由服务器发送，用于向客户端发送可用物品列表，并为自定义物品附加客户端侧组件。
// 该数据包在 1.21.60 前名为 ItemComponent，当时不包含物品定义，只包含组件。
//
// ItemRegistry is sent by the server to send the client a list of available items and attach client-side
// components to a custom item. This packet was formerly known as the ItemComponent packet before 1.21.60,
// which did not include item definitions but only the components.
//
// Added: v1.16.100
// Changed: v1.21.60, renamed from ItemComponent and expanded to include item definitions.
type ItemRegistry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Items 是游戏中所有可用物品及其旧版 ID 的列表。漏发游戏中存在的任何物品都会导致移动端客户端崩溃。
	// 任何自定义组件也会附加到该列表中的物品上。
	//
	// Items is a list of all items with their legacy IDs which are available in the game. Failing to send any
	// of the items that are in the game will crash mobile clients. Any custom components are also attached to
	// the items in this list.
	//
	// Added: v1.16.100
	// Changed: v1.21.60, expanded from component data to full item entries with runtime IDs and versions.
	// Go type: []protocol.ItemEntry
	Items         []*protocol.ItemEntry `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRegistry) Reset() {
	*x = ItemRegistry{}
	mi := &file_packet_item_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRegistry) ProtoMessage() {}

func (x *ItemRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_packet_item_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRegistry.ProtoReflect.Descriptor instead.
func (*ItemRegistry) Descriptor() ([]byte, []int) {
	return file_packet_item_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRegistry) GetItems() []*protocol.ItemEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_packet_item_registry_proto protoreflect.FileDescriptor

const file_packet_item_registry_proto_rawDesc = "" +
	"\n" +
	"\x1apacket/item_registry.proto\x123mousetunnel.minecraft.protocol.packet.item_registry\x1a\n" +
	"item.proto\x1a\x14packet_options.proto\"[\n" +
	"\fItemRegistry\x12D\n" +
	"\x05Items\x18\x01 \x03(\v2..mousetunnel.minecraft.protocol.item.ItemEntryR\x05Items:\x05\xc0\xc8\x05\xa2\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_item_registry_proto_rawDescOnce sync.Once
	file_packet_item_registry_proto_rawDescData []byte
)

func file_packet_item_registry_proto_rawDescGZIP() []byte {
	file_packet_item_registry_proto_rawDescOnce.Do(func() {
		file_packet_item_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_item_registry_proto_rawDesc), len(file_packet_item_registry_proto_rawDesc)))
	})
	return file_packet_item_registry_proto_rawDescData
}

var file_packet_item_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_item_registry_proto_goTypes = []any{
	(*ItemRegistry)(nil),       // 0: mousetunnel.minecraft.protocol.packet.item_registry.ItemRegistry
	(*protocol.ItemEntry)(nil), // 1: mousetunnel.minecraft.protocol.item.ItemEntry
}
var file_packet_item_registry_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.item_registry.ItemRegistry.Items:type_name -> mousetunnel.minecraft.protocol.item.ItemEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_item_registry_proto_init() }
func file_packet_item_registry_proto_init() {
	if File_packet_item_registry_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_item_registry_proto_rawDesc), len(file_packet_item_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_item_registry_proto_goTypes,
		DependencyIndexes: file_packet_item_registry_proto_depIdxs,
		MessageInfos:      file_packet_item_registry_proto_msgTypes,
	}.Build()
	File_packet_item_registry_proto = out.File
	file_packet_item_registry_proto_goTypes = nil
	file_packet_item_registry_proto_depIdxs = nil
}
