// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/item_frame_drop_item.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemFrameDropItem 由客户端在从物品展示框中掉落物品时发送。
//
// ItemFrameDropItem is sent by the client when it drops an item from an item frame.
//
// Added: v1.11.1
type ItemFrameDropItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position 是物品展示框的位置。
	//
	// Position is the position of the item frame.
	//
	// Added: v1.11.1
	Position      *protocol.BlockPos `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemFrameDropItem) Reset() {
	*x = ItemFrameDropItem{}
	mi := &file_packet_item_frame_drop_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemFrameDropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemFrameDropItem) ProtoMessage() {}

func (x *ItemFrameDropItem) ProtoReflect() protoreflect.Message {
	mi := &file_packet_item_frame_drop_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemFrameDropItem.ProtoReflect.Descriptor instead.
func (*ItemFrameDropItem) Descriptor() ([]byte, []int) {
	return file_packet_item_frame_drop_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemFrameDropItem) GetPosition() *protocol.BlockPos {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_packet_item_frame_drop_item_proto protoreflect.FileDescriptor

const file_packet_item_frame_drop_item_proto_rawDesc = "" +
	"\n" +
	"!packet/item_frame_drop_item.proto\x12:mousetunnel.minecraft.protocol.packet.item_frame_drop_item\x1a\x0fblock_pos.proto\x1a\x14packet_options.proto\"i\n" +
	"\x11ItemFrameDropItem\x12N\n" +
	"\bPosition\x18\x01 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\bPosition:\x04\xc0\xc8\x05GBPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_item_frame_drop_item_proto_rawDescOnce sync.Once
	file_packet_item_frame_drop_item_proto_rawDescData []byte
)

func file_packet_item_frame_drop_item_proto_rawDescGZIP() []byte {
	file_packet_item_frame_drop_item_proto_rawDescOnce.Do(func() {
		file_packet_item_frame_drop_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_item_frame_drop_item_proto_rawDesc), len(file_packet_item_frame_drop_item_proto_rawDesc)))
	})
	return file_packet_item_frame_drop_item_proto_rawDescData
}

var file_packet_item_frame_drop_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_item_frame_drop_item_proto_goTypes = []any{
	(*ItemFrameDropItem)(nil), // 0: mousetunnel.minecraft.protocol.packet.item_frame_drop_item.ItemFrameDropItem
	(*protocol.BlockPos)(nil), // 1: mousetunnel.minecraft.protocol.block_pos.BlockPos
}
var file_packet_item_frame_drop_item_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.item_frame_drop_item.ItemFrameDropItem.Position:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_item_frame_drop_item_proto_init() }
func file_packet_item_frame_drop_item_proto_init() {
	if File_packet_item_frame_drop_item_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_item_frame_drop_item_proto_rawDesc), len(file_packet_item_frame_drop_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_item_frame_drop_item_proto_goTypes,
		DependencyIndexes: file_packet_item_frame_drop_item_proto_depIdxs,
		MessageInfos:      file_packet_item_frame_drop_item_proto_msgTypes,
	}.Build()
	File_packet_item_frame_drop_item_proto = out.File
	file_packet_item_frame_drop_item_proto_goTypes = nil
	file_packet_item_frame_drop_item_proto_depIdxs = nil
}
