// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/level_event_generic.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LevelEventGeneric 由服务器发送，用于向客户端发送“通用”世界事件。
// 该数据包发送一个 NBT 序列化对象，因此可用于携带额外数据的任意事件。
//
// LevelEventGeneric is sent by the server to send a 'generic' level event to the client. This packet sends an
// NBT serialised object and may for that reason be used for any event holding additional data.
//
// Added: v1.12
type LevelEventGeneric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EventID 是标识所调用事件的唯一标识符。后续数据中的 NBT 字段会随事件类型而变化。
	//
	// EventID is a unique identifier that identifies the event called. The data that follows has fields in
	// the NBT depending on what event it is.
	//
	// Added: v1.12
	EventID int32 `protobuf:"varint,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	// SerialisedEventData 是网络小端格式的事件数据序列化对象，字段会随 EventID 而变化。
	// 与许多其他 NBT 结构不同，这些数据实际上不是复合标签，而是松散的 NBT 标签。
	// 如果要使用 nbt 包解码，需要在开头附加 0x0a00（复合标签 ID 和名称长度），并在结尾添加 0x00，
	// 手动把它包成复合标签。编码时同样需要移除这些字节。
	// 下方是 EventID 为 2026 时得到的数据示例：
	//
	// SerialisedEventData is a network little endian serialised object of event data, with fields that vary
	// depending on EventID.
	// Unlike many other NBT structures, this data is not actually in a compound but just loosely floating
	// NBT tags. To decode using the nbt package, you would need to append 0x0a00 at the start (compound id
	// and name length) and add 0x00 at the end, to manually wrap it in a compound. Likewise, you would have
	// to remove these bytes when encoding.
	// Example of the resulting data with an EventID of 2026:
	//
	//	TAG_Compound({
	//	   'pos15x': TAG_Float(198),
	//	   'pos11x': TAG_Float(201),
	//	   'pos6y': TAG_Float(65),
	//	   'pos13y': TAG_Float(64),
	//	   'pos17z': TAG_Float(36),
	//	   'pos8y': TAG_Float(65),
	//	   'originY': TAG_Float(65.06125),
	//	   'pos10z': TAG_Float(37),
	//	   'pos13x': TAG_Float(201),
	//	   'pos7y': TAG_Float(65),
	//	   'pos9x': TAG_Float(203),
	//	   'pos11y': TAG_Float(64),
	//	   'pos15y': TAG_Float(65),
	//	   'pos15z': TAG_Float(40),
	//	   'pos7z': TAG_Float(41),
	//	   'pos8x': TAG_Float(198),
	//	   'pos13z': TAG_Float(40),
	//	   'pos1z': TAG_Float(37),
	//	   'pos6z': TAG_Float(42),
	//	   'size': TAG_Int(18),
	//	   'pos0x': TAG_Float(204),
	//	   'pos12x': TAG_Float(200),
	//	   'pos2x': TAG_Float(204),
	//	   'pos9z': TAG_Float(37),
	//	   'pos16y': TAG_Float(64),
	//	   'pos5x': TAG_Float(204),
	//	   'pos5y': TAG_Float(64),
	//	   'pos17x': TAG_Float(202),
	//	   'pos3y': TAG_Float(64),
	//	   'pos3z': TAG_Float(36),
	//	   'radius': TAG_Float(4),
	//	   'pos0z': TAG_Float(38),
	//	   'pos4z': TAG_Float(36),
	//	   'pos8z': TAG_Float(38),
	//	   'pos1x': TAG_Float(204),
	//	   'pos0y': TAG_Float(64),
	//	   'pos14z': TAG_Float(39),
	//	   'pos16z': TAG_Float(40),
	//	   'pos2y': TAG_Float(63),
	//	   'pos6x': TAG_Float(203),
	//	   'pos10x': TAG_Float(205),
	//	   'pos12y': TAG_Float(64),
	//	   'pos1y': TAG_Float(64),
	//	   'pos14x': TAG_Float(200),
	//	   'pos3x': TAG_Float(204),
	//	   'pos9y': TAG_Float(64),
	//	   'pos4y': TAG_Float(63),
	//	   'pos10y': TAG_Float(63),
	//	   'pos12z': TAG_Float(38),
	//	   'pos16x': TAG_Float(202),
	//	   'originX': TAG_Float(202.48654),
	//	   'pos14y': TAG_Float(62),
	//	   'pos17y': TAG_Float(62),
	//	   'pos5z': TAG_Float(35),
	//	   'pos4x': TAG_Float(204),
	//	   'pos7x': TAG_Float(203),
	//	   'originZ': TAG_Float(38.297028),
	//	   'pos11z': TAG_Float(38),
	//	   'pos2z': TAG_Float(39),
	//	})
	//
	// The 'originX', 'originY' and 'originZ' fields are present in every event and serve as a replacement for
	// a Position field in this packet.
	//
	// Added: v1.12
	// Go type: []byte
	SerialisedEventData []byte `protobuf:"bytes,2,opt,name=SerialisedEventData,proto3" json:"SerialisedEventData,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LevelEventGeneric) Reset() {
	*x = LevelEventGeneric{}
	mi := &file_packet_level_event_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelEventGeneric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelEventGeneric) ProtoMessage() {}

func (x *LevelEventGeneric) ProtoReflect() protoreflect.Message {
	mi := &file_packet_level_event_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelEventGeneric.ProtoReflect.Descriptor instead.
func (*LevelEventGeneric) Descriptor() ([]byte, []int) {
	return file_packet_level_event_generic_proto_rawDescGZIP(), []int{0}
}

func (x *LevelEventGeneric) GetEventID() int32 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *LevelEventGeneric) GetSerialisedEventData() []byte {
	if x != nil {
		return x.SerialisedEventData
	}
	return nil
}

var File_packet_level_event_generic_proto protoreflect.FileDescriptor

const file_packet_level_event_generic_proto_rawDesc = "" +
	"\n" +
	" packet/level_event_generic.proto\x129mousetunnel.minecraft.protocol.packet.level_event_generic\x1a\x14packet_options.proto\"e\n" +
	"\x11LevelEventGeneric\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\x05R\aEventID\x120\n" +
	"\x13SerialisedEventData\x18\x02 \x01(\fR\x13SerialisedEventData:\x04\xc0\xc8\x05|BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_level_event_generic_proto_rawDescOnce sync.Once
	file_packet_level_event_generic_proto_rawDescData []byte
)

func file_packet_level_event_generic_proto_rawDescGZIP() []byte {
	file_packet_level_event_generic_proto_rawDescOnce.Do(func() {
		file_packet_level_event_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_level_event_generic_proto_rawDesc), len(file_packet_level_event_generic_proto_rawDesc)))
	})
	return file_packet_level_event_generic_proto_rawDescData
}

var file_packet_level_event_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_level_event_generic_proto_goTypes = []any{
	(*LevelEventGeneric)(nil), // 0: mousetunnel.minecraft.protocol.packet.level_event_generic.LevelEventGeneric
}
var file_packet_level_event_generic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_level_event_generic_proto_init() }
func file_packet_level_event_generic_proto_init() {
	if File_packet_level_event_generic_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_level_event_generic_proto_rawDesc), len(file_packet_level_event_generic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_level_event_generic_proto_goTypes,
		DependencyIndexes: file_packet_level_event_generic_proto_depIdxs,
		MessageInfos:      file_packet_level_event_generic_proto_msgTypes,
	}.Build()
	File_packet_level_event_generic_proto = out.File
	file_packet_level_event_generic_proto_goTypes = nil
	file_packet_level_event_generic_proto_depIdxs = nil
}
