// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/multi_player_settings.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiPlayerSettingsEnum int32

const (
	MultiPlayerSettingsEnum_EnableMultiPlayer  MultiPlayerSettingsEnum = 0
	MultiPlayerSettingsEnum_DisableMultiPlayer MultiPlayerSettingsEnum = 1
	MultiPlayerSettingsEnum_RefreshJoinCode    MultiPlayerSettingsEnum = 2
)

// Enum value maps for MultiPlayerSettingsEnum.
var (
	MultiPlayerSettingsEnum_name = map[int32]string{
		0: "EnableMultiPlayer",
		1: "DisableMultiPlayer",
		2: "RefreshJoinCode",
	}
	MultiPlayerSettingsEnum_value = map[string]int32{
		"EnableMultiPlayer":  0,
		"DisableMultiPlayer": 1,
		"RefreshJoinCode":    2,
	}
)

func (x MultiPlayerSettingsEnum) Enum() *MultiPlayerSettingsEnum {
	p := new(MultiPlayerSettingsEnum)
	*p = x
	return p
}

func (x MultiPlayerSettingsEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultiPlayerSettingsEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_multi_player_settings_proto_enumTypes[0].Descriptor()
}

func (MultiPlayerSettingsEnum) Type() protoreflect.EnumType {
	return &file_packet_multi_player_settings_proto_enumTypes[0]
}

func (x MultiPlayerSettingsEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultiPlayerSettingsEnum.Descriptor instead.
func (MultiPlayerSettingsEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_multi_player_settings_proto_rawDescGZIP(), []int{0}
}

// MultiPlayerSettings 由客户端发送，用于更新服务器侧多人游戏相关设置，并由服务器回发给在线玩家。
// MultiPlayerSettings 是 Minecraft: Education Edition 数据包，对基础游戏没有功能。
//
// MultiPlayerSettings is sent by the client to update multi-player related settings server-side and sent back
// to online players by the server.
// The MultiPlayerSettings packet is a Minecraft: Education Edition packet. It has no functionality for the
// base game.
//
// Added: v1.13
type MultiPlayerSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ActionType 是发送该数据包时应执行的操作，为上方常量之一。
	//
	// ActionType is the action that should be done when this packet is sent. It is one of the constants that
	// may be found above.
	//
	// Added: v1.13
	ActionType    int32 `protobuf:"varint,1,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPlayerSettings) Reset() {
	*x = MultiPlayerSettings{}
	mi := &file_packet_multi_player_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPlayerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPlayerSettings) ProtoMessage() {}

func (x *MultiPlayerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_packet_multi_player_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPlayerSettings.ProtoReflect.Descriptor instead.
func (*MultiPlayerSettings) Descriptor() ([]byte, []int) {
	return file_packet_multi_player_settings_proto_rawDescGZIP(), []int{0}
}

func (x *MultiPlayerSettings) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

var File_packet_multi_player_settings_proto protoreflect.FileDescriptor

const file_packet_multi_player_settings_proto_rawDesc = "" +
	"\n" +
	"\"packet/multi_player_settings.proto\x12;mousetunnel.minecraft.protocol.packet.multi_player_settings\x1a\x14packet_options.proto\"<\n" +
	"\x13MultiPlayerSettings\x12\x1e\n" +
	"\n" +
	"ActionType\x18\x01 \x01(\x05R\n" +
	"ActionType:\x05\xc0\xc8\x05\x8b\x01*]\n" +
	"\x17MultiPlayerSettingsEnum\x12\x15\n" +
	"\x11EnableMultiPlayer\x10\x00\x12\x16\n" +
	"\x12DisableMultiPlayer\x10\x01\x12\x13\n" +
	"\x0fRefreshJoinCode\x10\x02BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_multi_player_settings_proto_rawDescOnce sync.Once
	file_packet_multi_player_settings_proto_rawDescData []byte
)

func file_packet_multi_player_settings_proto_rawDescGZIP() []byte {
	file_packet_multi_player_settings_proto_rawDescOnce.Do(func() {
		file_packet_multi_player_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_multi_player_settings_proto_rawDesc), len(file_packet_multi_player_settings_proto_rawDesc)))
	})
	return file_packet_multi_player_settings_proto_rawDescData
}

var file_packet_multi_player_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_multi_player_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_multi_player_settings_proto_goTypes = []any{
	(MultiPlayerSettingsEnum)(0), // 0: mousetunnel.minecraft.protocol.packet.multi_player_settings.MultiPlayerSettingsEnum
	(*MultiPlayerSettings)(nil),  // 1: mousetunnel.minecraft.protocol.packet.multi_player_settings.MultiPlayerSettings
}
var file_packet_multi_player_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_multi_player_settings_proto_init() }
func file_packet_multi_player_settings_proto_init() {
	if File_packet_multi_player_settings_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_multi_player_settings_proto_rawDesc), len(file_packet_multi_player_settings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_multi_player_settings_proto_goTypes,
		DependencyIndexes: file_packet_multi_player_settings_proto_depIdxs,
		EnumInfos:         file_packet_multi_player_settings_proto_enumTypes,
		MessageInfos:      file_packet_multi_player_settings_proto_msgTypes,
	}.Build()
	File_packet_multi_player_settings_proto = out.File
	file_packet_multi_player_settings_proto_goTypes = nil
	file_packet_multi_player_settings_proto_depIdxs = nil
}
