// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/open_sign.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenSign 由服务器发送，用于打开告示牌编辑界面。
//
// OpenSign is sent by the server to open a sign for editing.
//
// Added: v1.19.80
// 自 1.19.80 起，玩家可以与告示牌交互并编辑正反两面的文本，而不再只限于正面。
//
// As of 1.19.80, the player can interact with a sign to edit the text on both sides instead of just the front.
type OpenSign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position 是要编辑的告示牌位置。客户端会使用该位置获取告示牌数据，
	// 包括现有文本和格式等信息。
	//
	// Position is the position of the sign to edit. The client uses this position to get the data of the sign, including
	// the existing text and formatting etc.
	//
	// Added: v1.19.80
	Position *protocol.BlockPos `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	// FrontSide 指定是否打开告示牌正面进行编辑。为 false 时，默认编辑背面。
	//
	// FrontSide dictates whether the front side of the sign should be opened for editing. If false, the back side is
	// assumed to be edited.
	//
	// Added: v1.19.80
	FrontSide     bool `protobuf:"varint,2,opt,name=FrontSide,proto3" json:"FrontSide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSign) Reset() {
	*x = OpenSign{}
	mi := &file_packet_open_sign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSign) ProtoMessage() {}

func (x *OpenSign) ProtoReflect() protoreflect.Message {
	mi := &file_packet_open_sign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSign.ProtoReflect.Descriptor instead.
func (*OpenSign) Descriptor() ([]byte, []int) {
	return file_packet_open_sign_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSign) GetPosition() *protocol.BlockPos {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *OpenSign) GetFrontSide() bool {
	if x != nil {
		return x.FrontSide
	}
	return false
}

var File_packet_open_sign_proto protoreflect.FileDescriptor

const file_packet_open_sign_proto_rawDesc = "" +
	"\n" +
	"\x16packet/open_sign.proto\x12/mousetunnel.minecraft.protocol.packet.open_sign\x1a\x0fblock_pos.proto\x1a\x14packet_options.proto\"\x7f\n" +
	"\bOpenSign\x12N\n" +
	"\bPosition\x18\x01 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\bPosition\x12\x1c\n" +
	"\tFrontSide\x18\x02 \x01(\bR\tFrontSide:\x05\xc0\xc8\x05\xaf\x02BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_open_sign_proto_rawDescOnce sync.Once
	file_packet_open_sign_proto_rawDescData []byte
)

func file_packet_open_sign_proto_rawDescGZIP() []byte {
	file_packet_open_sign_proto_rawDescOnce.Do(func() {
		file_packet_open_sign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_open_sign_proto_rawDesc), len(file_packet_open_sign_proto_rawDesc)))
	})
	return file_packet_open_sign_proto_rawDescData
}

var file_packet_open_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_open_sign_proto_goTypes = []any{
	(*OpenSign)(nil),          // 0: mousetunnel.minecraft.protocol.packet.open_sign.OpenSign
	(*protocol.BlockPos)(nil), // 1: mousetunnel.minecraft.protocol.block_pos.BlockPos
}
var file_packet_open_sign_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.open_sign.OpenSign.Position:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_open_sign_proto_init() }
func file_packet_open_sign_proto_init() {
	if File_packet_open_sign_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_open_sign_proto_rawDesc), len(file_packet_open_sign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_open_sign_proto_goTypes,
		DependencyIndexes: file_packet_open_sign_proto_depIdxs,
		MessageInfos:      file_packet_open_sign_proto_msgTypes,
	}.Build()
	File_packet_open_sign_proto = out.File
	file_packet_open_sign_proto_goTypes = nil
	file_packet_open_sign_proto_depIdxs = nil
}
