// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/player_location.proto

package packet

import (
	mgl32 "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/mgl32"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerLocationTypeEnum int32

const (
	PlayerLocationTypeEnum_PlayerLocationTypeCoordinates PlayerLocationTypeEnum = 0
	PlayerLocationTypeEnum_PlayerLocationTypeHide        PlayerLocationTypeEnum = 1
)

// Enum value maps for PlayerLocationTypeEnum.
var (
	PlayerLocationTypeEnum_name = map[int32]string{
		0: "PlayerLocationTypeCoordinates",
		1: "PlayerLocationTypeHide",
	}
	PlayerLocationTypeEnum_value = map[string]int32{
		"PlayerLocationTypeCoordinates": 0,
		"PlayerLocationTypeHide":        1,
	}
)

func (x PlayerLocationTypeEnum) Enum() *PlayerLocationTypeEnum {
	p := new(PlayerLocationTypeEnum)
	*p = x
	return p
}

func (x PlayerLocationTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerLocationTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_player_location_proto_enumTypes[0].Descriptor()
}

func (PlayerLocationTypeEnum) Type() protoreflect.EnumType {
	return &file_packet_player_location_proto_enumTypes[0]
}

func (x PlayerLocationTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerLocationTypeEnum.Descriptor instead.
func (PlayerLocationTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_player_location_proto_rawDescGZIP(), []int{0}
}

// PlayerLocation 由服务器发送给客户端，用于更新玩家在定位栏上的位置，或将其完全移除。
// 客户端会根据自己到 Position 的距离决定如何在定位栏上渲染该玩家。
//
// PlayerLocation is sent by the server to the client to either update a player's position on the locator bar,
// or remove them completely. The client will determine how to render the player on the locator bar based on
// their own distance to Position.
//
// Added: v1.21.80
type PlayerLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type 是正在执行的操作，它是上方常量之一。
	//
	// Type is the action that is being performed. It is one of the constants above.
	//
	// Added: v1.21.80
	Type int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// EntityUniqueID 是实体的唯一 ID。唯一 ID 会在同一世界的不同会话之间保持一致。
	//
	// EntityUniqueID is the unique ID of the entity. The unique ID is a value that remains consistent across
	// different sessions of the same world.
	//
	// Added: v1.21.80
	EntityUniqueID int64 `protobuf:"varint,2,opt,name=EntityUniqueID,proto3" json:"EntityUniqueID,omitempty"`
	// Position 是定位栏上使用的玩家位置。仅当 Type 为 PlayerLocationTypeCoordinates 时才会设置。
	//
	// Position is the position of the player to be used on the locator bar. This is only set when the Type is
	// PlayerLocationTypeCoordinates.
	//
	// Added: v1.21.80
	// Go type: mgl32.Vec3
	Position      *mgl32.Vec3 `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLocation) Reset() {
	*x = PlayerLocation{}
	mi := &file_packet_player_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLocation) ProtoMessage() {}

func (x *PlayerLocation) ProtoReflect() protoreflect.Message {
	mi := &file_packet_player_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLocation.ProtoReflect.Descriptor instead.
func (*PlayerLocation) Descriptor() ([]byte, []int) {
	return file_packet_player_location_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerLocation) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PlayerLocation) GetEntityUniqueID() int64 {
	if x != nil {
		return x.EntityUniqueID
	}
	return 0
}

func (x *PlayerLocation) GetPosition() *mgl32.Vec3 {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_packet_player_location_proto protoreflect.FileDescriptor

const file_packet_player_location_proto_rawDesc = "" +
	"\n" +
	"\x1cpacket/player_location.proto\x125mousetunnel.minecraft.protocol.packet.player_location\x1a\vmgl32.proto\x1a\x14packet_options.proto\"\x9b\x01\n" +
	"\x0ePlayerLocation\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12&\n" +
	"\x0eEntityUniqueID\x18\x02 \x01(\x03R\x0eEntityUniqueID\x12F\n" +
	"\bPosition\x18\x03 \x01(\v2*.mousetunnel.minecraft.protocol.mgl32.Vec3R\bPosition:\x05\xc0\xc8\x05\xc6\x02*W\n" +
	"\x16PlayerLocationTypeEnum\x12!\n" +
	"\x1dPlayerLocationTypeCoordinates\x10\x00\x12\x1a\n" +
	"\x16PlayerLocationTypeHide\x10\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_player_location_proto_rawDescOnce sync.Once
	file_packet_player_location_proto_rawDescData []byte
)

func file_packet_player_location_proto_rawDescGZIP() []byte {
	file_packet_player_location_proto_rawDescOnce.Do(func() {
		file_packet_player_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_player_location_proto_rawDesc), len(file_packet_player_location_proto_rawDesc)))
	})
	return file_packet_player_location_proto_rawDescData
}

var file_packet_player_location_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_player_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_player_location_proto_goTypes = []any{
	(PlayerLocationTypeEnum)(0), // 0: mousetunnel.minecraft.protocol.packet.player_location.PlayerLocationTypeEnum
	(*PlayerLocation)(nil),      // 1: mousetunnel.minecraft.protocol.packet.player_location.PlayerLocation
	(*mgl32.Vec3)(nil),          // 2: mousetunnel.minecraft.protocol.mgl32.Vec3
}
var file_packet_player_location_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.packet.player_location.PlayerLocation.Position:type_name -> mousetunnel.minecraft.protocol.mgl32.Vec3
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_player_location_proto_init() }
func file_packet_player_location_proto_init() {
	if File_packet_player_location_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_player_location_proto_rawDesc), len(file_packet_player_location_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_player_location_proto_goTypes,
		DependencyIndexes: file_packet_player_location_proto_depIdxs,
		EnumInfos:         file_packet_player_location_proto_enumTypes,
		MessageInfos:      file_packet_player_location_proto_msgTypes,
	}.Build()
	File_packet_player_location_proto = out.File
	file_packet_player_location_proto_goTypes = nil
	file_packet_player_location_proto_depIdxs = nil
}
