// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/player_video_capture.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerVideoCaptureActionEnum int32

const (
	PlayerVideoCaptureActionEnum_PlayerVideoCaptureActionStop  PlayerVideoCaptureActionEnum = 0
	PlayerVideoCaptureActionEnum_PlayerVideoCaptureActionStart PlayerVideoCaptureActionEnum = 1
)

// Enum value maps for PlayerVideoCaptureActionEnum.
var (
	PlayerVideoCaptureActionEnum_name = map[int32]string{
		0: "PlayerVideoCaptureActionStop",
		1: "PlayerVideoCaptureActionStart",
	}
	PlayerVideoCaptureActionEnum_value = map[string]int32{
		"PlayerVideoCaptureActionStop":  0,
		"PlayerVideoCaptureActionStart": 1,
	}
)

func (x PlayerVideoCaptureActionEnum) Enum() *PlayerVideoCaptureActionEnum {
	p := new(PlayerVideoCaptureActionEnum)
	*p = x
	return p
}

func (x PlayerVideoCaptureActionEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerVideoCaptureActionEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_player_video_capture_proto_enumTypes[0].Descriptor()
}

func (PlayerVideoCaptureActionEnum) Type() protoreflect.EnumType {
	return &file_packet_player_video_capture_proto_enumTypes[0]
}

func (x PlayerVideoCaptureActionEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerVideoCaptureActionEnum.Descriptor instead.
func (PlayerVideoCaptureActionEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_player_video_capture_proto_rawDescGZIP(), []int{0}
}

// PlayerVideoCapture 数据包由服务器发送，用于开始或停止玩家的视频录制。
// 它只在开发构建中生效，对正式构建没有效果。录制时，
// 客户端会按下方指定格式把单独帧保存到 '/LocalCache/minecraftpe'。
//
// PlayerVideoCapture packet is sent by the server to start or stop video recording for a player. It only works on
// development builds and has no effect on retail builds. When recording,
// the client will save individual frames to '/LocalCache/minecraftpe' in the format specified below.
//
// Added: v1.21.70
type PlayerVideoCapture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action 是要对视频捕获执行的操作，它是上方常量之一。
	//
	// Action is the action to perform with the video capture. It is one of the constants above.
	//
	// Added: v1.21.70
	// Go type: byte
	Action uint32 `protobuf:"varint,1,opt,name=Action,proto3" json:"Action,omitempty"`
	// FrameRate 是录制视频时应使用的帧率。仅当 Action 为 PlayerVideoCaptureActionStart 时使用。
	// 更高帧率会记录更多帧，但也会明显增加卡顿。
	//
	// FrameRate is the frame rate at which the video should be recorded. It is only used when Action is
	// PlayerVideoCaptureActionStart. A higher frame rate will cause more frames to be recorded, but also
	// a noticeable increase in lag.
	//
	// Added: v1.21.70
	FrameRate int32 `protobuf:"varint,2,opt,name=FrameRate,proto3" json:"FrameRate,omitempty"`
	// FilePrefix 是保存帧时使用的文件名前缀。帧会以 'FilePrefix%d.png' 格式保存，其中 %d 为帧索引。
	//
	// FilePrefix is the prefix of the file name that will be used to save the frames. The frames will be saved
	// in the format 'FilePrefix%d.png' where %d is the frame index.
	//
	// Added: v1.21.70
	FilePrefix    string `protobuf:"bytes,3,opt,name=FilePrefix,proto3" json:"FilePrefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerVideoCapture) Reset() {
	*x = PlayerVideoCapture{}
	mi := &file_packet_player_video_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerVideoCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerVideoCapture) ProtoMessage() {}

func (x *PlayerVideoCapture) ProtoReflect() protoreflect.Message {
	mi := &file_packet_player_video_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerVideoCapture.ProtoReflect.Descriptor instead.
func (*PlayerVideoCapture) Descriptor() ([]byte, []int) {
	return file_packet_player_video_capture_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerVideoCapture) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PlayerVideoCapture) GetFrameRate() int32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *PlayerVideoCapture) GetFilePrefix() string {
	if x != nil {
		return x.FilePrefix
	}
	return ""
}

var File_packet_player_video_capture_proto protoreflect.FileDescriptor

const file_packet_player_video_capture_proto_rawDesc = "" +
	"\n" +
	"!packet/player_video_capture.proto\x12:mousetunnel.minecraft.protocol.packet.player_video_capture\x1a\x14packet_options.proto\"q\n" +
	"\x12PlayerVideoCapture\x12\x16\n" +
	"\x06Action\x18\x01 \x01(\rR\x06Action\x12\x1c\n" +
	"\tFrameRate\x18\x02 \x01(\x05R\tFrameRate\x12\x1e\n" +
	"\n" +
	"FilePrefix\x18\x03 \x01(\tR\n" +
	"FilePrefix:\x05\xc0\xc8\x05\xc4\x02*c\n" +
	"\x1cPlayerVideoCaptureActionEnum\x12 \n" +
	"\x1cPlayerVideoCaptureActionStop\x10\x00\x12!\n" +
	"\x1dPlayerVideoCaptureActionStart\x10\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_player_video_capture_proto_rawDescOnce sync.Once
	file_packet_player_video_capture_proto_rawDescData []byte
)

func file_packet_player_video_capture_proto_rawDescGZIP() []byte {
	file_packet_player_video_capture_proto_rawDescOnce.Do(func() {
		file_packet_player_video_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_player_video_capture_proto_rawDesc), len(file_packet_player_video_capture_proto_rawDesc)))
	})
	return file_packet_player_video_capture_proto_rawDescData
}

var file_packet_player_video_capture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_player_video_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_player_video_capture_proto_goTypes = []any{
	(PlayerVideoCaptureActionEnum)(0), // 0: mousetunnel.minecraft.protocol.packet.player_video_capture.PlayerVideoCaptureActionEnum
	(*PlayerVideoCapture)(nil),        // 1: mousetunnel.minecraft.protocol.packet.player_video_capture.PlayerVideoCapture
}
var file_packet_player_video_capture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_player_video_capture_proto_init() }
func file_packet_player_video_capture_proto_init() {
	if File_packet_player_video_capture_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_player_video_capture_proto_rawDesc), len(file_packet_player_video_capture_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_player_video_capture_proto_goTypes,
		DependencyIndexes: file_packet_player_video_capture_proto_depIdxs,
		EnumInfos:         file_packet_player_video_capture_proto_enumTypes,
		MessageInfos:      file_packet_player_video_capture_proto_msgTypes,
	}.Build()
	File_packet_player_video_capture_proto = out.File
	file_packet_player_video_capture_proto_goTypes = nil
	file_packet_player_video_capture_proto_depIdxs = nil
}
