// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/resource_packs_info.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourcePacksInfo 由服务器发送，用于告知客户端服务器拥有哪些资源包。
// 它会发送服务器拥有的资源包列表，以及版本和描述等基础信息。
//
// ResourcePacksInfo is sent by the server to inform the client on what resource packs the server has. It
// sends a list of the resource packs it has and basic information on them like the version and description.
//
// Added: v1.11.1
type ResourcePacksInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TexturePackRequired 指定客户端是否必须接受服务器提供的材质包才能加入服务器。
	// 如果设为 true，客户端可以选择下载资源包并加入，或完全退出。行为包永远不需要下载。
	//
	// TexturePackRequired specifies if the client must accept the texture packs the server has in order to
	// join the server. If set to true, the client gets the option to either download the resource packs and
	// join, or quit entirely. Behaviour packs never have to be downloaded.
	//
	// Added: v1.11.1
	TexturePackRequired bool `protobuf:"varint,1,opt,name=TexturePackRequired,proto3" json:"TexturePackRequired,omitempty"`
	// HasAddons 指定是否有任何资源包包含附加包。如果设为 true，
	// 只有支持附加包的客户端才能下载它们。
	//
	// HasAddons specifies if any of the resource packs contain addons in them. If set to true, only clients
	// that support addons will be able to download them.
	//
	// Added: v1.20.70
	HasAddons bool `protobuf:"varint,2,opt,name=HasAddons,proto3" json:"HasAddons,omitempty"`
	// HasScripts 指定是否有任何资源包包含脚本。如果设为 true，
	// 只有支持脚本的客户端才能下载它们。
	//
	// HasScripts specifies if any of the resource packs contain scripts in them. If set to true, only clients
	// that support scripts will be able to download them.
	//
	// Added: v1.11.1
	HasScripts bool `protobuf:"varint,3,opt,name=HasScripts,proto3" json:"HasScripts,omitempty"`
	// ForcingServerPacks 指定是否应强制客户端使用服务器资源包。
	//
	// ForcingServerPacks specifies if the client should be forced to use the server resource packs.
	//
	// Added: v1.17.10
	ForcingServerPacks bool `protobuf:"varint,4,opt,name=ForcingServerPacks,proto3" json:"ForcingServerPacks,omitempty"`
	// ForceDisableVibrantVisuals 指定是否应在服务器上强制禁用鲜艳视觉功能。
	// 如果设为 true，无论客户端设置如何，服务器都会确保不会启用鲜艳视觉。
	//
	// ForceDisableVibrantVisuals specifies if the vibrant visuals feature should be forcibly disabled on the server.
	// If set to true, the server will ensure that vibrant visuals are not enabled, regardless of the client's settings.
	//
	// Added: v1.21.90
	ForceDisableVibrantVisuals bool `protobuf:"varint,5,opt,name=ForceDisableVibrantVisuals,proto3" json:"ForceDisableVibrantVisuals,omitempty"`
	// WorldTemplateUUID 是用于生成世界的模板 UUID。模板可以从市场下载，
	// 也可以通过 `.mctemplate` 文件安装。如果世界不是从模板生成的，该字段为空。
	//
	// WorldTemplateUUID is the UUID of the template that has been used to generate the world. Templates can
	// be downloaded from the marketplace or installed via '.mctemplate' files. If the world was not generated
	// from a template, this field is empty.
	//
	// Added: v1.20.30
	// Go type: uuid.UUID
	WorldTemplateUUID string `protobuf:"bytes,6,opt,name=WorldTemplateUUID,proto3" json:"WorldTemplateUUID,omitempty"`
	// WorldTemplateVersion 是用于生成世界的世界模板版本。如果世界不是从模板生成的，该字段为空。
	//
	// WorldTemplateVersion is the version of the world template that has been used to generate the world. If
	// the world was not generated from a template, this field is empty.
	//
	// Added: v1.20.30
	WorldTemplateVersion string `protobuf:"bytes,7,opt,name=WorldTemplateVersion,proto3" json:"WorldTemplateVersion,omitempty"`
	// BehaviourPacks 是客户端加入服务器前需要下载的行为包列表。
	// 这些包在该数据包中的顺序并不重要，但在 ResourcePackStack 数据包中很重要。
	//
	// BehaviourPacks is a list of behaviour packs that the client needs to download before joining the server.
	// The order of these packs is not relevant in this packet. It is however important in the ResourcePackStack packet.
	//
	// Added: v1.1.0
	// Go type: []protocol.TexturePackInfo
	BehaviourPacks []*protocol.TexturePackInfo `protobuf:"bytes,8,rep,name=BehaviourPacks,proto3" json:"BehaviourPacks,omitempty"`
	// TexturePacks 是客户端加入服务器前需要下载的材质包列表。
	// 这些材质包在该数据包中的顺序并不重要，但在 ResourcePackStack 数据包中很重要。
	//
	// TexturePacks is a list of texture packs that the client needs to download before joining the server.
	// The order of these texture packs is not relevant in this packet. It is however important in the
	// ResourcePackStack packet.
	//
	// Added: v1.11.1
	// Go type: []protocol.TexturePackInfo
	TexturePacks []*protocol.TexturePackInfo `protobuf:"bytes,9,rep,name=TexturePacks,proto3" json:"TexturePacks,omitempty"`
	// CDNEntries 是远程 URL 列表，客户端可使用它们下载资源包，
	// 而不必由服务器按块发送资源包。
	//
	// CDNEntries is a list of remote URLs that the client can use to download resource packs instead of the
	// server sending them in chunks.
	//
	// Added: v1.20.30.24, Removed: v1.21.40
	// Go type: []protocol.PackURL
	CDNEntries    []*protocol.PackURL `protobuf:"bytes,10,rep,name=CDNEntries,proto3" json:"CDNEntries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePacksInfo) Reset() {
	*x = ResourcePacksInfo{}
	mi := &file_packet_resource_packs_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePacksInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePacksInfo) ProtoMessage() {}

func (x *ResourcePacksInfo) ProtoReflect() protoreflect.Message {
	mi := &file_packet_resource_packs_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePacksInfo.ProtoReflect.Descriptor instead.
func (*ResourcePacksInfo) Descriptor() ([]byte, []int) {
	return file_packet_resource_packs_info_proto_rawDescGZIP(), []int{0}
}

func (x *ResourcePacksInfo) GetTexturePackRequired() bool {
	if x != nil {
		return x.TexturePackRequired
	}
	return false
}

func (x *ResourcePacksInfo) GetHasAddons() bool {
	if x != nil {
		return x.HasAddons
	}
	return false
}

func (x *ResourcePacksInfo) GetHasScripts() bool {
	if x != nil {
		return x.HasScripts
	}
	return false
}

func (x *ResourcePacksInfo) GetForcingServerPacks() bool {
	if x != nil {
		return x.ForcingServerPacks
	}
	return false
}

func (x *ResourcePacksInfo) GetForceDisableVibrantVisuals() bool {
	if x != nil {
		return x.ForceDisableVibrantVisuals
	}
	return false
}

func (x *ResourcePacksInfo) GetWorldTemplateUUID() string {
	if x != nil {
		return x.WorldTemplateUUID
	}
	return ""
}

func (x *ResourcePacksInfo) GetWorldTemplateVersion() string {
	if x != nil {
		return x.WorldTemplateVersion
	}
	return ""
}

func (x *ResourcePacksInfo) GetBehaviourPacks() []*protocol.TexturePackInfo {
	if x != nil {
		return x.BehaviourPacks
	}
	return nil
}

func (x *ResourcePacksInfo) GetTexturePacks() []*protocol.TexturePackInfo {
	if x != nil {
		return x.TexturePacks
	}
	return nil
}

func (x *ResourcePacksInfo) GetCDNEntries() []*protocol.PackURL {
	if x != nil {
		return x.CDNEntries
	}
	return nil
}

var File_packet_resource_packs_info_proto protoreflect.FileDescriptor

const file_packet_resource_packs_info_proto_rawDesc = "" +
	"\n" +
	" packet/resource_packs_info.proto\x129mousetunnel.minecraft.protocol.packet.resource_packs_info\x1a\x14packet_options.proto\x1a\x13resource_pack.proto\"\xfc\x04\n" +
	"\x11ResourcePacksInfo\x120\n" +
	"\x13TexturePackRequired\x18\x01 \x01(\bR\x13TexturePackRequired\x12\x1c\n" +
	"\tHasAddons\x18\x02 \x01(\bR\tHasAddons\x12\x1e\n" +
	"\n" +
	"HasScripts\x18\x03 \x01(\bR\n" +
	"HasScripts\x12.\n" +
	"\x12ForcingServerPacks\x18\x04 \x01(\bR\x12ForcingServerPacks\x12>\n" +
	"\x1aForceDisableVibrantVisuals\x18\x05 \x01(\bR\x1aForceDisableVibrantVisuals\x12,\n" +
	"\x11WorldTemplateUUID\x18\x06 \x01(\tR\x11WorldTemplateUUID\x122\n" +
	"\x14WorldTemplateVersion\x18\a \x01(\tR\x14WorldTemplateVersion\x12e\n" +
	"\x0eBehaviourPacks\x18\b \x03(\v2=.mousetunnel.minecraft.protocol.resource_pack.TexturePackInfoR\x0eBehaviourPacks\x12a\n" +
	"\fTexturePacks\x18\t \x03(\v2=.mousetunnel.minecraft.protocol.resource_pack.TexturePackInfoR\fTexturePacks\x12U\n" +
	"\n" +
	"CDNEntries\x18\n" +
	" \x03(\v25.mousetunnel.minecraft.protocol.resource_pack.PackURLR\n" +
	"CDNEntries:\x04\xc0\xc8\x05\x06BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_resource_packs_info_proto_rawDescOnce sync.Once
	file_packet_resource_packs_info_proto_rawDescData []byte
)

func file_packet_resource_packs_info_proto_rawDescGZIP() []byte {
	file_packet_resource_packs_info_proto_rawDescOnce.Do(func() {
		file_packet_resource_packs_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_resource_packs_info_proto_rawDesc), len(file_packet_resource_packs_info_proto_rawDesc)))
	})
	return file_packet_resource_packs_info_proto_rawDescData
}

var file_packet_resource_packs_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_resource_packs_info_proto_goTypes = []any{
	(*ResourcePacksInfo)(nil),        // 0: mousetunnel.minecraft.protocol.packet.resource_packs_info.ResourcePacksInfo
	(*protocol.TexturePackInfo)(nil), // 1: mousetunnel.minecraft.protocol.resource_pack.TexturePackInfo
	(*protocol.PackURL)(nil),         // 2: mousetunnel.minecraft.protocol.resource_pack.PackURL
}
var file_packet_resource_packs_info_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.packet.resource_packs_info.ResourcePacksInfo.BehaviourPacks:type_name -> mousetunnel.minecraft.protocol.resource_pack.TexturePackInfo
	1, // 1: mousetunnel.minecraft.protocol.packet.resource_packs_info.ResourcePacksInfo.TexturePacks:type_name -> mousetunnel.minecraft.protocol.resource_pack.TexturePackInfo
	2, // 2: mousetunnel.minecraft.protocol.packet.resource_packs_info.ResourcePacksInfo.CDNEntries:type_name -> mousetunnel.minecraft.protocol.resource_pack.PackURL
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packet_resource_packs_info_proto_init() }
func file_packet_resource_packs_info_proto_init() {
	if File_packet_resource_packs_info_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_resource_packs_info_proto_rawDesc), len(file_packet_resource_packs_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_resource_packs_info_proto_goTypes,
		DependencyIndexes: file_packet_resource_packs_info_proto_depIdxs,
		MessageInfos:      file_packet_resource_packs_info_proto_msgTypes,
	}.Build()
	File_packet_resource_packs_info_proto = out.File
	file_packet_resource_packs_info_proto_goTypes = nil
	file_packet_resource_packs_info_proto_depIdxs = nil
}
