// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/respawn.proto

package packet

import (
	mgl32 "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/mgl32"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespawnStateEnum int32

const (
	RespawnStateEnum_RespawnStateSearchingForSpawn  RespawnStateEnum = 0
	RespawnStateEnum_RespawnStateReadyToSpawn       RespawnStateEnum = 1
	RespawnStateEnum_RespawnStateClientReadyToSpawn RespawnStateEnum = 2
)

// Enum value maps for RespawnStateEnum.
var (
	RespawnStateEnum_name = map[int32]string{
		0: "RespawnStateSearchingForSpawn",
		1: "RespawnStateReadyToSpawn",
		2: "RespawnStateClientReadyToSpawn",
	}
	RespawnStateEnum_value = map[string]int32{
		"RespawnStateSearchingForSpawn":  0,
		"RespawnStateReadyToSpawn":       1,
		"RespawnStateClientReadyToSpawn": 2,
	}
)

func (x RespawnStateEnum) Enum() *RespawnStateEnum {
	p := new(RespawnStateEnum)
	*p = x
	return p
}

func (x RespawnStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespawnStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_respawn_proto_enumTypes[0].Descriptor()
}

func (RespawnStateEnum) Type() protoreflect.EnumType {
	return &file_packet_respawn_proto_enumTypes[0]
}

func (x RespawnStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespawnStateEnum.Descriptor instead.
func (RespawnStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_respawn_proto_rawDescGZIP(), []int{0}
}

// Respawn 由服务器发送，用于让玩家在客户端侧重生。它会响应 ActionType 为 PlayerActionRespawn 的
// PlayerAction 数据包发送。
// 自 1.13 起，服务器会发送两个具有不同状态的该数据包，客户端再回发其中一个以完成重生。
//
// Respawn is sent by the server to make a player respawn client-side. It is sent in response to a
// PlayerAction packet with ActionType PlayerActionRespawn.
// As of 1.13, the server sends two of these packets with different states, and the client sends one of these
// back in order to complete the respawn.
//
// Added: v1.13.0
type Respawn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position 是玩家应重生的位置。该位置可能位于不同维度，此时应先向客户端发送 ChangeDimension 数据包。
	//
	// Position is the position on which the player should be respawned. The position might be in a different
	// dimension, in which case the client should first be sent a ChangeDimension packet.
	//
	// Added: v1.11.1
	// Go type: mgl32.Vec3
	Position *mgl32.Vec3 `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	// State 是重生的“状态”。它是上方常量之一，数据包所含的值取决于发送方是服务器还是客户端。
	//
	// State is the 'state' of the respawn. It is one of the constants that may be found above, and the value
	// the packet contains depends on whether the server or client sends it.
	//
	// Added: v1.13.0
	// Go type: byte
	State uint32 `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	// EntityRuntimeID 是该重生数据包所涉及玩家的实体运行时 ID。
	// 这显然用于让服务器识别哪个玩家发送了该数据包。
	//
	// EntityRuntimeID is the entity runtime ID of the player that the respawn packet concerns. This is
	// apparently for the server to recognise which player sends this packet.
	//
	// Added: v1.13.0
	EntityRuntimeID uint64 `protobuf:"varint,3,opt,name=EntityRuntimeID,proto3" json:"EntityRuntimeID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Respawn) Reset() {
	*x = Respawn{}
	mi := &file_packet_respawn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respawn) ProtoMessage() {}

func (x *Respawn) ProtoReflect() protoreflect.Message {
	mi := &file_packet_respawn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respawn.ProtoReflect.Descriptor instead.
func (*Respawn) Descriptor() ([]byte, []int) {
	return file_packet_respawn_proto_rawDescGZIP(), []int{0}
}

func (x *Respawn) GetPosition() *mgl32.Vec3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Respawn) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Respawn) GetEntityRuntimeID() uint64 {
	if x != nil {
		return x.EntityRuntimeID
	}
	return 0
}

var File_packet_respawn_proto protoreflect.FileDescriptor

const file_packet_respawn_proto_rawDesc = "" +
	"\n" +
	"\x14packet/respawn.proto\x12-mousetunnel.minecraft.protocol.packet.respawn\x1a\vmgl32.proto\x1a\x14packet_options.proto\"\x97\x01\n" +
	"\aRespawn\x12F\n" +
	"\bPosition\x18\x01 \x01(\v2*.mousetunnel.minecraft.protocol.mgl32.Vec3R\bPosition\x12\x14\n" +
	"\x05State\x18\x02 \x01(\rR\x05State\x12(\n" +
	"\x0fEntityRuntimeID\x18\x03 \x01(\x04R\x0fEntityRuntimeID:\x04\xc0\xc8\x05-*w\n" +
	"\x10RespawnStateEnum\x12!\n" +
	"\x1dRespawnStateSearchingForSpawn\x10\x00\x12\x1c\n" +
	"\x18RespawnStateReadyToSpawn\x10\x01\x12\"\n" +
	"\x1eRespawnStateClientReadyToSpawn\x10\x02BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_respawn_proto_rawDescOnce sync.Once
	file_packet_respawn_proto_rawDescData []byte
)

func file_packet_respawn_proto_rawDescGZIP() []byte {
	file_packet_respawn_proto_rawDescOnce.Do(func() {
		file_packet_respawn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_respawn_proto_rawDesc), len(file_packet_respawn_proto_rawDesc)))
	})
	return file_packet_respawn_proto_rawDescData
}

var file_packet_respawn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_respawn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_respawn_proto_goTypes = []any{
	(RespawnStateEnum)(0), // 0: mousetunnel.minecraft.protocol.packet.respawn.RespawnStateEnum
	(*Respawn)(nil),       // 1: mousetunnel.minecraft.protocol.packet.respawn.Respawn
	(*mgl32.Vec3)(nil),    // 2: mousetunnel.minecraft.protocol.mgl32.Vec3
}
var file_packet_respawn_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.packet.respawn.Respawn.Position:type_name -> mousetunnel.minecraft.protocol.mgl32.Vec3
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_respawn_proto_init() }
func file_packet_respawn_proto_init() {
	if File_packet_respawn_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_respawn_proto_rawDesc), len(file_packet_respawn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_respawn_proto_goTypes,
		DependencyIndexes: file_packet_respawn_proto_depIdxs,
		EnumInfos:         file_packet_respawn_proto_enumTypes,
		MessageInfos:      file_packet_respawn_proto_msgTypes,
	}.Build()
	File_packet_respawn_proto = out.File
	file_packet_respawn_proto_goTypes = nil
	file_packet_respawn_proto_depIdxs = nil
}
