// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/script_custom_event.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScriptCustomEvent 可由客户端和服务器双方发送。它是一种让脚本与服务器通信的方式，
// 使客户端可以告知服务器它触发了某个事件，反向通信也同样可行。
// ScriptCustomEvent 自 1.20.10 起已弃用。
//
// ScriptCustomEvent is sent by both the client and the server. It is a way to let scripts communicate with
// the server, so that the client can let the server know it triggered an event, or the other way around.
// ScriptCustomEvent is deprecated as of 1.20.10.
//
// Added: v1.12
type ScriptCustomEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EventName 是事件名称。脚本和服务器会使用该事件名称来识别发送的数据。
	//
	// EventName is the name of the event. The script and the server will use this event name to identify the
	// data that is sent.
	//
	// Added: v1.12
	EventName string `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName,omitempty"`
	// EventData 是事件数据。该数据通常是 JSON 编码字符串，脚本也能够对其进行编码和解码。
	//
	// EventData is the data of the event. This data is typically a JSON encoded string, that the script is
	// able to encode and decode too.
	//
	// Added: v1.12
	// Go type: []byte
	EventData     []byte `protobuf:"bytes,2,opt,name=EventData,proto3" json:"EventData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptCustomEvent) Reset() {
	*x = ScriptCustomEvent{}
	mi := &file_packet_script_custom_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptCustomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptCustomEvent) ProtoMessage() {}

func (x *ScriptCustomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packet_script_custom_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptCustomEvent.ProtoReflect.Descriptor instead.
func (*ScriptCustomEvent) Descriptor() ([]byte, []int) {
	return file_packet_script_custom_event_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptCustomEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ScriptCustomEvent) GetEventData() []byte {
	if x != nil {
		return x.EventData
	}
	return nil
}

var File_packet_script_custom_event_proto protoreflect.FileDescriptor

const file_packet_script_custom_event_proto_rawDesc = "" +
	"\n" +
	" packet/script_custom_event.proto\x129mousetunnel.minecraft.protocol.packet.script_custom_event\x1a\x14packet_options.proto\"U\n" +
	"\x11ScriptCustomEvent\x12\x1c\n" +
	"\tEventName\x18\x01 \x01(\tR\tEventName\x12\x1c\n" +
	"\tEventData\x18\x02 \x01(\fR\tEventData:\x04\xc0\xc8\x05uBJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_script_custom_event_proto_rawDescOnce sync.Once
	file_packet_script_custom_event_proto_rawDescData []byte
)

func file_packet_script_custom_event_proto_rawDescGZIP() []byte {
	file_packet_script_custom_event_proto_rawDescOnce.Do(func() {
		file_packet_script_custom_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_script_custom_event_proto_rawDesc), len(file_packet_script_custom_event_proto_rawDesc)))
	})
	return file_packet_script_custom_event_proto_rawDescData
}

var file_packet_script_custom_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_script_custom_event_proto_goTypes = []any{
	(*ScriptCustomEvent)(nil), // 0: mousetunnel.minecraft.protocol.packet.script_custom_event.ScriptCustomEvent
}
var file_packet_script_custom_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_script_custom_event_proto_init() }
func file_packet_script_custom_event_proto_init() {
	if File_packet_script_custom_event_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_script_custom_event_proto_rawDesc), len(file_packet_script_custom_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_script_custom_event_proto_goTypes,
		DependencyIndexes: file_packet_script_custom_event_proto_depIdxs,
		MessageInfos:      file_packet_script_custom_event_proto_msgTypes,
	}.Build()
	File_packet_script_custom_event_proto = out.File
	file_packet_script_custom_event_proto_goTypes = nil
	file_packet_script_custom_event_proto_depIdxs = nil
}
