// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/set_spawn_position.proto

package packet

import (
	protocol "github.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnTypeEnum int32

const (
	SpawnTypeEnum_SpawnTypePlayer SpawnTypeEnum = 0
	SpawnTypeEnum_SpawnTypeWorld  SpawnTypeEnum = 1
)

// Enum value maps for SpawnTypeEnum.
var (
	SpawnTypeEnum_name = map[int32]string{
		0: "SpawnTypePlayer",
		1: "SpawnTypeWorld",
	}
	SpawnTypeEnum_value = map[string]int32{
		"SpawnTypePlayer": 0,
		"SpawnTypeWorld":  1,
	}
)

func (x SpawnTypeEnum) Enum() *SpawnTypeEnum {
	p := new(SpawnTypeEnum)
	*p = x
	return p
}

func (x SpawnTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpawnTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_set_spawn_position_proto_enumTypes[0].Descriptor()
}

func (SpawnTypeEnum) Type() protoreflect.EnumType {
	return &file_packet_set_spawn_position_proto_enumTypes[0]
}

func (x SpawnTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpawnTypeEnum.Descriptor instead.
func (SpawnTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_packet_set_spawn_position_proto_rawDescGZIP(), []int{0}
}

// SetSpawnPosition 由服务器发送，用于更新玩家的出生点位置，例如玩家在床上睡觉时。
//
// SetSpawnPosition is sent by the server to update the spawn position of a player, for example when sleeping
// in a bed.
//
// Added: v1.12
type SetSpawnPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SpawnType 是要设置的出生点类型。它可以是 SpawnTypePlayer 或 SpawnTypeWorld，
	// 并指定出生点设置的行为。如果设置为 SpawnTypeWorld，指南针指向的位置也会改变。
	//
	// SpawnType is the type of spawn to set. It is either SpawnTypePlayer or SpawnTypeWorld, and specifies
	// the behaviour of the spawn set. If SpawnTypeWorld is set, the position to which compasses will point is
	// also changed.
	//
	// Added: v1.12
	SpawnType int32 `protobuf:"varint,1,opt,name=SpawnType,proto3" json:"SpawnType,omitempty"`
	// Position 是被设置出生点的新位置。如果 SpawnType 为 SpawnTypeWorld，指南针会指向该位置。
	// 自 1.16 起，Position 始终是玩家的位置。
	//
	// Position is the new position of the spawn that was set. If SpawnType is SpawnTypeWorld, compasses will
	// point to this position. As of 1.16, Position is always the position of the player.
	//
	// Added: v1.12
	// Changed: v1.16, no longer carries the world spawn position and instead always carries the player's spawn position.
	Position *protocol.BlockPos `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	// Dimension 是出生点被更新的维度 ID。这尤其与 1.16 新增行为相关，
	// 例如重生锚允许在特定维度中设置出生点。
	//
	// Dimension is the ID of the dimension that had its spawn updated. This is specifically relevant for
	// behaviour added in 1.16 such as the respawn anchor, which allows setting the spawn in a specific
	// dimension.
	//
	// Added: v1.16
	Dimension int32 `protobuf:"varint,3,opt,name=Dimension,proto3" json:"Dimension,omitempty"`
	// SpawnPosition 是 1.16 新增的字段，保存世界出生点位置。
	// 默认出生点时，该出生点位置为 {-2147483648, -2147483648, -2147483648}。
	//
	// SpawnPosition is a new field added in 1.16. It holds the spawn position of the world. This spawn
	// position is {-2147483648, -2147483648, -2147483648} for a default spawn position.
	//
	// Added: v1.16
	SpawnPosition *protocol.BlockPos `protobuf:"bytes,4,opt,name=SpawnPosition,proto3" json:"SpawnPosition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpawnPosition) Reset() {
	*x = SetSpawnPosition{}
	mi := &file_packet_set_spawn_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpawnPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpawnPosition) ProtoMessage() {}

func (x *SetSpawnPosition) ProtoReflect() protoreflect.Message {
	mi := &file_packet_set_spawn_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpawnPosition.ProtoReflect.Descriptor instead.
func (*SetSpawnPosition) Descriptor() ([]byte, []int) {
	return file_packet_set_spawn_position_proto_rawDescGZIP(), []int{0}
}

func (x *SetSpawnPosition) GetSpawnType() int32 {
	if x != nil {
		return x.SpawnType
	}
	return 0
}

func (x *SetSpawnPosition) GetPosition() *protocol.BlockPos {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SetSpawnPosition) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *SetSpawnPosition) GetSpawnPosition() *protocol.BlockPos {
	if x != nil {
		return x.SpawnPosition
	}
	return nil
}

var File_packet_set_spawn_position_proto protoreflect.FileDescriptor

const file_packet_set_spawn_position_proto_rawDesc = "" +
	"\n" +
	"\x1fpacket/set_spawn_position.proto\x128mousetunnel.minecraft.protocol.packet.set_spawn_position\x1a\x0fblock_pos.proto\x1a\x14packet_options.proto\"\xfe\x01\n" +
	"\x10SetSpawnPosition\x12\x1c\n" +
	"\tSpawnType\x18\x01 \x01(\x05R\tSpawnType\x12N\n" +
	"\bPosition\x18\x02 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\bPosition\x12\x1c\n" +
	"\tDimension\x18\x03 \x01(\x05R\tDimension\x12X\n" +
	"\rSpawnPosition\x18\x04 \x01(\v22.mousetunnel.minecraft.protocol.block_pos.BlockPosR\rSpawnPosition:\x04\xc0\xc8\x05+*8\n" +
	"\rSpawnTypeEnum\x12\x13\n" +
	"\x0fSpawnTypePlayer\x10\x00\x12\x12\n" +
	"\x0eSpawnTypeWorld\x10\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_set_spawn_position_proto_rawDescOnce sync.Once
	file_packet_set_spawn_position_proto_rawDescData []byte
)

func file_packet_set_spawn_position_proto_rawDescGZIP() []byte {
	file_packet_set_spawn_position_proto_rawDescOnce.Do(func() {
		file_packet_set_spawn_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_set_spawn_position_proto_rawDesc), len(file_packet_set_spawn_position_proto_rawDesc)))
	})
	return file_packet_set_spawn_position_proto_rawDescData
}

var file_packet_set_spawn_position_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_set_spawn_position_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_set_spawn_position_proto_goTypes = []any{
	(SpawnTypeEnum)(0),        // 0: mousetunnel.minecraft.protocol.packet.set_spawn_position.SpawnTypeEnum
	(*SetSpawnPosition)(nil),  // 1: mousetunnel.minecraft.protocol.packet.set_spawn_position.SetSpawnPosition
	(*protocol.BlockPos)(nil), // 2: mousetunnel.minecraft.protocol.block_pos.BlockPos
}
var file_packet_set_spawn_position_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.packet.set_spawn_position.SetSpawnPosition.Position:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	2, // 1: mousetunnel.minecraft.protocol.packet.set_spawn_position.SetSpawnPosition.SpawnPosition:type_name -> mousetunnel.minecraft.protocol.block_pos.BlockPos
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_packet_set_spawn_position_proto_init() }
func file_packet_set_spawn_position_proto_init() {
	if File_packet_set_spawn_position_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_set_spawn_position_proto_rawDesc), len(file_packet_set_spawn_position_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_set_spawn_position_proto_goTypes,
		DependencyIndexes: file_packet_set_spawn_position_proto_depIdxs,
		EnumInfos:         file_packet_set_spawn_position_proto_enumTypes,
		MessageInfos:      file_packet_set_spawn_position_proto_msgTypes,
	}.Build()
	File_packet_set_spawn_position_proto = out.File
	file_packet_set_spawn_position_proto_goTypes = nil
	file_packet_set_spawn_position_proto_depIdxs = nil
}
