// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/store_buy_succ.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreBuySucc 是网易商店购买成功数据包。
//
// StoreBuySucc is a NetEase store purchase success packet.
//
// Added: NetEase.
type StoreBuySucc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Go type: []byte
	Data          []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBuySucc) Reset() {
	*x = StoreBuySucc{}
	mi := &file_packet_store_buy_succ_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBuySucc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBuySucc) ProtoMessage() {}

func (x *StoreBuySucc) ProtoReflect() protoreflect.Message {
	mi := &file_packet_store_buy_succ_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBuySucc.ProtoReflect.Descriptor instead.
func (*StoreBuySucc) Descriptor() ([]byte, []int) {
	return file_packet_store_buy_succ_proto_rawDescGZIP(), []int{0}
}

func (x *StoreBuySucc) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_packet_store_buy_succ_proto protoreflect.FileDescriptor

const file_packet_store_buy_succ_proto_rawDesc = "" +
	"\n" +
	"\x1bpacket/store_buy_succ.proto\x124mousetunnel.minecraft.protocol.packet.store_buy_succ\x1a\x14packet_options.proto\")\n" +
	"\fStoreBuySucc\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data:\x05\xc0\xc8\x05\xca\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_store_buy_succ_proto_rawDescOnce sync.Once
	file_packet_store_buy_succ_proto_rawDescData []byte
)

func file_packet_store_buy_succ_proto_rawDescGZIP() []byte {
	file_packet_store_buy_succ_proto_rawDescOnce.Do(func() {
		file_packet_store_buy_succ_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_store_buy_succ_proto_rawDesc), len(file_packet_store_buy_succ_proto_rawDesc)))
	})
	return file_packet_store_buy_succ_proto_rawDescData
}

var file_packet_store_buy_succ_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_store_buy_succ_proto_goTypes = []any{
	(*StoreBuySucc)(nil), // 0: mousetunnel.minecraft.protocol.packet.store_buy_succ.StoreBuySucc
}
var file_packet_store_buy_succ_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_store_buy_succ_proto_init() }
func file_packet_store_buy_succ_proto_init() {
	if File_packet_store_buy_succ_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_store_buy_succ_proto_rawDesc), len(file_packet_store_buy_succ_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_store_buy_succ_proto_goTypes,
		DependencyIndexes: file_packet_store_buy_succ_proto_depIdxs,
		MessageInfos:      file_packet_store_buy_succ_proto_msgTypes,
	}.Build()
	File_packet_store_buy_succ_proto = out.File
	file_packet_store_buy_succ_proto_goTypes = nil
	file_packet_store_buy_succ_proto_depIdxs = nil
}
