// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/update_block_properties.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateBlockProperties 为旧版更新方块属性数据包预留。
//
// UpdateBlockProperties is reserved for the legacy update block properties packet.
type UpdateBlockProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockProperties) Reset() {
	*x = UpdateBlockProperties{}
	mi := &file_packet_update_block_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockProperties) ProtoMessage() {}

func (x *UpdateBlockProperties) ProtoReflect() protoreflect.Message {
	mi := &file_packet_update_block_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockProperties.ProtoReflect.Descriptor instead.
func (*UpdateBlockProperties) Descriptor() ([]byte, []int) {
	return file_packet_update_block_properties_proto_rawDescGZIP(), []int{0}
}

var File_packet_update_block_properties_proto protoreflect.FileDescriptor

const file_packet_update_block_properties_proto_rawDesc = "" +
	"\n" +
	"$packet/update_block_properties.proto\x12=mousetunnel.minecraft.protocol.packet.update_block_properties\x1a\x14packet_options.proto\"\x1e\n" +
	"\x15UpdateBlockProperties:\x05\xc0\xc8\x05\x86\x01BJZHgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_update_block_properties_proto_rawDescOnce sync.Once
	file_packet_update_block_properties_proto_rawDescData []byte
)

func file_packet_update_block_properties_proto_rawDescGZIP() []byte {
	file_packet_update_block_properties_proto_rawDescOnce.Do(func() {
		file_packet_update_block_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_update_block_properties_proto_rawDesc), len(file_packet_update_block_properties_proto_rawDesc)))
	})
	return file_packet_update_block_properties_proto_rawDescData
}

var file_packet_update_block_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_update_block_properties_proto_goTypes = []any{
	(*UpdateBlockProperties)(nil), // 0: mousetunnel.minecraft.protocol.packet.update_block_properties.UpdateBlockProperties
}
var file_packet_update_block_properties_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_update_block_properties_proto_init() }
func file_packet_update_block_properties_proto_init() {
	if File_packet_update_block_properties_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_update_block_properties_proto_rawDesc), len(file_packet_update_block_properties_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_update_block_properties_proto_goTypes,
		DependencyIndexes: file_packet_update_block_properties_proto_depIdxs,
		MessageInfos:      file_packet_update_block_properties_proto_msgTypes,
	}.Build()
	File_packet_update_block_properties_proto = out.File
	file_packet_update_block_properties_proto_goTypes = nil
	file_packet_update_block_properties_proto_depIdxs = nil
}
