// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: packet/update_adventure_settings.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateAdventureSettings 是服务器发送给客户端的数据包，用于更新玩家的冒险设置。
// 自 v1.19.10 起，它与 UpdateAbilities 数据包一起取代了 AdventureSettings 数据包。
//
// UpdateAdventureSettings is a packet sent from the server to the client to update the adventure settings of the player.
// It, along with the UpdateAbilities packet, are replacements of the AdventureSettings packet since v1.19.10.
//
// Added: v1.19.10
type UpdateAdventureSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NoPvM 是一个布尔值，表示玩家是否允许与生物战斗。
	//
	// NoPvM is a boolean indicating whether the player is allowed to fight mobs or not.
	//
	// Added: v1.19.10
	NoPvM bool `protobuf:"varint,1,opt,name=NoPvM,proto3" json:"NoPvM,omitempty"`
	// NoMvP 是一个布尔值，表示生物是否允许攻击玩家。尚不清楚为什么要将其发送给客户端。
	//
	// NoMvP is a boolean indicating whether mobs are allowed to fight the player or not. It is unclear why this is sent
	// to the client.
	//
	// Added: v1.19.10
	NoMvP bool `protobuf:"varint,2,opt,name=NoMvP,proto3" json:"NoMvP,omitempty"`
	// ImmutableWorld 是一个布尔值，表示玩家是否允许修改世界。
	//
	// ImmutableWorld is a boolean indicating whether the player is allowed to modify the world or not.
	//
	// Added: v1.19.10
	ImmutableWorld bool `protobuf:"varint,3,opt,name=ImmutableWorld,proto3" json:"ImmutableWorld,omitempty"`
	// ShowNameTags 是一个布尔值，表示是否显示玩家名称标签。
	//
	// ShowNameTags is a boolean indicating whether player name tags are shown or not.
	//
	// Added: v1.19.10
	ShowNameTags bool `protobuf:"varint,4,opt,name=ShowNameTags,proto3" json:"ShowNameTags,omitempty"`
	// AutoJump 是一个布尔值，表示玩家是否允许自动跳跃。
	//
	// AutoJump is a boolean indicating whether the player is allowed to jump automatically or not.
	//
	// Added: v1.19.10
	AutoJump      bool `protobuf:"varint,5,opt,name=AutoJump,proto3" json:"AutoJump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdventureSettings) Reset() {
	*x = UpdateAdventureSettings{}
	mi := &file_packet_update_adventure_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdventureSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdventureSettings) ProtoMessage() {}

func (x *UpdateAdventureSettings) ProtoReflect() protoreflect.Message {
	mi := &file_packet_update_adventure_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdventureSettings.ProtoReflect.Descriptor instead.
func (*UpdateAdventureSettings) Descriptor() ([]byte, []int) {
	return file_packet_update_adventure_settings_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAdventureSettings) GetNoPvM() bool {
	if x != nil {
		return x.NoPvM
	}
	return false
}

func (x *UpdateAdventureSettings) GetNoMvP() bool {
	if x != nil {
		return x.NoMvP
	}
	return false
}

func (x *UpdateAdventureSettings) GetImmutableWorld() bool {
	if x != nil {
		return x.ImmutableWorld
	}
	return false
}

func (x *UpdateAdventureSettings) GetShowNameTags() bool {
	if x != nil {
		return x.ShowNameTags
	}
	return false
}

func (x *UpdateAdventureSettings) GetAutoJump() bool {
	if x != nil {
		return x.AutoJump
	}
	return false
}

var File_packet_update_adventure_settings_proto protoreflect.FileDescriptor

const file_packet_update_adventure_settings_proto_rawDesc = "" +
	"\n" +
	"&packet/update_adventure_settings.proto\x12?mousetunnel.minecraft.protocol.packet.update_adventure_settings\x1a\x14packet_options.proto\"\xb4\x01\n" +
	"\x17UpdateAdventureSettings\x12\x14\n" +
	"\x05NoPvM\x18\x01 \x01(\bR\x05NoPvM\x12\x14\n" +
	"\x05NoMvP\x18\x02 \x01(\bR\x05NoMvP\x12&\n" +
	"\x0eImmutableWorld\x18\x03 \x01(\bR\x0eImmutableWorld\x12\"\n" +
	"\fShowNameTags\x18\x04 \x01(\bR\fShowNameTags\x12\x1a\n" +
	"\bAutoJump\x18\x05 \x01(\bR\bAutoJump:\x05\xc0\xc8\x05\xbc\x01BPZNgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/packet;packetb\x06proto3"

var (
	file_packet_update_adventure_settings_proto_rawDescOnce sync.Once
	file_packet_update_adventure_settings_proto_rawDescData []byte
)

func file_packet_update_adventure_settings_proto_rawDescGZIP() []byte {
	file_packet_update_adventure_settings_proto_rawDescOnce.Do(func() {
		file_packet_update_adventure_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_update_adventure_settings_proto_rawDesc), len(file_packet_update_adventure_settings_proto_rawDesc)))
	})
	return file_packet_update_adventure_settings_proto_rawDescData
}

var file_packet_update_adventure_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_update_adventure_settings_proto_goTypes = []any{
	(*UpdateAdventureSettings)(nil), // 0: mousetunnel.minecraft.protocol.packet.update_adventure_settings.UpdateAdventureSettings
}
var file_packet_update_adventure_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_update_adventure_settings_proto_init() }
func file_packet_update_adventure_settings_proto_init() {
	if File_packet_update_adventure_settings_proto != nil {
		return
	}
	file_packet_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_update_adventure_settings_proto_rawDesc), len(file_packet_update_adventure_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_update_adventure_settings_proto_goTypes,
		DependencyIndexes: file_packet_update_adventure_settings_proto_depIdxs,
		MessageInfos:      file_packet_update_adventure_settings_proto_msgTypes,
	}.Build()
	File_packet_update_adventure_settings_proto = out.File
	file_packet_update_adventure_settings_proto_goTypes = nil
	file_packet_update_adventure_settings_proto_depIdxs = nil
}
