// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_actors/fields/banner_patterns.proto

package fields

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BannerPatterns 描述旗帜中的一个图案组合。
//
// BannerPatterns describes one pattern entry in a banner.
type BannerPatterns struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TAG_Int(4) = 0
	Color int32 `protobuf:"varint,1,opt,name=Color,proto3" json:"Color,omitempty"`
	// TAG_String(8) = ""
	Pattern       string `protobuf:"bytes,2,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerPatterns) Reset() {
	*x = BannerPatterns{}
	mi := &file_block_actors_fields_banner_patterns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerPatterns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerPatterns) ProtoMessage() {}

func (x *BannerPatterns) ProtoReflect() protoreflect.Message {
	mi := &file_block_actors_fields_banner_patterns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerPatterns.ProtoReflect.Descriptor instead.
func (*BannerPatterns) Descriptor() ([]byte, []int) {
	return file_block_actors_fields_banner_patterns_proto_rawDescGZIP(), []int{0}
}

func (x *BannerPatterns) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *BannerPatterns) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

var File_block_actors_fields_banner_patterns_proto protoreflect.FileDescriptor

const file_block_actors_fields_banner_patterns_proto_rawDesc = "" +
	"\n" +
	")block_actors/fields/banner_patterns.proto\x12Bmousetunnel.minecraft.protocol.block_actors.fields.banner_patterns\"@\n" +
	"\x0eBannerPatterns\x12\x14\n" +
	"\x05Color\x18\x01 \x01(\x05R\x05Color\x12\x18\n" +
	"\aPattern\x18\x02 \x01(\tR\aPatternBWZUgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors/fields;fieldsb\x06proto3"

var (
	file_block_actors_fields_banner_patterns_proto_rawDescOnce sync.Once
	file_block_actors_fields_banner_patterns_proto_rawDescData []byte
)

func file_block_actors_fields_banner_patterns_proto_rawDescGZIP() []byte {
	file_block_actors_fields_banner_patterns_proto_rawDescOnce.Do(func() {
		file_block_actors_fields_banner_patterns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_actors_fields_banner_patterns_proto_rawDesc), len(file_block_actors_fields_banner_patterns_proto_rawDesc)))
	})
	return file_block_actors_fields_banner_patterns_proto_rawDescData
}

var file_block_actors_fields_banner_patterns_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_actors_fields_banner_patterns_proto_goTypes = []any{
	(*BannerPatterns)(nil), // 0: mousetunnel.minecraft.protocol.block_actors.fields.banner_patterns.BannerPatterns
}
var file_block_actors_fields_banner_patterns_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_actors_fields_banner_patterns_proto_init() }
func file_block_actors_fields_banner_patterns_proto_init() {
	if File_block_actors_fields_banner_patterns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_actors_fields_banner_patterns_proto_rawDesc), len(file_block_actors_fields_banner_patterns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_actors_fields_banner_patterns_proto_goTypes,
		DependencyIndexes: file_block_actors_fields_banner_patterns_proto_depIdxs,
		MessageInfos:      file_block_actors_fields_banner_patterns_proto_msgTypes,
	}.Build()
	File_block_actors_fields_banner_patterns_proto = out.File
	file_block_actors_fields_banner_patterns_proto_goTypes = nil
	file_block_actors_fields_banner_patterns_proto_depIdxs = nil
}
