// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_actors/fields/spawn_data.proto

package fields

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpawnData 描述刷怪笼中的一个复用字段。
//
// SpawnData describes a reusable field in mob spawners.
type SpawnData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TAG_Compound(10)
	// Go type: map[string]any
	Properties map[string]*structpb.Value `protobuf:"bytes,1,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// TAG_String(8)
	TypeID string `protobuf:"bytes,2,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	// TAG_Int(4)
	Weight        int32 `protobuf:"varint,3,opt,name=Weight,proto3" json:"Weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnData) Reset() {
	*x = SpawnData{}
	mi := &file_block_actors_fields_spawn_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnData) ProtoMessage() {}

func (x *SpawnData) ProtoReflect() protoreflect.Message {
	mi := &file_block_actors_fields_spawn_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnData.ProtoReflect.Descriptor instead.
func (*SpawnData) Descriptor() ([]byte, []int) {
	return file_block_actors_fields_spawn_data_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnData) GetProperties() map[string]*structpb.Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SpawnData) GetTypeID() string {
	if x != nil {
		return x.TypeID
	}
	return ""
}

func (x *SpawnData) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_block_actors_fields_spawn_data_proto protoreflect.FileDescriptor

const file_block_actors_fields_spawn_data_proto_rawDesc = "" +
	"\n" +
	"$block_actors/fields/spawn_data.proto\x12=mousetunnel.minecraft.protocol.block_actors.fields.spawn_data\x1a\x1cgoogle/protobuf/struct.proto\"\x8c\x02\n" +
	"\tSpawnData\x12x\n" +
	"\n" +
	"Properties\x18\x01 \x03(\v2X.mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData.PropertiesEntryR\n" +
	"Properties\x12\x16\n" +
	"\x06TypeID\x18\x02 \x01(\tR\x06TypeID\x12\x16\n" +
	"\x06Weight\x18\x03 \x01(\x05R\x06Weight\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01BWZUgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/block_actors/fields;fieldsb\x06proto3"

var (
	file_block_actors_fields_spawn_data_proto_rawDescOnce sync.Once
	file_block_actors_fields_spawn_data_proto_rawDescData []byte
)

func file_block_actors_fields_spawn_data_proto_rawDescGZIP() []byte {
	file_block_actors_fields_spawn_data_proto_rawDescOnce.Do(func() {
		file_block_actors_fields_spawn_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_actors_fields_spawn_data_proto_rawDesc), len(file_block_actors_fields_spawn_data_proto_rawDesc)))
	})
	return file_block_actors_fields_spawn_data_proto_rawDescData
}

var file_block_actors_fields_spawn_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_block_actors_fields_spawn_data_proto_goTypes = []any{
	(*SpawnData)(nil),      // 0: mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData
	nil,                    // 1: mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData.PropertiesEntry
	(*structpb.Value)(nil), // 2: google.protobuf.Value
}
var file_block_actors_fields_spawn_data_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData.Properties:type_name -> mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData.PropertiesEntry
	2, // 1: mousetunnel.minecraft.protocol.block_actors.fields.spawn_data.SpawnData.PropertiesEntry.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_block_actors_fields_spawn_data_proto_init() }
func file_block_actors_fields_spawn_data_proto_init() {
	if File_block_actors_fields_spawn_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_actors_fields_spawn_data_proto_rawDesc), len(file_block_actors_fields_spawn_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_actors_fields_spawn_data_proto_goTypes,
		DependencyIndexes: file_block_actors_fields_spawn_data_proto_depIdxs,
		MessageInfos:      file_block_actors_fields_spawn_data_proto_msgTypes,
	}.Build()
	File_block_actors_fields_spawn_data_proto = out.File
	file_block_actors_fields_spawn_data_proto_goTypes = nil
	file_block_actors_fields_spawn_data_proto_depIdxs = nil
}
