// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: entity_properties.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityProperties 保存定义实体特定属性的实体属性列表。从 v1.19.40 开始，
// 原版服务器不使用这些属性，但协议仍然支持它们。
//
// EntityProperties holds lists of entity properties that define specific attributes of an entity. As of v1.19.40, the
// vanilla server does not use these properties, however they are still supported by the protocol.
//
// Added: v1.19.40
type EntityProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IntegerProperties 是包含整数值的实体属性列表。
	//
	// IntegerProperties is a list of entity properties that contain integer values.
	//
	// Added: v1.19.40
	// Go type: []IntegerEntityProperty
	IntegerProperties []*IntegerEntityProperty `protobuf:"bytes,1,rep,name=IntegerProperties,proto3" json:"IntegerProperties,omitempty"`
	// FloatProperties 是包含浮点值的实体属性列表。
	//
	// FloatProperties is a list of entity properties that contain float values.
	//
	// Added: v1.19.40
	// Go type: []FloatEntityProperty
	FloatProperties []*FloatEntityProperty `protobuf:"bytes,2,rep,name=FloatProperties,proto3" json:"FloatProperties,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EntityProperties) Reset() {
	*x = EntityProperties{}
	mi := &file_entity_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityProperties) ProtoMessage() {}

func (x *EntityProperties) ProtoReflect() protoreflect.Message {
	mi := &file_entity_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityProperties.ProtoReflect.Descriptor instead.
func (*EntityProperties) Descriptor() ([]byte, []int) {
	return file_entity_properties_proto_rawDescGZIP(), []int{0}
}

func (x *EntityProperties) GetIntegerProperties() []*IntegerEntityProperty {
	if x != nil {
		return x.IntegerProperties
	}
	return nil
}

func (x *EntityProperties) GetFloatProperties() []*FloatEntityProperty {
	if x != nil {
		return x.FloatProperties
	}
	return nil
}

// IntegerEntityProperty 是包含整数值的实体属性。
//
// IntegerEntityProperty is an entity property that contains an integer value.
//
// Added: v1.19.40
type IntegerEntityProperty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index 表示该属性的索引。目前尚不清楚它的确切用途。
	//
	// Index represents the index of the property. It is unclear what the exact purpose of this is.
	//
	// Added: v1.19.40
	Index uint32 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	// Value 是该属性的值。
	//
	// Value is the value of the property.
	//
	// Added: v1.19.40
	Value         int32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerEntityProperty) Reset() {
	*x = IntegerEntityProperty{}
	mi := &file_entity_properties_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerEntityProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerEntityProperty) ProtoMessage() {}

func (x *IntegerEntityProperty) ProtoReflect() protoreflect.Message {
	mi := &file_entity_properties_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerEntityProperty.ProtoReflect.Descriptor instead.
func (*IntegerEntityProperty) Descriptor() ([]byte, []int) {
	return file_entity_properties_proto_rawDescGZIP(), []int{1}
}

func (x *IntegerEntityProperty) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IntegerEntityProperty) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// FloatEntityProperty 是包含浮点值的实体属性。
//
// FloatEntityProperty is an entity property that contains a float value.
//
// Added: v1.19.40
type FloatEntityProperty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index 表示该属性的索引。目前尚不清楚它的确切用途。
	//
	// Index represents the index of the property. It is unclear what the exact purpose of this is.
	//
	// Added: v1.19.40
	Index uint32 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	// Value 是该属性的值。
	//
	// Value is the value of the property.
	//
	// Added: v1.19.40
	// Go type: float32
	Value         float32 `protobuf:"fixed32,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatEntityProperty) Reset() {
	*x = FloatEntityProperty{}
	mi := &file_entity_properties_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatEntityProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatEntityProperty) ProtoMessage() {}

func (x *FloatEntityProperty) ProtoReflect() protoreflect.Message {
	mi := &file_entity_properties_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatEntityProperty.ProtoReflect.Descriptor instead.
func (*FloatEntityProperty) Descriptor() ([]byte, []int) {
	return file_entity_properties_proto_rawDescGZIP(), []int{2}
}

func (x *FloatEntityProperty) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FloatEntityProperty) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_entity_properties_proto protoreflect.FileDescriptor

const file_entity_properties_proto_rawDesc = "" +
	"\n" +
	"\x17entity_properties.proto\x120mousetunnel.minecraft.protocol.entity_properties\"\xfa\x01\n" +
	"\x10EntityProperties\x12u\n" +
	"\x11IntegerProperties\x18\x01 \x03(\v2G.mousetunnel.minecraft.protocol.entity_properties.IntegerEntityPropertyR\x11IntegerProperties\x12o\n" +
	"\x0fFloatProperties\x18\x02 \x03(\v2E.mousetunnel.minecraft.protocol.entity_properties.FloatEntityPropertyR\x0fFloatProperties\"C\n" +
	"\x15IntegerEntityProperty\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05Index\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x05R\x05Value\"A\n" +
	"\x13FloatEntityProperty\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05Index\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x02R\x05ValueBEZCgithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol;protocolb\x06proto3"

var (
	file_entity_properties_proto_rawDescOnce sync.Once
	file_entity_properties_proto_rawDescData []byte
)

func file_entity_properties_proto_rawDescGZIP() []byte {
	file_entity_properties_proto_rawDescOnce.Do(func() {
		file_entity_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_properties_proto_rawDesc), len(file_entity_properties_proto_rawDesc)))
	})
	return file_entity_properties_proto_rawDescData
}

var file_entity_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_entity_properties_proto_goTypes = []any{
	(*EntityProperties)(nil),      // 0: mousetunnel.minecraft.protocol.entity_properties.EntityProperties
	(*IntegerEntityProperty)(nil), // 1: mousetunnel.minecraft.protocol.entity_properties.IntegerEntityProperty
	(*FloatEntityProperty)(nil),   // 2: mousetunnel.minecraft.protocol.entity_properties.FloatEntityProperty
}
var file_entity_properties_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.entity_properties.EntityProperties.IntegerProperties:type_name -> mousetunnel.minecraft.protocol.entity_properties.IntegerEntityProperty
	2, // 1: mousetunnel.minecraft.protocol.entity_properties.EntityProperties.FloatProperties:type_name -> mousetunnel.minecraft.protocol.entity_properties.FloatEntityProperty
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entity_properties_proto_init() }
func file_entity_properties_proto_init() {
	if File_entity_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_properties_proto_rawDesc), len(file_entity_properties_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_properties_proto_goTypes,
		DependencyIndexes: file_entity_properties_proto_depIdxs,
		MessageInfos:      file_entity_properties_proto_msgTypes,
	}.Build()
	File_entity_properties_proto = out.File
	file_entity_properties_proto_goTypes = nil
	file_entity_properties_proto_depIdxs = nil
}
