// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/chat_phrases/sync_remove_phrases.proto

package chat_phrases

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRemovePhrases 同步被移除的快捷短语 ID。
//
// SyncRemovePhrases synchronises removed quick phrase IDs.
type SyncRemovePhrases struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	// IDs 保存按来源索引的快捷短语 ID 列表。
	//
	// IDs stores quick phrase IDs indexed by source.
	// Go type: map[string][]uint64
	IDs           map[string]uint64 `protobuf:"bytes,2,rep,name=IDs,proto3" json:"IDs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRemovePhrases) Reset() {
	*x = SyncRemovePhrases{}
	mi := &file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRemovePhrases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRemovePhrases) ProtoMessage() {}

func (x *SyncRemovePhrases) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRemovePhrases.ProtoReflect.Descriptor instead.
func (*SyncRemovePhrases) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRemovePhrases) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *SyncRemovePhrases) GetIDs() map[string]uint64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

var File_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDesc = "" +
	"\n" +
	"Apy_rpc/mod_event/minecraft/chat_phrases/sync_remove_phrases.proto\x12Zmousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases\x1a3py_rpc/mod_event/minecraft/chat_phrases/basic.proto\"\xc1\x02\n" +
	"\x11SyncRemovePhrases\x12i\n" +
	"\x05Basic\x18\x01 \x01(\v2S.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.basic.BasicR\x05Basic\x12\x88\x01\n" +
	"\x03IDs\x18\x02 \x03(\v2v.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases.IDsEntryR\x03IDs\x1a6\n" +
	"\bIDsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01BqZogithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/chat_phrases;chat_phrasesb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_goTypes = []any{
	(*SyncRemovePhrases)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases
	nil,                       // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases.IDsEntry
	(*Basic)(nil),             // 2: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.basic.Basic
}
var file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_depIdxs = []int32{
	2, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.basic.Basic
	1, // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases.IDs:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.chat_phrases.sync_remove_phrases.SyncRemovePhrases.IDsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_init() }
func file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_init() {
	if File_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_chat_phrases_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto = out.File
	file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_chat_phrases_sync_remove_phrases_proto_depIdxs = nil
}
