// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: py_rpc/mod_event/minecraft/emote/two_person_agree_join.proto

package emote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TwoPersonAgreeJoin 是客户端同意加入双人动作的请求。
//
// TwoPersonAgreeJoin is a client request to join a two-person emote.
type TwoPersonAgreeJoin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *Basic                 `protobuf:"bytes,1,opt,name=Basic,proto3" json:"Basic,omitempty"`
	// Inviter 是邀请方玩家 ID。
	//
	// Inviter is the inviting player ID.
	Inviter string `protobuf:"bytes,2,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	// EmoteID 是双人动作 ID。
	//
	// EmoteID is the two-person emote ID.
	EmoteID       string `protobuf:"bytes,3,opt,name=EmoteID,proto3" json:"EmoteID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPersonAgreeJoin) Reset() {
	*x = TwoPersonAgreeJoin{}
	mi := &file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPersonAgreeJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPersonAgreeJoin) ProtoMessage() {}

func (x *TwoPersonAgreeJoin) ProtoReflect() protoreflect.Message {
	mi := &file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPersonAgreeJoin.ProtoReflect.Descriptor instead.
func (*TwoPersonAgreeJoin) Descriptor() ([]byte, []int) {
	return file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescGZIP(), []int{0}
}

func (x *TwoPersonAgreeJoin) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *TwoPersonAgreeJoin) GetInviter() string {
	if x != nil {
		return x.Inviter
	}
	return ""
}

func (x *TwoPersonAgreeJoin) GetEmoteID() string {
	if x != nil {
		return x.EmoteID
	}
	return ""
}

var File_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto protoreflect.FileDescriptor

const file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDesc = "" +
	"\n" +
	"<py_rpc/mod_event/minecraft/emote/two_person_agree_join.proto\x12Umousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.two_person_agree_join\x1a,py_rpc/mod_event/minecraft/emote/basic.proto\"\xac\x01\n" +
	"\x12TwoPersonAgreeJoin\x12b\n" +
	"\x05Basic\x18\x01 \x01(\v2L.mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.basic.BasicR\x05Basic\x12\x18\n" +
	"\aInviter\x18\x02 \x01(\tR\aInviter\x12\x18\n" +
	"\aEmoteID\x18\x03 \x01(\tR\aEmoteIDBiZggithub.com/EmptyDea-Team/EmptyDea-core-api/pb/minecraft/protocol/py_rpc/mod_event/minecraft/emote;emoteb\x06proto3"

var (
	file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescOnce sync.Once
	file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescData []byte
)

func file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescGZIP() []byte {
	file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescOnce.Do(func() {
		file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDesc)))
	})
	return file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDescData
}

var file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_goTypes = []any{
	(*TwoPersonAgreeJoin)(nil), // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.two_person_agree_join.TwoPersonAgreeJoin
	(*Basic)(nil),              // 1: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.basic.Basic
}
var file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_depIdxs = []int32{
	1, // 0: mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.two_person_agree_join.TwoPersonAgreeJoin.Basic:type_name -> mousetunnel.minecraft.protocol.py_rpc.mod_event.minecraft.emote.basic.Basic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_init() }
func file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_init() {
	if File_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto != nil {
		return
	}
	file_py_rpc_mod_event_minecraft_emote_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDesc), len(file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_goTypes,
		DependencyIndexes: file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_depIdxs,
		MessageInfos:      file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_msgTypes,
	}.Build()
	File_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto = out.File
	file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_goTypes = nil
	file_py_rpc_mod_event_minecraft_emote_two_person_agree_join_proto_depIdxs = nil
}
